### ISSUE TITLE
Font color lost when the color mode is switched from dark mode to light mode

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#1013]
**Describe the bug**
When we load some text with specific color under dark mode, and then turn off dark mode. The text is transformed from the original color to dark, and the preset color is lost.

**To Reproduce**
1. Turn on dark mode
2. Set some text with color `#e1a25e` / or any other color like "red" "green"
3. Turn off dark mode

**Expected behavior**
The text should still be the original color

**Screenshots**
![Screen Recording 2022-06-02 at 10 47 45 AM](https://user-images.githubusercontent.com/17299418/171542986-d7e3f41d-b269-4296-be54-0bf36781889c.gif)

**Device Information**
 - OS: MacOS and iOS
 - Browser chrome and safari
 - Version 8.23

**Additional context**

**Comment by JiuqingSong** [comment]
In step 2, how did you set the color? Is it via debugger, or use some code? What code?

If you set color using setColor API, or insert the text using insertNode() API, the color will be transformed to dark mode color, and when switch back to light mode, the original color will be resumed. Setting color directly from DOM or debugger is not a supported scenario.
