### ISSUE TITLE
Pasting a list item on top of another list item causes odd behavior

### ISSUE THREAD

**Issue by jvillalobos** [microsoft/roosterjs#1065]
Steps to reproduce:

1. Start a list (bulleted or numbered)
2. Paste a **full** list item from another app. I think case I used OneNote and triple-clicked on the item, so the entire item, including the bullet, was selected.

The result is that when you paste it, you get nested bullets:

![image](https://user-images.githubusercontent.com/62568/176309955-f9d361cc-aef7-4dc7-9be1-03838df826a4.png)

If you click on the paste button and select Text Only, the result is also strange:

![image](https://user-images.githubusercontent.com/62568/176310767-8d4ae684-c40a-4edf-a9d7-2439ee5bf9bb.png)

I think the expected behavior in this case is that the lists should be merged, meaning that the pasted items should be at the same level as where the cursor is. They should probably use the bullet or number style from the origin, but I would consider that more of a nice to have.

**Comment by jvillalobos** [comment]
Here are the clipboard contents: https://1drv.ms/u/s!AsQmD_D-z0z_gdk7rJ_RjOm-HbWEsw?e=CAsSJf 

And the before and after of the paste operation:

```
<div style="font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 10.5pt; color: rgb(255, 255, 255); background-color: rgb(51, 51, 51);" data-ogsc="rgb(0,0,0)" data-ogsb="rgb(255,255,255)"><ul><li><br></li></ul></div><!--{"type":0,"isDarkMode":true,"start":[0,0,0,0],"end":[0,0,0,0]}-->
```

```
<div style="font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 10.5pt; color: rgb(255, 255, 255); background-color: rgb(51, 51, 51);" data-ogsc="rgb(0,0,0)" data-ogsb="rgb(255,255,255)"><ul><li><ul style="unicode-bidi:embed;margin-top:0in;margin-bottom:0in" type="disc">
 <li style="margin-top:0;margin-bottom:0;vertical-align:middle"><span style="font-family:Calibri;font-size:11.0pt">test</span></li></ul><br></li></ul></div><!--{"type":0,"isDarkMode":true,"start":[0,0,0,1],"end":[0,0,0,1]}-->
```

**Comment by BryanValverdeU** [comment]
This should be fixed using the Experimental Feature: `Paste with content model` 

Example:
![list items 1](https://github.com/microsoft/roosterjs/assets/8291124/8e104844-4509-4c5d-a83c-7bd733058429)
