### ISSUE TITLE
Update the color of the link will not change the underline color.

### ISSUE THREAD

**Issue by zepei-sun** [microsoft/roosterjs#1066]
**Describe the bug**
While we have a link inserted, changing the text color of the link will not change the underline of it at the same time.

**To Reproduce**
1. Go to editor
2. Insert a new link
3. Select the link content, change the color of it to red or any other color
4. See the underline of the content is still having the original color

**Expected behavior**
The under line should change the color along with the text

**Screenshots**
![image](https://user-images.githubusercontent.com/101152963/176325697-cb8c0350-54cd-4a0d-b9ff-251850427358.png)

**Additional context**
Win32 Mail app, Gmail all support the underline color change

**Comment by JiuqingSong** [comment]
This is now solved by Content Model
