### ISSUE TITLE
Undo Selection Marker logic prevents certain content from be replaced

### ISSUE THREAD

**Issue by adriantran** [Microsoft/roosterjs#107]
**To Reproduce**
1. Initialize the editor with this content:

`<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div><ol><li>BBBBBBB BBBBBBB BBB BB BBBBBBBBBB BB BBBBBBB BBB BB BBBBBBBBBBB (2d)<ul><li>a</li><li>CCCCCCCCC CCCC: CCCC CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCoCCCCCC</li></ul></li></ol><ol><li>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA (5d)</li><li>UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU. (3d)</li><li>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</li></ol>`

2. Open the sample site in Edge and select the first line (e.g. double click it), or the last line
3. Press a key on the keyboard like 'a', text isn't replaced

**Expected behavior**
Text should be replaced

(sometimes it works, most times it doesn't)

**Investigation so far**
It looks like if you're trying add or remove elements (in this case the SPAN marker) under keypress event, there is a race condition which prevents your text from being replaced.

I've also made an attempt to fix the issue by using attribute only markers--adding them to the node's parent attribute list (this includes the node's index). There's at least one problem with this solution: the node's parent could be the contenteditable div itself, but the original issue is fixed.

A different attempt involved clearing the current selection and setting it back after calling remove markers, but that doesn't work (the selection range was created from scratch too).

**Important:** when I was investigating, I had to comment the code in ShowFormatState and ShowCursorPosition sample plugins as they also modify elements on the page to locate the source of the issue.

**Device Information**
 - Browser [e.g. chrome, safari]: Edge
 - Version [e.g. 22] 42.17134.1

**Additional context**

**Comment by JiuqingSong** [comment]
Max is working on a new strategy of marking selection. I feel that way can fix this issue.

**Comment by JiuqingSong** [comment]
Fixed in 6.18.0
