### ISSUE TITLE
Replace highlighted text  not working

### ISSUE THREAD

**Issue by huahuahu** [microsoft/roosterjs#1071]
**Describe the bug**
Highlighted text is not replaced, instead new word is added on to original word

**To Reproduce**
1. Open demo page
2. Type a word ex. "movie"
3. Tap to highlight that word
4. Type another word (to override what was previously written) ex. "film"
5. The second word "film" will be added to the end of the first word "movie"
6. We end up with two words combined "moviefilm" rather than "film" replacing "movie"

**Expected behavior**

"film" replacing "movie"

**Screenshots**

https://user-images.githubusercontent.com/5757671/176805198-79775491-c8a8-4120-8890-1225f8582bf7.MP4

o help explain your problem.

**Device Information**
 - OS: [iOS]
 - Browser [Safari]
 - Version [15.5]

**Additional Text**
In a plain div, we have the expected behavior.

https://user-images.githubusercontent.com/5757671/176805218-f6455490-5e58-48eb-b323-d29cc0b97a23.MP4

**Comment by huahuahu** [comment]
The repo is on a real phone. iOS 15.5, iPhone 13.

**Comment by JiuqingSong** [comment]
I also tried on iOS 15.5, Safari. But it works fine to me.

**Comment by JiuqingSong** [comment]
I noticed that in the video I didn't see a menu of "select", "select all", ... before you select the text. So how did you select the text? When I try I need to tap the text to show a menu, then I choose "select all" so the text got selected

BTW, this operation is totally handled by browser, we don't have any special logic to replace the text.

**Comment by huahuahu** [comment]
> So how did you select the text?

Double tap the text would select it.

**Comment by JiuqingSong** [comment]
Just tried to double tap, it can select the word, but replace can still work well to me.

**Comment by biubiubiu-boom** [comment]
I can repro too, the keyboard in my device is 'English ( US )' with 'QWERTY'

**Comment by haven2world** [comment]
Same here. Looks like it's related to the keyboard. If you cannot repro, maybe you can try just type in some number or event emoji instead for the step 4.

**Comment by JiuqingSong** [comment]
That is weird. Just tried with iPad and I can repro it. Ok let me see what we can do here

**Comment by JiuqingSong** [comment]
@huahuahu  @biubiubiu-boom  @haven2world  here is a fix https://github.com/microsoft/roosterjs/pull/1127 Would you please help verify? Thansk.

**Comment by biubiubiu-boom** [comment]
Tested the fix branch, it works on my simulator's Safari. @huahuahu @haven2world

**Comment by huahuahu** [comment]
The fix works on my simulator's Safari as well

**Comment by huahuahu** [comment]
@JiuqingSong  Thanks for the quick fix. When the next version will be available? Do we have a schedule for releasing new version?

**Comment by JiuqingSong** [comment]
> @JiuqingSong Thanks for the quick fix. When the next version will be available? Do we have a schedule for releasing new version?

Planned time will be this Friday

**Comment by huahuahu** [comment]
@JiuqingSong  This bug still exists in iPad if "Request Desktop Website" is enabled.
To repro
1. Open demo site using Safari on iPad
2. Request Desktop website
3. Type a word ex. "movie"
1. Tap to highlight that word
1. Type another word (to override what was previously written) ex. "film"
1. The second word "film" will be added to the end of the first word "movie"
1. We end up with two words combined "moviefilm" rather than "film" replacing "movie"

https://user-images.githubusercontent.com/5757671/187827554-dc181268-5e20-4486-8e68-631a235e2c32.mp4


The User-Agent for iPad when requesting desktop website is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)`. `isMobileOrTablet` is false for the UA.

**Comment by huahuahu** [comment]
The provided repro is on a real device. iPhone 13. iOS 15.5, safari

**Comment by JiuqingSong** [comment]
Although I can't repro with the given step, but it sounds make sense.

**Comment by JiuqingSong** [comment]
This will be solved in #1553
