### ISSUE TITLE
Fail to input content between two tables.

### ISSUE THREAD

**Issue by mjrjoh** [microsoft/roosterjs#1072]
**Describe the bug**
Fail to input content between two tables.

**To Reproduce**
1. Go to [RoosterJs Demo Site](https://microsoft.github.io/roosterjs/index.html)
2. Insert a 2x2 table
3. Insert another 2x2 table after previous one
4. Move cursor to the end of previous table or the beginning of the second table
5. When inputting characters, cursor jumps to table below automatically.

**Expected behavior**
Inputting character successfully between two tables.

**Screenshots**
![image](https://user-images.githubusercontent.com/8462120/177088288-22d51974-7b7e-4a70-be9f-e4ef951a50c4.png)
![image](https://user-images.githubusercontent.com/8462120/177088316-3e02f3af-519c-448d-8211-112abb6512ae.png)

**Device Information**
 - OS: Windows 11
 - Browser Edge
 - Version 8.26.1

**Comment by romanisa** [comment]
If we look at the behavior in other editors like Microsoft Word, this would just merge the two tables. Would merging the two tables in this case, solve the problem? 
Also, if a content is needed to be added in between two tables, adding a newline before adding another table works. Does that suffice your scenario?

**Comment by mjrjoh** [comment]
We are not able to guarantee that there is always a new line between two tables. Because it could be deleted intentionally or unintentionally at any time.

Merging tables looks good. But I wonder how to merge two tables with different column number. For example, merge table 2x2 and table 3x3.

**Comment by romanisa** [comment]
Ok, we think that we can just insert an empty line whenever we detect that there is a table before when adding a new table. The user can remove that line or do undo to add it back. That should suffice your scenario. 

@BryanValverdeU do you think you can take care of that?
