### ISSUE TITLE
Table cell selection selects multi tables

### ISSUE THREAD

**Issue by StephenArk30** [microsoft/roosterjs#1073]
**Describe the bug**
When more than 3 tables are selected, table cell selection plugin will once select multi tables.

**To Reproduce**
1. Insert more than 3 tables
2. Select one table
3. Select the second table
4. Select the third table

**Expected behavior**
Only select the one I select

**Screenshots**
![rooster](https://user-images.githubusercontent.com/20739682/177356222-b514e4b2-be59-4a29-bda1-a983f3fec469.gif)

**Device Information**
 - OS: Windows10
 - Browser chrome
 - Version 97.0.4692.99

**Comment by BryanValverdeU** [comment]
Thank you for the fix!
