### ISSUE TITLE
The bold state is wrong from `getFormatState()` after setting the font size and toggling bold.

### ISSUE THREAD

**Issue by Foolment** [microsoft/roosterjs#1078]
**Describe the bug**
The bold state is wrong from `getFormatState()` after setting the font size and toggling bold.

I guess the zero-width space should be the cause. The cursor is placed out of the `<b>` node.
Do we have any way to remove that invisible space?
![image](https://user-images.githubusercontent.com/3321518/177937256-21abb162-4d7f-4472-95dd-d57c2cd8d6cd.png)

**To Reproduce**
1. Go to the [RoosterJs Demo Site](https://microsoft.github.io/roosterjs/index.html)
2. Click on **Increate Font Size** button
3. Click on the **Bold** button
4. Type in some content
5. Move cursor to the beginning of the line
6. Check the bold state from `getFormatState()`

**Expected behavior**
Bold state should be true.

**Screenshots**
https://user-images.githubusercontent.com/3321518/177936669-35ea02b2-d9e0-42d3-a18b-bb4876d8a2a3.mp4

**Device Information**
 Mac Chrome and Android WebView both can be reproduced.

**Comment by JiuqingSong** [comment]
This is now solved by Content Model.
