### ISSUE TITLE
Add param to customize classname for Watermark

### ISSUE THREAD

**Issue by janineliao** [microsoft/roosterjs#1079]
Currently the Watermark constructor doesn't provide a way for consumers to customize the classname. 
https://microsoft.github.io/roosterjs/docs/classes/roosterjs_editor_plugins.watermark.html#constructor

For more complicated style overrides, we are relying on the Watermark internal classname, but this is unstable as it could change in the future. 
![image](https://user-images.githubusercontent.com/108954733/178355771-65935f9a-0fbc-4c6f-ab85-cd51aaeef0b8.png)

**Comment by romanisa** [comment]
@ianeli1 can you please help address this as a partner request?
