### ISSUE TITLE
Cannot Show Image Cut/Copied from Outlook iOS

### ISSUE THREAD

**Issue by biubiubiu-boom** [microsoft/roosterjs#1080]
**Describe the bug**
Cannot Show Image Cut/Copied from Outlook iOS. Those images don't have the http URL and stored in memory.

**To Reproduce**

1. Open Outlook iOS client, open compose view
2. Attach an image through toolbar
3. Select the image with some text, cut them all
4. Open iOS Safari, open RoosterJS demo
5. Paste content into the demo editor. Image cannot show
6. Open another website with contentEditable attribute
7.  Paste content into the website. Image showed.

**Expected behavior**
In repro step4, image should show into editor.

**Screenshots**
[repro video](https://user-images.githubusercontent.com/11981186/178425611-12b7eb03-39eb-414f-8408-e1f9f2aa15df.mp4)

**Device Information**
 - OS: iOS
 - Browser Safari
 - Version 15.5 (could be repro before 15.5 too)

**Additional context**
iOS Safari has a system behavior that would auto-exchange some resource's URL as ' blob://xxx' if those resources didn't have a specific src like('[https://xxxxxx.png').](https://xxxxxx.png%27%29./) If you try the repro step 1-3 and 6-7 , you could see the image has a blob url when it has been pasted into another website with contentEditable.

**Comment by JiuqingSong** [comment]
@biubiubiu-boom As per discussion offline, can we close this issue now?

**Comment by biubiubiu-boom** [comment]
@JiuqingSong  Sure!
