### ISSUE TITLE
[roosterjs-editor-core] incorrect package name casing for "coreApi"

### ISSUE THREAD

**Issue by janineliao** [microsoft/roosterjs#1085]
The casing for "coreApi" in _**roosterjs-editor-core\lib\editor\Editor.js**_ does not match the one that gets installed: "coreAPI"

![image](https://user-images.githubusercontent.com/108954733/178831703-61a80975-4d29-473e-9fde-872be82110f4.png)

**Comment by JiuqingSong** [comment]
@janineliao as per discussion offline, can we close this issue now?

**Comment by janineliao** [comment]
@JiuqingSong sure, feel free to close this as it's not reproducible on your side, and may be specific to my machine. thanks for your help in looking into this :)
