### ISSUE TITLE
Support Content Model

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#1093]
Support Content Model in roosterjs.

https://microsoft.sharepoint.com/:w:/t/outlookwebteam/EQ_5svQWahlCpe0q2kvgu3MB2WoxwIz6V_YzPhOZ5epf5Q?e=3C7pdE&isSPOFile=1

**Comment by evilbs** [comment]
> 

hi JiuqingSong，I want to know about this disign file, can you share it?
<img width="832" alt="image" src="https://user-images.githubusercontent.com/3305041/196479925-404ca0a8-437c-4334-a17f-88dbf5069805.png">
