### ISSUE TITLE
Alignment overrided after toggling bullet

### ISSUE THREAD

**Issue by StephenArk30** [microsoft/roosterjs#1102]
**Describe the bug**
If the above line has set a text-align, and the below one does not, the down line will be aligned to the same with the above one after toggling the bullet.

**To Reproduce**
1. Write two lines 1 and 2
2. Align 1 to center
3. Select 1 and 2
4. Toggle bullet (or number)
5. 2 is center aligned

**Expected behavior**
Do not override line 2's alignment.

**Screenshots**
![bullet-align](https://user-images.githubusercontent.com/20739682/179355483-b92a9de0-f119-4162-a9bd-29bd8e45b6f9.gif)

**Device Information**
 - OS: Mac
 - Browser chrome
 - Version 8.27.0

**Comment by JiuqingSong** [comment]
This seems not repro to me now
