### ISSUE TITLE
normalizeRect incorrectly returening null

### ISSUE THREAD

**Issue by StephenArk30** [microsoft/roosterjs#1117]
**Describe the bug**
I see code in normalizeRect.ts and I don't understand [this check](https://github.com/microsoft/roosterjs/blob/f8c1746443ffe128d93efc8d04775b426c109f42/packages/roosterjs-editor-dom/lib/utils/normalizeRect.ts#L10):

```typescript
return left + right + top + bottom > 0
        ? ...
        : null;
```

I'm not sure why ``left + right + top + bottom`` should always be positive. It might be negative, or just happens to be 0. See this [example](https://codepen.io/stephenark30/pen/wvmdRwW).

This causes bugs when a very tall element's rect is passed in. For example, in [TableResize plugin](https://github.com/microsoft/roosterjs/blob/f8c1746443ffe128d93efc8d04775b426c109f42/packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts#L134), if the table is taller than the window, and you scroll to bottom, then move mouse on the table, the resizer won't show.

I'm not entirely sure what this function is used for. Maybe we should change this to ``left === 0 && right === 0 && top === 0 && bottom === 0``?

@melvsparks @JiuqingSong

**Comment by StephenArk30** [comment]
https://user-images.githubusercontent.com/20739682/180229003-5db55d4f-51b6-4c81-bfe4-96d412999602.mov

Screenshot

**Comment by StephenArk30** [comment]
@melvsparks @JiuqingSong

**Comment by romanisa** [comment]
@BryanValverdeU can you please take a look?

**Comment by BryanValverdeU** [comment]
It seems like the current check `left + right + top + bottom > 0` was to avoid that all these properties were different that 0. So yes, I think we can update this to` left === 0 && right === 0 && top === 0 && bottom === 0`
