### ISSUE TITLE
Old selection is restored on Chromium browsers after re-focussing the editor

### ISSUE THREAD

**Issue by MelvilQ** [microsoft/roosterjs#1124]
**Describe the bug**
On Chromium browsers (i.e. Chrome, MS Edge), when the editor loses the focus with text being selected, the selection is restored after the editor regains the focus. This is reproducible on the sample site.

**To Reproduce**
1. Go to https://microsoft.github.io/roosterjs/index.html
2. Select some text.
3. Click in empty space to make the editor lose focus.
4. Click somewhere on the text (not necessarily on the previously selected part)
5. The editor regains the focus and the previously selected text is selected no matter where the click was.

**Expected behavior**
The cursor should move where the click was and the previous selection should not be restored, as it already is on Firefox/Safari.

**Device Information**
- OS: Windows 10
- Browsers: Chrome 103.0.5060.134, MS Edge 103.0.1264.71

**Comment by JiuqingSong** [comment]
Close old issue.
