### ISSUE TITLE
Issue with BIU

### ISSUE THREAD

**Issue by JiuqingSong** [Microsoft/roosterjs#113]
**Describe the bug**
Sometimes Ctrl+I can't cancel italic style, similar with B,U

**To Reproduce**
(1) Type something
(2) Press 'ctrl+i'
(3) Continue typing, now in italics, and finish a word without hitting space
(4) Press 'ctrl+i'
(5) Hit space, and continue typing

**Expected behavior**
Not italic anymore

**Device Information**
 - OS: Windows 10
 - Browser Chrome 69, Edge 17.17134

**Comment by Adjective-Object** [comment]
More broadly this happens any time you change formatting state in chrome and then press space.

**Comment by JiuqingSong** [comment]
Fixed in 6.18.0
