### ISSUE TITLE
Image Resize Plugin isn't compatible with touch + pen

### ISSUE THREAD

**Issue by adriantran** [microsoft/roosterjs#115]
**Describe the bug**
Touch + pen isn't supported when trying to resize image, page just pans
Also, drag target/red blocks are really small for touch

**Device Information**
 - OS: Windows 10 RS3
 - Browser Edge and Chrome

**Additional context**
Pen seems to be working for RS2

**Comment by JiuqingSong** [comment]
I'll make a fix soon

**Comment by JiuqingSong** [comment]
Close old issues.
