### ISSUE TITLE
"Zero width space" is announced unexpectedly by voice over 

### ISSUE THREAD

**Issue by huahuahu** [microsoft/roosterjs#1151]
**Describe the bug**

"Zero width space" is announced by voice over when changing inline style when the editor content is empty.

**To Reproduce**
1. Go to demo site
2. Enable voice over
3. Click on editor
4. Tap "Increase font size" button
5. "Zero width space" is announced.

**Expected behavior**
 "Zero width space" shouldn't announced.

**Screenshots**

https://user-images.githubusercontent.com/5757671/182345763-a7f94a82-3d93-4926-a42e-d8ebe202fd94.mp4

explain your problem.

**Device Information**
 - OS: Mac OS
 - Browser: Safari
 - Version: 15.6 (17613.3.9.1.5)

**Additional context**
I think the reason is [here ](https://github.com/microsoft/roosterjs/blob/7231c39b80b30f01362c06f3c3899c03700148e5/packages/roosterjs-editor-api/lib/utils/applyInlineStyle.ts#L38). Can we avoid adding zero width space here?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5757671/182346335-75f33e2b-c327-41d4-991f-cd52c984c854.png">

**Comment by huahuahu** [comment]
It's happens in iOS as well. But I can't repo using demo site since accessibility isn't well supported.
If we create a web app using the sdk, it can be repro as well.

**Comment by huahuahu** [comment]
Can we use [aria-hidden](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden) here?

**Comment by JiuqingSong** [comment]
This is not an easy one. Current approach of formatting text has this limitation. We are working on Content Model which will fully change the formatting approach which should be able to fix this problem.

**Comment by huahuahu** [comment]
@JiuqingSong Content Model seems to be a large project. Do we have an ETA for that?

**Comment by JiuqingSong** [comment]
Content Model will need long time to finish.

Here is a partial fix, not completed yet: https://github.com/microsoft/roosterjs/pull/1161

I'd like to get your feedback on this fix, see if it works and if it has any side effect.

@huahuahu thanks.

**Comment by huahuahu** [comment]
The issue doesn't exist after the fix. I don't find any side effect.

**Comment by JiuqingSong** [comment]
Thanks, @huahuahu .

I still need to handle some related issue from this change, so please expect a couple of days to finsih

**Comment by JiuqingSong** [comment]
The fix was checked in. To enable it, need to turn on an experimental feature "PendingStyleBasedFormat" when create editor:

```ts
new Editor(div, {
  ...
  experimentalFeatures: [
     ...
     ExperimentalFeatures.PendingStyleBasedFormat,
  }
});
```

**Comment by JiuqingSong** [comment]
You can add a flight in your code and put the experimental feature behind the flight.
________________________________
