### ISSUE TITLE
Cannot resize the table on v8.x.x

### ISSUE THREAD

**Issue by BDMChau** [microsoft/roosterjs#1156]
I'm upgrading the version from 7.16.0 to 8.28.1 and the plugin TableResize does not work, I cannot resize the table, I tried to downgrade to v8.13.0 and v7.16.0 everything is good
Here is my pseudo code (pluginList.tableResize is always **true**)

    let editorInstanceTogglePlugins = {
      tableResize: pluginList.tableResize ? new TableResize() : null,
      ...
    };
    let plugins = [
      ...Object.keys(editorInstanceTogglePlugins).map(
        (k) => (editorInstanceTogglePlugins)[k]
      ),
      ...this.props.plugins,
    ];
    let options = {
      plugins: plugins,
      ...
    };
    this.editor = new RoosterJsEditor(this.contentDiv, options);

**Comment by JiuqingSong** [comment]
Hi, table resize works well in roosterjs demo site (https://microsoft.github.io/roosterjs/index.html) with latest build (8.28.1). Would you please provide a repro project such as a link to codepen or similar site so that we can debug.

Thanks.

**Comment by BDMChau** [comment]
Thank you, I visited the demo site before deciding to upgrade to the latest version (v8.28.1). It's still work on v8.13.0 but not working from v8.14.0 onwards.
I cannot give you the code because it's our privacy, we just keep all of code on v7.16.0 and follow this [link](https://github.com/microsoft/roosterjs/wiki/RoosterJs-8) to compare the change.
Everything we did

1. Rename plugin getDefaultContentEditFeatures to getAllFeatures function
2. Change clearBlockFormat to clearFormat(_, ClearFormatMode.Block)
3. Rename plugin ImageResize to ImageEdit

**Comment by JiuqingSong** [comment]
Thanks. No need to provide the full code of your project, but just need to build a simple repro will be good enough.

**Comment by BDMChau** [comment]
well, we just found out the problem is because <Drawer /> component of [Mui](https://mui.com/material-ui/react-drawer/)
if Roosterjs editor is used in a place that was wrapped by [Drawer](https://mui.com/material-ui/react-drawer/), it will not work well, especially the plugin TableResize I mentioned above.
other places are still working well @~@

**Comment by BDMChau** [comment]
we're still in finding a solution, if you have something new, please let me know, thank you

**Comment by BryanValverdeU** [comment]
Maybe you could check if the z-index of the Drawer component is higher than 0. 
By default, the Resize controls have z-index: 0, so maybe the elements are showing, but behind the Drawer component.

You could use onShowHelperElement parameter in TableResize Plugin constructor to update the z-index style of the Resize Elements. 

https://github.com/microsoft/roosterjs/blob/ea1bb65b6e3ad38e6ca1a6e50a5c79b7a719cf3b/packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts#L30

**Comment by BDMChau** [comment]
@BryanValverdeU Thank you, you saved my life 💯
