### ISSUE TITLE
Cannot add table when editor empty

### ISSUE THREAD

**Issue by BDMChau** [microsoft/roosterjs#1178]
Click on empty editor and press the BackSpace key (this will delete empty div in picture below),
insertTable(...) now will have an error because editor.getElementAtCursor() is null
New issue I just find out on v8.29.0

![image](https://user-images.githubusercontent.com/64347888/184538512-49463a39-9fe3-4aaa-a889-c00d59cc16a8.png)

**Comment by JiuqingSong** [comment]
@BryanValverdeU can you help take a look?

Thanks.
