### ISSUE TITLE
Provide checklist functionality 

### ISSUE THREAD

**Issue by t-camilac** [microsoft/roosterjs#1197]
The checklist is a list of items required, to be done, or points to be considered that is attached to a checkbox that can be checked/unchecked to define when the task is completed or not.

Eg.
- [ ] task 1
- [ ] task 2

**Comment by JiuqingSong** [comment]
You can build your own plugin to support this feature. 

Generally, roosterjs is a pure client library, it doesn't handle any server side related things. For a task list, it needs to know how to save the task result, that is beyond the scope of roosterjs.
