### ISSUE TITLE
Missing roosterjs-react v8 sample

### ISSUE THREAD

**Issue by TeckTn** [microsoft/roosterjs#1211]
Is there any sample using roosterjs-react v8 ?

**Comment by JiuqingSong** [comment]
[RoosterJs demo site](https://microsoft.github.io/roosterjs/index.html) is built on top of roosterjs-react. You can check its source code [here](https://github.com/microsoft/roosterjs/tree/master/demo/scripts). You can also use the "Try roosterjs-react in CodePen" button from https://microsoft.github.io/roosterjs/index.html#options to general a simple demo with source code.
