### ISSUE TITLE
Tables with clear borders renders with borders in Outlook Desktop

### ISSUE THREAD

**Issue by florian-msft** [microsoft/roosterjs#1215]
**Describe the bug**
Setting a `TableBorderFormat` or `Clear` does not remove the borders which renders fine in web browsers but leads to borders still appearing in Outlook Desktop. 

**To Reproduce**
1. Insert a table
2. Go to _API Playground_
3. Select the _VTable API_ and create a VTable from the inserted table
4. Select any cell and click _Predefined_ > _Clear_
5. The table has transparent borders, but the borders still exist (1px solid transparent)

**Expected behavior**
The borders are removed completely (border width of 0 or style of `none`).

**Screenshots**
N/A

**Device Information**
 - OS: Windows
 - Browser: Outlook Desktop (Win32, Word)
 - Version: N/A

**Additional context**
I believe the issue lies in [applyTableFormat.ts](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-dom/lib/table/applyTableFormat.ts). One possible fix might be to set the border width to 0 or the style to `none` when the border color is `transparent`.

**Comment by JiuqingSong** [comment]
This is now solved by Content Model. We will publish new Content Model Editor soon.
