### ISSUE TITLE
Error when deleting selection ending in empty nested bullet

### ISSUE THREAD

**Issue by tshibley** [microsoft/roosterjs#1261]
**Describe the bug**
When deleting a selection that ends in an empty nested bullet, we end up with an extra bullet, and incorrect styling across the remaining bullet. 

**To Reproduce**
1. Go to Rooster example site 
2. Create a list ending in an empty nested bullet 
3. Select the whole list
4. Press "delete"
5. Observe duplicated bullets with incorrect styling

**Expected behavior**
A single remaining bullet, without the styling of a nested bullet. 

**Screenshots**
https://user-images.githubusercontent.com/15166410/190506087-3a46d323-94c0-4a98-bedf-9138e2971e5c.mov

**Device Information**
 - OS: Mac
 - Browser: Chrome

**Comment by tshibley** [comment]
The underlying issue appears to be in the browser implementation of `contenteditable` - Rooster isn't doing any handling of this delete selection right now as far as I know, and I confirmed in the Gmail editor that this same behavior is created (minus the list styling, but that makes sense). 

So the fix will probably involve adding a new feature in `listFeatures.ts` that handles this type of selection deletion


https://user-images.githubusercontent.com/15166410/190506986-2bb30d3e-ee1e-48ef-a24c-e2e0db6f653e.mov

**Comment by JiuqingSong** [comment]
#1660

**Comment by JiuqingSong** [comment]
Fixed with Content Model in #1660
