### ISSUE TITLE
Toggling type of nested list creates multiple root lists

### ISSUE THREAD

**Issue by tshibley** [microsoft/roosterjs#1270]
**Describe the bug**
When toggling the list type for a nested list, we end up with a messy state in the dom + multiple root nodes. 

**To Reproduce**
See the video below for an example of how to reproduce: 

https://user-images.githubusercontent.com/15166410/191145215-4a490d03-091c-4b31-b4d1-c084f97a7cef.mov

As you can see the list gets split into two, with one `ol` root and one `ul` root. This also creates a display issue in the DOM, since we add a small vertical separation between the lists. 

**Expected behavior**
I would expect theses lists to have one root node after toggling the type of the whole list.

**Screenshots**

**Device Information**
 - OS: Mac
 - Browser Chrome

**Comment by tshibley** [comment]
I believe the issue is caused by the way the core `VListItem` type works - which will potentially make it tricky to fix.

Since we store the list types of an item as an array, when we call `changeListType` on an item we only replace the closest list type to the item. So then when we go to `writeBack` those changes into the DOM, the earlier list types in our array no longer match the previous bullets, so we create new lists. 

When it comes to nesting lists, I don't believe the type of the previous levels matters at all for display? So it might be the case that we could ignore mismatches in the types of lists that aren't the one directly surrounding the bullet when we call `writeBack`? 

I think this would generally leave us with a cleaner/more correct DOM as an end user would expect it, but I'm a little worried that it would create other side effects, since it would make `writeBack` a potentially lossy operation - especially on lists that had been pasted into the composer for instanct.

**Comment by JiuqingSong** [comment]
This is an interesting finding. For now I don't know if there is any side effect, but I think we'd better put this change under an ExperimentalFeature since it changes the original behavior. Then you can enable the feature in your project. After some time if we didn't see any issue, we can turn this Experimental feature always on.
