### ISSUE TITLE
How do I create custom blocks

### ISSUE THREAD

**Issue by chimon2000** [microsoft/roosterjs#128]
**Describe the bug**
I am trying to figure out how to create custom blocks.  Currently we achieve this using Draft.js, but we've been actively looking for a less involved solution.

**To Reproduce**
N/A

**Expected behavior**
The block should be able to:
* Display some image
* Disable backspace or delete the entire block on backspace.
* Override the mouse events (dblclick, right click, etc.)

The documentation is not very clear about how to achieve this using plugins.

**Screenshots**
Here is an example using Quill (click 'Add Action' and input some text)
https://stackblitz.com/edit/quill-demo
![image](https://user-images.githubusercontent.com/6907797/47893812-5bd32f80-de35-11e8-82ea-7d6651b0068c.png)

**Device Information**
N/A

**Additional context**
N/A

**Comment by JiuqingSong** [comment]
Currently we don't provide an API to insert such block, but you can do this by building such block element (e.g. DIV) on your own then insert it using Editor.insertNode().

To disable editing, you need to set contenteditable=false to your block. For example:

var block = document.createElement("div");
block.contentEditable = "false";
block.innerHTML = "Hello block!";
editor.insertNode(block);
