### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by totht91** [Microsoft/roosterjs#130]
Dear maintainers, 

Are there any plans to support Markdown?

**Comment by JiuqingSong** [comment]
There were some discussion about markdown, but not have detailed plan yet.

**Comment by fmuecke** [comment]
That's bad. Markdown support would really be great!

**Comment by froboy** [comment]
Would it be possible to reopen discussion of this issue? Markdown or some similar inline formatting option is pretty standard across other platforms, despite everyone having their own unique implementation. It'd be great to have this feature parity here.

**Comment by bennypowers** [comment]
A typical day on Azure DevOps:

- Respond to discussions on User Stories, Tasks, Bugs, etc. I can't use markdown, it takes me between 2 and 3 times as long to format comments, I don't have syntax highlighting
- Context switch to discussions on Pull Requests, where I do have markdown.
- Context switch back to Tasks where I don't have markdown 
- repeat 1-3

Markdown support here would go a long way to improving the UX of Azure DevOps. Here's an easy fix: use the `<zero-md>` custom element to render the output!

https://github.com/zerodevx/zero-md/
