### ISSUE TITLE
Copy pasting content with links having istemptitle doesn't remove title

### ISSUE THREAD

**Issue by adriantran** [Microsoft/roosterjs#131]
Hyperlink plugin creates temporary title for CTRL+Click message, but it doesn't work well with copy-paste scenario.

Main issue is when pasting one of these anchor elements, the temp title is still there and is now the true title. Perhaps the correct fix is to setData to the clipboard ourselves when user runs copy.

**Comment by JiuqingSong** [comment]
Good bug! I'll try to find a solution.
