### ISSUE TITLE
Copying tables turns them into single line

### ISSUE THREAD

**Issue by Andres-CT98** [microsoft/roosterjs#1322]
**Describe the bug**

Copying and pasting in a certain way causes the table to turn into a single line.

**To Reproduce**
1. Copy this table into the roosterjs demo site: 
<table><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>4</td><td>5</td><td>6</td></tr><tr><td>7</td><td>8</td><td>9</td></tr></table>

2. Paste the table on the editor

3. Copy the table on the editor while using table selection, the table needs to look all greyed out

4. Paste it again, it will turn into a line

**Expected behavior**
Table pastes like normal. This behaviour can be seen if the table is copied using normal selection, where the contents of the table are highlighted blue.

**Device Information**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 8.33.1

**Comment by jvillalobos** [comment]
I'm not able to reproduce this in Firefox. When you paste the table on the demo site, it's pasted with less formatting, but copying it and pasting it again works correctly. It seems there's something in the styling that is preserved on Edge and Chrome that is breaking the following copy/paste actions.
