### ISSUE TITLE
Toggling lists creates nesting DIVs

### ISSUE THREAD

**Issue by richardtagger** [microsoft/roosterjs#1358]
**Describe the bug**
Toggling list on and off creates nested DIVs - once per toggle meaning content can get very deep in the DOM

**To Reproduce**
1. From the Rooster Demo Site
2. Create a list of a few items
3. Select it and toggle the list off via the toolbar
4. Toggle the list back again
5. Repeat 3-4 a few times

**Expected behavior**
The HTML in the DOM matches what we're seeing visually - a list (or not depending on how many times you toggled)

**Screenshots**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/692240/197635381-99c79f93-7cc8-4130-abad-484af1c82265.png">

**Comment by JiuqingSong** [comment]
This is now fixed by Content Model:

![contentmodellist](https://user-images.githubusercontent.com/23065085/211995854-a2647fed-02f7-46cd-a441-63757999c054.gif)
