### ISSUE TITLE
Provide proper documentation on how to run roosterjs with typescript in react

### ISSUE THREAD

**Issue by pramodsk** [microsoft/roosterjs#1404]
**Describe the bug**
Can anyone please Provide proper documentation on how to run roosterjs with typescript in react ?

**Comment by romanisa** [comment]
Hi! We do not have a proper documentation at the moment, and we plan to invest in it in future. For now, if you are looking to get started, the best place would be to look at our sample site: https://microsoft.github.io/roosterjs/index.html. You can view its code on CodePen. Also https://github.com/microsoft/roosterjs/wiki has some links on usage. 
Please let us know if you have specific questions on usage.
