### ISSUE TITLE
Picker Plugin onRemove is not called

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoft/roosterjs#1424]
**Describe the bug**
[`onRemove`](https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.pickerdataprovider.html#onremove) is not working when we try to delete picked content

**To Reproduce**

following is a webpack project which reproduces issue
[rooster_issue.zip](https://github.com/microsoft/roosterjs/files/10057786/rooster_issue.zip)

relevant snippet from above cod
```ts
// following is minimal code to reproduce, 
// code for opening closing picker popup is not listed here, those are working fine for me
import { createEditor, PickerPlugin } from 'roosterjs';

const contentDiv = document.createElement('div');
document.body.appendChild(contentDiv);

const additionalPlugins = [
    new PickerPlugin(
        {
            onInitalize() {

            },
            onDispose() {

            },
            onIsSuggestingChanged() {

            },
            onRemove() {
                console.log('REmove Called');

                return null!;
            },
            queryStringUpdated() {
                
            },
        },
        {
            changeSource: "MyPickerPlugin",
            elementIdPrefix: 'pick-',
            triggerCharacter: '@',
        }
    )
];

const initialContent = /*html*/`Hello <span id="pick-123">@user</span> , welcome again`;
createEditor(
    contentDiv,
    additionalPlugins,
    initialContent
);
```
1. Run above code
2. try to delete @user
3. in console we should see `Remove called` , but it never occurs

**Expected behavior**
in console we should see `Remove called` 

**Device Information**
 - OS: Widowns
 - Browser Edge 107 , firefox 107
 - Version ^8.36.0

**Comment by JiuqingSong** [comment]
This is a good finding. I think it is because from the very beginning the picker plugin was not designed for a normal `<SPAN>` tag to work. You can try to change `SPAN` to `A` then it will trigger `onRemove()`.
