### ISSUE TITLE
Change format not working if call `setFontSize` and `toggleBold` in a row

### ISSUE THREAD

**Issue by huahuahu** [microsoft/roosterjs#1458]
**Describe the bug**
toggleBold or setFontSize not working when calling `setFontSize` and `toggleBold` in a row.

**To Reproduce**
1. Checkout #1457 
   This pr call `setFontSize` and `toggleBold` in a row when the italic button tapped.
3. run `yarn start` to start the demo
4. Tap some text from iPad's keyboard
5. Tap italic button
6. Tap some text from iPad's keyboard

**Expected behavior**
After tapping the italic button, the text should be bold as `toggleBold` is called.

**Screenshots**

https://user-images.githubusercontent.com/5757671/206655378-69c5bab5-261f-40e5-ab1a-5d91182aa27b.mov

shots to help explain your problem.

**Device Information**
 - OS: iPad simulator on Mac OS 13.0.1 (22A400)
 - Browser: iPad Safari 16.1

**Additional context**

If `PendingStyleBasedFormat` is on, it can't work as well. It seems related to the soft keyboard. If I type by hard keyboard, it can work as expected.

https://user-images.githubusercontent.com/5757671/206656572-652a8859-c285-4111-8488-f6141281222a.mov

**Comment by juliaroldi** [comment]
Hey @huahuahu, could provide more information about the issue? I followed the steps you provided and it is working as expected. 
![ipad](https://user-images.githubusercontent.com/87443959/207707233-281b4d7a-7503-4745-89c9-9cb0dc768098.gif)

**Comment by huahuahu** [comment]
@juliaroldi You can try tapping the suggested text at top of the keyboard instead of tapping each key.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/5757671/208582944-6cd01f75-1c62-43a4-ac7d-3b65e0eaf233.png">

**Comment by JiuqingSong** [comment]
![1458](https://user-images.githubusercontent.com/23065085/213766292-a81ee326-d54b-46c1-8934-815ace9de851.gif)

This is now solved by content model. We will publish a new version of editor that support content model soon.

**Comment by huahuahu** [comment]
@JiuqingSong  How can I test content model in the latest master branch?

**Comment by JiuqingSong** [comment]
@huahuahu For now, the easiest way to test is to go to https://microsoft.github.io/roosterjs/index.html#contentModel then click the pencil button from the right pane, it will give you a new format bar. Then you can test the new format buttons.

To test in code, you need to create a new editor class for content model to implement `IExperimentalContentModelEditor` interface. This is not included in production code yet but you can copy the code from https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controls/editor/ExperimentalContentModelEditor.ts just for test.

**Comment by huahuahu** [comment]
Verified! Thanks @JiuqingSong. Looking forward to the new content model.
