### ISSUE TITLE
roosterjs dependencies on publish is not correct

### ISSUE THREAD

**Issue by milliezhang-qinlan** [microsoft/roosterjs#1468]
**Describe the bug**
When I update the roosterjs version in my project package.json as 8.35.1 and do npm install, it will install the sub-packages of roosterjs such as roosterjs-editor-plugins as version 8.38.0

I noticed the dependencies of roosterjs is as follows:
![image](https://user-images.githubusercontent.com/63031370/208062813-40579353-1825-4fb8-9539-815b4de98393.png)

And the caret "^" sign would make it install the latest version with major version unchanged, in 8.x.x format, and results in the 8.38.0 version of roosterjs-editor-plugins installed.

**To Reproduce**
1. update project package.json and change roosterjs version to an older one such as 8.35.1
2. Do npm install and check the sub-packages version installed

**Expected behavior**
Sub-packages such as roosterjs-editor-plugins should be in 8.35.1 as well

**Comment by JiuqingSong** [comment]
This is expected behavior and totally by design. We expect latest version to be installed.
