### ISSUE TITLE
Tapping Backspace key will delete all adjacent non-contentEditable elements

### ISSUE THREAD

**Issue by Dream0827** [microsoft/roosterjs#1475]
**Describe the bug**
When there are two div elements that include an image element, and they are not contentEditable, if you put cursor on the next line of the second element and tap Backspace, the two div elements will be both deleted.

**To Reproduce**
1. Set `EditorOptions.initialContent` as two div non-contentEditable elements, such as **div1** and **div2**
```
<div contenteditable="false" id="div1">
    <img src="https://microsoft.sharepoint.com/test.img">
</div>
<div contenteditable="false" id="div2">
    <img src="https://microsoft.sharepoint.com/test.img">
</div>
```
2. Put cursor on the next line of **div2**
3. Tap `Backspace` in the keyboard
4. Both **div1** and **div2** are deleted

**Expected behavior**
Only **div2** is deleted

**Device Information**
 - Browser: chrome

**Additional context**
Here is my test: https://codepen.io/dreamxcf/pen/poZgMMV

**Comment by JiuqingSong** [comment]
This is a browser behavior rather than a roosterjs bug. It can also repro with just a simple HTML page without any javascript code:
```html
<html>
<body>
<div contenteditable>
test <div contenteditable=false>test 1</div><div contenteditable=false>test 2</div>
test
</div>
</body>
</html>
```

To workaround it, better add some editable content between these two readonly blocks to allow browser put cursor there.
