### ISSUE TITLE
Circular dependency in roosterjs-editor-dom

### ISSUE THREAD

**Issue by pranavgk** [Microsoft/roosterjs#15]
We are trying to import roosterjs-react into our product and in process, have a step that ensures that the plugin being imported has no circular dependencies.
Unfortunately, importing roosterjs-editor-dom is causing this step to fail due to the following circular dependency:
 
Circular dependency in modules.
**Attempting to add** 
roosterjs-editor-dom\lib\blockElements\NodeBlockElement.js
 
**Dependencies**: 
* roosterjs-editor-dom\lib\domWalker\getInlineElement.js
* roosterjs-editor-dom\lib\domWalker\getBlockElement.js
* roosterjs-editor-dom\lib\blockElements\NodeBlockElement.js 
 
Do you think we can have a single dist file or are there any other ways to address this?

**Comment by JiuqingSong** [comment]
I fixed this by merging these files together.
