### ISSUE TITLE
The element with `tabindex` attribute cannot be focused.

### ISSUE THREAD

**Issue by Dream0827** [microsoft/roosterjs#1501]
**Describe the bug**
When we set `tabindex` attribute such as `tabindex="0"` for an element, it will lead to an issue that the element cannot be focused easily.

**To Reproduce**
1. Insert a Bullet/Numbering list
2. Set `tabindex` attribute of the ul/ol element as 0
3. Focus other area except the ul area first
4. Then tap on the ul element, which cannot be focused again. 

**Expected behavior**
The ul element can be focused when tapping

**Device Information**
 - Browser: chrome

**Additional context**
The same issue for anchor element.
Here is my test: https://codepen.io/dreamxcf/pen/WNKjJbZ

**Comment by JiuqingSong** [comment]
I tried with your test link but the tab key works fine to me. Can you please explain with more details about "Then tap on the ul element, which cannot be focused again." ? Better attach a video or GIF to help us understand. Thanks.
![1501](https://user-images.githubusercontent.com/23065085/213765956-64443d0d-383e-42a1-b0ff-5a93a2781eed.gif)

**Comment by Dream0827** [comment]
I attached a video to help understand. When I tap on the area of ul element, the cursor cannot be moved to the ul area. I think the expected behavior is that the cursor will be moved to the position where the mouse taps on.
![image](https://user-images.githubusercontent.com/118722930/215089475-bb1b484c-1225-45a8-aef4-3d98d306c742.png)

https://user-images.githubusercontent.com/118722930/215090856-0a3832a2-8d50-4076-b495-eb34e6677c8b.mp4

**Comment by JiuqingSong** [comment]
This seems by design to me. Tab order is controlled by browser, we don't have special handling to it. And using tab to change focus is not a common operation inside an editor since everything is editable. But if you want to override this behavior, you can always write a plugin to do it.
