### ISSUE TITLE
[Image Resize] It exits the image editing mode automatically on scrolling

### ISSUE THREAD

**Issue by milliezhang-qinlan** [microsoft/roosterjs#1503]
**Describe the bug**
During the process of resizing an image, if scrolling the editor, it will exit the image editing mode automatically and the resize handle disappears.

I find it is because it triggers `this.setEditingImage(null);` in `onPluginEvent` of `ImageEdit`
<img width="953" alt="Screenshot 2023-01-12 at 18 25 44" src="https://user-images.githubusercontent.com/63031370/212042538-fb937488-74f1-4145-bb7c-2efcac62863f.png">

For the previous versions of roosterjs, it will not exit the resize mode on scorlling. And when resizing an image on mobile, it would scroll a lot during the process of resizing an image. 

Correct me if I am wrong. I guess the reason to do so is to ensure the image displayed at a right position on scroll? 🤔 If so I am wondering if there is a way to update the image wrapper position instead of exiting the image editing mode on scrolling.

And there is also another issue, after exiting the resize mode on scrolling, the image has a red border:
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/63031370/212044502-ef8685d1-67ee-40ea-a025-7c9fdfdd9a33.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/63031370/212044799-1aea966c-a192-4ca6-922f-e5484f7c6ef8.png">

**To Reproduce**
1. Go to roosterjs sample site
2. Insert an image and click on it and resize
3. Do not exit resize mode and scroll the editor

**Expected behavior**
The image should be in resize mode with resize handle displayed and in a correct position after scroll.

**Screenshots**

**Device Information**
 - Browser: Chrome

**Comment by JiuqingSong** [comment]
Thanks for reporting.

@juliaroldi  is working on this issue.
