### ISSUE TITLE
Images selection does not disappear

### ISSUE THREAD

**Issue by Guillaumez** [microsoft/roosterjs#1507]
Hey Rooster folks ! Just met a bug on latest versions. Seem to be related to `ImageSelection` plugin.

**Describe the bug**
When `ImageEdit` plugin is disabled, images don't leave the selected state.

**To Reproduce**
Steps to reproduce:
1. Go to this sandbox https://codesandbox.io/s/rooster-img-issue-i5gfyg
2. Click on insert image
3. Click on image
4. Click outside image
5. Image stays focused
6. Type text
7. Image disappears

**Expected behavior**
Image should leave selected state on click outside.

**Screenshots**
![rooster-issue](https://user-images.githubusercontent.com/942451/212571016-2d6df6b3-c040-41ca-9eb3-81ffc7b74f31.gif)

**Device Information**
 - OS: Macos
 - Browser: Chrome/Safari/Firefox
 - Version: Latests

**Notes**
Image leave selected state when pressing arrow keys.

**Comment by JiuqingSong** [comment]
Thanks for reporting. We will investigate.

**Comment by JiuqingSong** [comment]
As a workaround, you can add TableCellSelection plugin which will avoid this issue:

![image](https://user-images.githubusercontent.com/23065085/212973860-0c6f9190-4722-4089-8010-1abbe815d53d.png)

And we will make a fix to make it work even without this plugin.
