### ISSUE TITLE
createLink() function replaces the existing content 

### ISSUE THREAD

**Issue by Dream0827** [microsoft/roosterjs#1512]
**Describe the bug**
In some cases, when inserting a link in a new line, it will replace some contenst after the new line with display text of the inserted link.

**To Reproduce**
1. Go to the test https://codepen.io/dreamxcf/pen/eYjGxWb
2. Click on `Insert Normal Anchor` button, "**A normal anchor 1**" is inserted
![image](https://user-images.githubusercontent.com/118722930/213141228-8e267ed3-bcd5-4a7b-b867-31a618bd85fa.png)

3. Then input a text at the end of the link, such as "test"
4. Click on `Insert Block Anchor` button, "**A block anchor 2**" is inserted
5. Put the cursor at the end of "test" and then tap on "Enter"
6. Click on `Insert Normal Anchor` button, the "**A block anchor 2**" is replaced as "**A normal anchor 3**"
![image](https://user-images.githubusercontent.com/118722930/213139784-bf91619a-083b-451b-992e-2f2770458553.png)

**Expected behavior**
The "**A normal anchor 3**" is inserted before the "**A block anchor 2**".

**Screenshots**
The actual result is 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/118722930/213140596-e4cedabd-941a-4a18-bf55-85be4d383f01.png">

The expected result is
<img width="524" alt="image" src="https://user-images.githubusercontent.com/118722930/213140425-6cf0e69f-c35c-4ebc-91e5-4be9d5e1f920.png">

**Device Information**
 - Browser: chrome

**Comment by JiuqingSong** [comment]
Thanks for reporting.

It seems the queryElements() function doesn't handle this case well. We need to find out a best solution to fix.

**Comment by JiuqingSong** [comment]
This is now solved by Content Model. We will publish new Content Model editor soon.
