### ISSUE TITLE
Feature request: Inline code formatting

### ISSUE THREAD

**Issue by stonebk** [microsoft/roosterjs#1536]
**Describe the feature**
Add support for new inline code formatting. In markdown this is usually accomplished with a single back tick surrounding the content, e.g. `` `inline code` ``

<img width="665" alt="Screen Shot 2023-01-27 at 9 14 44 AM" src="https://user-images.githubusercontent.com/1432010/215151409-47df697f-a929-49b7-aef5-b45e51abf353.png">

Inline code is sometimes also applied in the same place as headings as a "code" or "monospace" style:

<img width="431" alt="Screen Shot 2023-01-27 at 8 47 44 AM" src="https://user-images.githubusercontent.com/1432010/215145420-d1b7bf85-a9dc-4452-b691-580a220dab6b.png">

**Expected behavior**
This should behave similarly to other inline styles like bold, underline, and italic. The API could potentially look something like this:

roosterjs-editor-api
`toggleCode(editor: IEditor): void`

FormatState
`isCode: boolean`

Uses the inline [`<code>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) under the covers.

**Prior art**

* [CKEditor basic styles](https://ckeditor.com/docs/ckeditor5/latest/api/basic-styles.html) > [Code](https://ckeditor.com/docs/ckeditor5/latest/api/module_basic-styles_code-Code.html)
* [Draft.js toggle inline style](https://draftjs.org/docs/api-reference-rich-utils/#toggleinlinestyle), e.g. `toggleInlineStyle(editorState, 'CODE')`

**Comment by romanisa** [comment]
@ianeli1 can you please take this up for February?
