### ISSUE TITLE
Feature request: ContentEdit plugin: remove code block when enter or backspace empty line

### ISSUE THREAD

**Issue by stonebk** [microsoft/roosterjs#1550]
**Describe the feature**
Similar to [`unquoteWhenEnterOnEmptyLine`](https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.contenteditfeaturesettings.html#unquotewhenenteronemptyline) and [`unquoteWhenBackspaceOnEmptyFirstLine`](https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.contenteditfeaturesettings.html#unquotewhenbackspaceonemptyfirstline) for quote blocks, add [`ContentEditFeatureSettings`](https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.contenteditfeaturesettings.html) that will remove the code block when you enter or backspace on an empty line.

**Comment by romanisa** [comment]
@ianeli1 This and the other inline code formatting asks might be done together. Can you please take this up as well for February?
