### ISSUE TITLE
Unreliable cursor/focus behavior with readonly entities

### ISSUE THREAD

**Issue by richardtagger** [microsoft/roosterjs#1551]
**Describe the bug**
The cursor is not working as expected with inline read-only entities. Navigating through/past it often results in the cursor disappearing altogether making it impossible to tell where the focus is.

**To Reproduce**
1. Go to Rooster Demo Site
2. Add some text and insert an inline <a> entity after that is inline and read-only
3. Focus at the start of the editor and use arrow keys to navigate past to right after the entity
4. Press back arrow
5. Observe cursor not rendered / missing

**Expected behavior**
The cursor goes back to before the entity

**Screenshots**
![busted](https://user-images.githubusercontent.com/692240/216128034-0e570341-42e3-4b0d-bed9-aa38f9b2037f.gif)

**Device Information**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest

**Additional context**
Issues with focus/cursor seem particularly prevalent when the editor content ends with a readonly entity

**Comment by BryanValverdeU** [comment]
We added a fix for this, please enable this [Experimental Feature](https://github.com/microsoft/roosterjs/blob/806f2031d8d434dbed8f82f7e2a9c4b4aa410cbe/packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts#L154) in your editor, lets us know if you find any issues. Thanks.
