### ISSUE TITLE
Clearing undo stack

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#1562]
Hi folks,

I am wondering if there's a way to clear the undo stack entirely, i.e., resulting `canUndo` to return false and making corresponding keyboard shortcuts not working.

A very common issue for us is that not all user content is loaded from the very beginning, due to the mechanism of loading contents, some might be inserted after initializing the editor, and we always wanted to treat such a state as "clean", users should not be able to undo the content changes, because they are not made by users.

Do you have any recommendations for such a scenario? I think I might have missed something obvious.

Also, I noticed that even on roosterjs demo website, the undo button is initially enabled, by just clicking on the text area:

![image](https://user-images.githubusercontent.com/6745066/217136201-ad716def-b1a6-40d3-9b25-8245d2cadbf4.png)

Is this the expected behavior?

Thanks in advance!

**Comment by JiuqingSong** [comment]
This can be done by providing a customized undo snapshot service. So you can do any operation on this service object since that your own code. example https://codepen.io/jiuqingsong/pen/VwBNNea

**Comment by JiuqingSong** [comment]
You can add a call to editor.addUndoSnapshot() after clear undo. I updated the demo code.
