### ISSUE TITLE
It is not possible to type after a table

### ISSUE THREAD

**Issue by juliaroldi** [microsoft/roosterjs#1577]
**Describe the bug**
It is not possible to type after a table

**To Reproduce**
1.Insert a table
2.Click under table
3.Press back space 
4.Click under the table again
5. The focus goes inside the table

**Expected behavior**
The focus is under the table 

**Screenshots**
![tableBug1](https://user-images.githubusercontent.com/87443959/219101901-38875db5-9da4-4c54-a251-b4c542063c2a.gif)

**Device Information**
 - OS: MacOS
 - Browser: Chrome

**Comment by JiuqingSong** [comment]
Resolved by Content Model edit feature.
