### ISSUE TITLE
Pressing Enter inside of a Read Inline entity that is at the end of a list makes the new list item to be wrapped in a entity

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/roosterjs#1584]
**Describe the bug**
Pressing Enter inside of a Read Inline entity that is at the end of a list makes the new list item to be wrapped in a entity

**To Reproduce**
1. https://microsoft.github.io/roosterjs/index.html/#api/entity
2.  Restore Snapshot
```
<div><ol data-editing-info="{&quot;orderedStyleType&quot;:1,&quot;unorderedStyleType&quot;:1}"><li style="list-style-type: &quot;1. &quot;;"><span><br></span></li></ol></div><!--{"type":0,"isDarkMode":true,"start":[0],"end":[0]}-->
```
3. Add a new Entity of Type Inline and editable at the end of the List item
```
<a>Read</a>
```
4. Press Enter at the end of the Entity.
5. The new List item is also wrapped in a Span with Entity classes

**Expected behavior**
New Element in the new List item is wrapped in the same Entity as in the previous List item Entity

**Comment by JiuqingSong** [comment]
I'm considering stop support editable entity

**Comment by JiuqingSong** [comment]
We have removed editable entity support in 9.0
