### ISSUE TITLE
Feature Request: Addition of checkbox type task list

### ISSUE THREAD

**Issue by fctg-swatisacheti** [microsoft/roosterjs#1588]
**Describe the bug**
This is a feature request to get the ability to add checkbox type task list to work items. The editor should have an option to allow task list just like bulleted or numbered list

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**

**Additional context**

**Comment by JiuqingSong** [comment]
@fctg-swatisacheti I'm not sure if I understand your requirement. Can you add more details with what you exactly want?

Thanks.

**Comment by romanisa** [comment]
@fctg-swatisacheti we understand the feature ask, but this is not in our backlog currently. If you have the bandwidth, we encourage open-source contribution to add a new format API of this type of list.

**Comment by JiuqingSong** [comment]
We suggest to create your own format API to insert check box since this is not a very common scenario.
