### ISSUE TITLE
Add `dir` and `text-align` info in FormatState

### ISSUE THREAD

**Issue by Echo-az** [microsoft/roosterjs#1589]
**Describe the feature**
Add `dir` and `text-align` info in FormatState. They will be used to calculate the alignment (left | center | right) of text at cursor. This state will be displayed to the users through the icons of the button.
![image](https://user-images.githubusercontent.com/63284518/219995457-16d859a3-5b10-45a0-bbfc-81a7123ea4ff.png)
![image](https://user-images.githubusercontent.com/63284518/219995513-1d6ab09b-2438-4c55-acdf-e9cbb806640d.png)
![image](https://user-images.githubusercontent.com/63284518/219995538-fe1bfb7a-2c76-42cd-bf06-862fac9db6e3.png)

**Expected behavior**
Expose two properties in FormatState:
`textAlign`
`dir`: while it's undefined, return that of its parent

**Comment by JiuqingSong** [comment]
#1590
