### ISSUE TITLE
PickerPlugin don't remove query string for Chinese Input Method

### ISSUE THREAD

**Issue by huahuahu** [microsoft/roosterjs#1593]
**Describe the bug**
PickerPlugin don't remove query string for Chinese Input Method

**To Reproduce**
1. Checkout #1592 
2. Start the demo website by running `yarn start`
3. Open the website on iPhone
4. Switch keyboard to Chinese, type `yu` to trigger mention commit. The committed node is `<div>person<div>`

**Expected behavior**
The `<div>person<div>` is inserted and the `yu` query string is removed. 
But the actual result is the `yu` query string is still there.

**Screenshots**

https://user-images.githubusercontent.com/5757671/220815378-59eae4e5-a8ca-4386-8ffe-ad55feebf283.MP4

**Device Information**
 - OS: iOS
 - Browser Safari
 - Version 16.3.1

**Additional context**
I added log for [wordToReplace](https://github.com/microsoft/roosterjs/blob/91ebd24a244dea603f553205ad57e7a8fd6b2949/packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts#L96). The value is the query string `yu`. So I thought it maybe a browser issue?

**Comment by JiuqingSong** [comment]
Hi @huahuahu , do you want to submit a fix? Or I'll close this issue for now since we don't plan to fix it from our side. Thanks
