### ISSUE TITLE
Copy paste bullet list item doesn't work, copies just empty span instead of content inside.

### ISSUE THREAD

**Issue by p-rk** [microsoft/roosterjs#1713]
**Describe the bug**

Copy pasting the bullet list item text not pasting in another bullet point instead it is embedding an empty span in html whenever Ctrl + V or paste is clicked on browser contextual menu.

**To Reproduce**
1. Go to demo site
2. Copy paste any bullet list content with each item containing span element inside the li
3. Copy any item from the bullet list and try pasting under another bullet list item
4. It is just copying the empty span and when pasting it just pastes span instead of the content or text.

Tried copying and pasting the same bullet list and it just copies empty spans as shown in the screenshots.

**Expected behavior**
Ideally the content needs to be copied or cut and the same needs to be carried forward to pasting the content in the bullet list item.

**Screenshots**
<img width="761" alt="image" src="https://user-images.githubusercontent.com/30556391/230896532-535681e2-bc9f-4006-a1ef-1d8a3845159e.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/30556391/230896651-882af0c1-69ff-4d4d-8299-27192f37d03a.png">

**Device Information**
 - OS: Windows 11
 - Edge browser
 - Version 111.0.1661.62 (Official build) (64-bit)

https://user-images.githubusercontent.com/30556391/230898417-57bc136c-279d-48a8-92e0-ec96c8e41775.mp4

**Comment by BryanValverdeU** [comment]
Thanks for reporting this issue.

Could you please provide the HTML or a snapshot to repro this issue?
You can take a current editor snapshot here in the Take snapshot button.
![image](https://user-images.githubusercontent.com/8291124/231220558-359ff23c-0fb1-4c15-9df4-503ebc83aae1.png)

**Comment by shubhambajpai1994** [comment]
Hi, this issue is still occuring. I tested by pulling the latest release of roosterjs 8.45.2. Can you please look into it and fix this

**Comment by JiuqingSong** [comment]
It doesn't happen to me, either in demo site, or in this test: https://codepen.io/jiuqingsong/pen/rNqwwZW

![pastelist](https://user-images.githubusercontent.com/23065085/234936586-3449cc9b-9e37-471a-9481-1ccac24a4b98.gif)

Does it happen to you on the demo site? Can you build a repro demo with something like codepen so we can try. Without a repro we have nothing to fix.
