### ISSUE TITLE
Picker plugin opens when a word is split between multiple inline elements

### ISSUE THREAD

**Issue by Adjective-Object** [microsoft/roosterjs#173]
**Describe the bug**
Picker plugin will open when a word is split between multiple inline elements

**To Reproduce**
In a project that uses ':word' to search for emoji
Insert an auto-link
Type `:` immediately after the link
Picker plugin opens

**Expected behavior**
Picker plugin should not open

**Screenshots**
![image](https://user-images.githubusercontent.com/1174858/49601444-b41cb600-f93a-11e8-9128-ef5b9a9f260c.png)

**Device Information**
Repros on firefox, Safari

**Additional context**

**Comment by JiuqingSong** [comment]
Close old issues.
