### ISSUE TITLE
Removed cached elements from source model when using mergeModel function

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/roosterjs#1734]
When using domToModel on paste, we should not cache elements. Because when we cached elements, we skip some format appliers when doing modelToDom. 

Remove cached elements from source element to prevent inconsistent behavior.

**Comment by BryanValverdeU** [comment]
Ah I see, do you think it is okay to add this option to skip this cache logic for Table and Td?

**Comment by BryanValverdeU** [comment]
So, when we create a model from the paste fragment,
In case we want to override the default format parser and merge the model with the current editor model, we will not apply the new format [here](https://github.com/microsoft/roosterjs/blob/077d8da7929ab6fcafea55c505cb55359fd1bbb3/packages/roosterjs-content-model/lib/modelToDom/handlers/handleTable.ts#L79-83)

**Comment by JiuqingSong** [comment]
#1751
