### ISSUE TITLE
[discussion] Custom Serialization Format

### ISSUE THREAD

**Issue by rajsite** [microsoft/roosterjs#1747]
**Description**

Is there an API that can be used to customize the serialization format in and out of RoosterJS? I'd like to be able to persist a representation with a strict JSON Schema or to a flavor of Markdown.

Alternatively is there a strict representation of the HTML output by Rooster that can be referenced?

**Comment by JiuqingSong** [comment]
The default IEditor.getContent() API relies on browser's innerHTML attribute so there is no way to customize it.

An optional way is to build on top of Content Model. Existing handlers are https://github.com/microsoft/roosterjs/tree/master/packages/roosterjs-content-model/lib/modelToDom/handlers, they will just convert Content Model back to DOM tree. But with a given model you can create your own model handlers to customize the output. 

However, Content Model is still under development and not finalized yet. So it has risk that the model can be changed in the future so your code may also need to be changed.

**Comment by JiuqingSong** [comment]
Some of existing format API (from `roosterjs-editor-api` package) are still using `execCommand`, especially for toggle bold, italic, underline, superscript, subscript and strikethough. For others, we have get rid of `execCommand`.

For format API from Content Model (from `roosterjs-content-model` package), it does not rely on `execCommand` at all. So the code should generate consistent HTML in spite of browser.
