### ISSUE TITLE
toggleHeader naming inaccuracy

### ISSUE THREAD

**Issue by stonebk** [microsoft/roosterjs#1752]
I know this would be a breaking change, but I noticed `toggleHeader` uses the term "header" which is a bit inaccurate -- the correct term is "heading".

From ChatGPT:

> Header and heading are two terms that are commonly used in the context of document formatting and website design.
>
> A header is a section of a document or webpage that appears at the top of each page or screen. It often contains important information such as the title of the document, the author's name, the date, and page numbers. In website design, the header may also include navigation links, a logo, and other design elements.
>
> A heading, on the other hand, refers to the title or subtitle of a section within a document or webpage. Headings are used to organize content and make it easier for readers to navigate through the text. They are typically formatted in a larger or bolder font than the surrounding text to make them stand out.
>
> In summary, a header is a section at the top of a document or webpage that contains important information, while a heading is a title or subtitle within the document or webpage that helps organize the content.

H1-H6 are referred to as "heading" elements:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

Might be something you think about updating if you ever plan to make other breaking changes.

**Comment by romanisa** [comment]
@ianeli1 We can rename the API to have the new name and then create another API with older name and that will call the new API as well, so that we don't break backward compatibitlity. Can you please take that up? Thanks
