### ISSUE TITLE
Cursor placement with insertEntity

### ISSUE THREAD

**Issue by stonebk** [microsoft/roosterjs#1769]
Currently the cursor does not move when using the `insertEntity` API. My expectation was that the cursor would move just after where the entity was inserted. I asked @JiuqingSong  about this, and this was his response:

> Today it will not put cursor after block entity. The cursor management is a bit messy here actually. I think it is ok to add parameter to change this behavior. And I'm also thinking about having a "v2" implementation of insertEntity to change those unclear behavior

Adding this issue to track.

**Comment by JiuqingSong** [comment]
Created a draft PR to add a parameter

![1769](https://github.com/microsoft/roosterjs/assets/23065085/21ad8c71-ec80-4506-9e6b-46c434224d7e)
