### ISSUE TITLE
Sanitizer trimming new lines inside pre

### ISSUE THREAD

**Issue by adriantran** [Microsoft/roosterjs#177]
**Describe the bug**
Sanitizer is trimming new lines inside pre tag.

**To Reproduce**
1. Start the editor with this content:

```
foooooo barrr foooooo bbbar foobar #11111111111<div><br></div><div><pre><span style="color:#1e1e1e;">:020> kn 100</span>
<span style="color:#1e1e1e;"> # 00000000          0000000           Call Site</span>
<u><span style="color:#0066cc;">00</span></u><span style="color:#1e1e1e;"> 00000000`00000000 00000000`00000000 00000000000000000000000000000000 [</span><u><span style="color:#0066cc;">000000000000000000000000000000000000000000000000000000000000000000000</span></u><span style="color:#1e1e1e;"> 0 0000 </span>
```

2. copy that content to clipboard
3. paste into a clean editor

**Expected behavior**
Content inside pre tag is under one line, not multi like it was originally.

**Screenshots**

**Device Information**
At least Chrome

**Additional context**

**Comment by JiuqingSong** [comment]
Fixed in roosterjs-html-sanitizer@1.1.2, will be included in roosterjs@6.18.1
