### ISSUE TITLE
Copy paste distorted list issue with bullet

### ISSUE THREAD

**Issue by adriantran** [Microsoft/roosterjs#182]
Copy the following including the first empty line (i.e. this line w/o this sentence), then paste into the editor:

* abc
* 123
* def

**Comment by adriantran** [comment]
This looks like a Chrome bug actually (removed the noisy style attributes):

<html>
<body>
<li ><br class="Apple-interchange-newline">abc</li><li >123</li><li >def</li>
</body>
</html>

When copied from other browsers, the list is well formed.

**Comment by adriantran** [comment]
still repros for me

**Comment by JiuqingSong** [comment]
Hmm, still not able to repro.
Anyway, can you try with this branch jisong/fix193 see if the pasting works for you? @adriantran 

Thanks
