### ISSUE TITLE
Redo not works when type in table.

### ISSUE THREAD

**Issue by lwyj123** [microsoft/roosterjs#1828]
**Describe the bug**
https://microsoft.github.io/roosterjs/index.html

use redo in roosterjs table not work and will clear history.

**To Reproduce**
1. Go to 'https://microsoft.github.io/roosterjs/index.html'
2. Insert a table
3. type in table
4. use ctrl+z or click undo
5. use ctrl+shift+z or click redo.
6. the redo didn't get back to previous state and the history get cleared and can redo again.

**Expected behavior**
Redo should works

**Screenshots**

**Device Information**
 - OS: Windows 11
 - Browser: Edge
 - Version: 113.0.1774.50 (Official build) (64-bit) 

**Additional context**

**Comment by lwyj123** [comment]
Sorry, It seems like the shortcut not works. ctrl+shift+z. the button in the editor works.

**Comment by JiuqingSong** [comment]
The shortcut for Redo is Ctrl+Y

**Comment by lwyj123** [comment]
Hi @JiuqingSong, thanks for the reply. Ctrl + Shift + Z is also a common shortcut for redo. Also I think there is a weird behavior that when I use Ctrl + Shift + Z my history get clear.
