### ISSUE TITLE
[Question] How can I set cursor position

### ISSUE THREAD

**Issue by bokuweb** [Microsoft/roosterjs#187]
Is there a way to set cursor position now?
I can find `getFocusedPosition()` and `getCursorRect()`, but I can not find setXXXX ( i.e. setFocusPosition, setCursorRect())
If not, I would like to create PR.
What do you think about it?

**Comment by JiuqingSong** [comment]
You can use editor.select(). It accepts several combinations, such as
editor.select(node, offset)
editor.select(nodePosition)
editor.select(nodePosition, nodePosition) // this will select a range
editor.select(range)
...

**Comment by bokuweb** [comment]
Thanks I missed it...

**Comment by Samigirma1** [comment]
It would still be great if we could have a straightforward way that abstracts! 😁

**Comment by JiuqingSong** [comment]
@Samigirma1  what kind of straightforward way you'd like to see? Can you give an example?

Thanks.
