### ISSUE TITLE
Screen reader is not reading state as 'On/Pressed' for toggle buttons when they are selected

### ISSUE THREAD

**Issue by Nick-Castle-m** [microsoft/roosterjs#1890]
**PWD Impact:**

Users with 'Visual Disabilities' who rely on screen readers will be impacted if state for toggle buttons is not read after selecting them and users will not be able to get the appropriate information about the control, the user might be misguided while navigating using keyboard.

Test Environment:

OS: Windows 11 21H2 (OS Version 22000.613)

Browsers: New Edge Version 113.0.1774.35 (Official build) (64-bit)

URL: https://microsoft.github.io/roosterjs/index.html

Screen Readers: Narrator and NVDA (Version 2022.2)

**Repro Steps:**

Step 1. Open the above URL in Edge browser.  

Step 2. Navigate to ‘Rooster Js Example’ and move focus to any toggle button (example – Bold, Italic, Underline, etc) using ‘Tab’ key.

Step 3. Run Narrator and select any button using ‘Enter’ key and verify whether the screen reader is reading state as 'On/Pressed' for toggle buttons after invoking them or not.

**Actual result:**

After invoking the ‘Bold, Italic, Underline’ or any other toggle button, screen reader is not reading the state as 'On/Pressed' for the selected button even if the on pressed label has been applied. This is because the focus moves directly to the input after the button has been pressed.  

**Observation:** Screen reader is not reading state as selected, pressed or On after invoking any toggle button, instead keyboard focus is moving to text field.

**Expected result:**

Screen reader should read the selected state as 'On, pressed or selected' for the selected 'Bold, Italic, Underline' or any other toggle button on the page.

**Example:** After invoking any toggle button, screen reader should read the state as, ‘Bold toggle button ON’, ‘Italic toggle button ON’ and ‘Underline toggle button ON’ etc.

PFA: <MAS 4.1.2_Narrator is not reading any message after invoking any toggle button>

PFA: <MAS 4.1.2_Code Snippet_SR not reading any message after invoking any toggle button>

**NVDA Behaviour:** Issue is also observed while navigating using screen reader NVDA.

PFA: <MAS 4.1.2_NVDA is not reading any message after invoking any toggle button>

**MAS Reference Link:** 

https://microsoft.sharepoint.com/:w:/s/accessibility/EZBde1C58eFKkdEvHy1sfB0BbfrE-sgqsVO5g2zVY6wbDA?e=jEWXd4

**WCAG Reference:** 

https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

**Comment by JiuqingSong** [comment]
Thanks for reporting the issue. Would you like to submit a fix so that it can benefit everyone who uses roosterjs?

Thanks.

**Comment by Nick-Castle-m** [comment]
Hello @JiuqingSong, 
Whoever makes the fix would your team be willing to backport the fix to our version of RoosterJS? This is a bug the Coherence team has to fix as its risk to our accessibility grade.

**Comment by JiuqingSong** [comment]
Once fix is merged it will be included in next release.

What do you mean by "our version of roosterjs"?

**Comment by Nick-Castle-m** [comment]
I thought we were using an older version of Rooster in our monorepo. It looks like it's using the current version.

**Comment by JiuqingSong** [comment]
Hi @Nick-Castle-m , do you want to submit a fix? Or I'll close this issue for now.

Thanks.
