### ISSUE TITLE
Style lost when transformColor is triggered under dark mode

### ISSUE THREAD

**Issue by milliezhang-qinlan** [microsoft/roosterjs#1901]
**Describe the bug**
Style lost when transformColor is triggered under dark mode

**To Reproduce**
1. Open the roosterjs demo site
2. Click 'Dark Mode' button to turn on dark mode
3. Inspect and insert the following element in the editor: 
`<table><tr><td><span style='color: #0000FF'>Test signature!</span> <span style='color: #00FF00'>Message with this signature is always </span><span style='color: #FF0000'>saved as draft.</span></td></tr></table>
`
![image](https://github.com/microsoft/roosterjs/assets/63031370/5837ab25-1227-459e-a46a-324a15632578)

5. Click on 'Export' button, which will trigger the editor.getContent. Check the editor html content.
6. Or instead of clicking on 'Export' button, you can reproduce the issue by toggle back to light mode. The styles will be lost after back to light mode.

**Expected behavior**
The exported editor html content should retain the styles set on the elements

**Screenshots**
The styles are lost after getContent under dark mode
![image](https://github.com/microsoft/roosterjs/assets/63031370/8093665b-6eba-46cf-afd0-779f67b5a485)
![image](https://github.com/microsoft/roosterjs/assets/63031370/24ac98dc-8a8a-45c8-9a59-e5db03d5eb01)

getContent under light mode works fine:
![image](https://github.com/microsoft/roosterjs/assets/63031370/bfb78a2f-06e4-40fd-9c30-2565b2d4a089)

**Device Information**
 - Chrome

**Additional Context**
I think the problem lies in the transformColor implementations.
Right now the color style is removed no matter the lightModeColor is valid or not.
<img width="785" alt="Screenshot 2023-06-20 at 11 55 52" src="https://github.com/microsoft/roosterjs/assets/63031370/76119a0c-af74-4a8f-9d92-5c6b7634c853">

**Comment by romanisa** [comment]
Closing as per above comment by Jiuqing.
