### ISSUE TITLE
insertNode does not work properly with HyperLink

### ISSUE THREAD

**Issue by Foolment** [microsoft/roosterjs#1903]
**Describe the bug**
The insert position is not right when calling `Editor.insertNode()` with a `Range` relative to a Node and that Node's final child is a hyperlink.

**To Reproduce**
Attached a [reproduce-demo.zip](https://github.com/microsoft/roosterjs/files/11796464/reproduce-demo.zip) contains `editor.html` and `source.js` for you to reproduce.

DOM: 
![image](https://github.com/microsoft/roosterjs/assets/3321518/11532174-8766-42d2-92c7-1a4ab117517e)
What I'm trying to do is to append a `DIV#reference-message` after the `DIV#signature`
```javascript
const range = document.createRange();
range.setStartAfter(signatureDiv);
range.setEndAfter(signatureDiv);

editor.insertNode(refDiv, {
  position: roosterjs.ContentPosition.Range,
  range,
});
```
After calling `insertNode`, the `DIV#reference-message` will be inserted inside the `DIV#signature`, which is unexpectedly.
![image](https://github.com/microsoft/roosterjs/assets/3321518/54551eeb-fcef-4b7c-ac88-76d870d502e3)

In comparison, these scenarios are work expectedly.
|no hyper link|last child is text|use range.insertNode()|
|:--:|:--:|:--:|
|![image](https://github.com/microsoft/roosterjs/assets/3321518/9475c671-bb0a-40ed-8c54-f34638b42349)|![image](https://github.com/microsoft/roosterjs/assets/3321518/5940f1ec-caec-4803-a80d-d6fab685a50f)|![image](https://github.com/microsoft/roosterjs/assets/3321518/ec71f942-aa4a-4aef-aa32-6dc517e0e62a)|

**Expected behavior**
The insert position should be expected in this case, the `DIV#reference-message` should be inserted after `DIV#signature`

**Device Information**
 - OS: Android (didn't verify on the iOS side)
 - Browser: Edge, Chrome

**Additional context**
1. Maybe it's related to [adjustInsertPositionForHyperLink()](https://github.com/microsoft/roosterjs/blob/d1b1982fced794b47f716990c99bab6fc58d5e72/packages/roosterjs-editor-dom/lib/edit/adjustInsertPosition.ts#L50).
2. Related to a bug in Outlook Android: [#8013739](https://office.visualstudio.com/Outlook%20Mobile/_workitems/edit/8013739/)

**Comment by JiuqingSong** [comment]
This should have been fixed when Content Model editor and new insertLink API on top of Content Model

**Comment by Foolment** [comment]
The version of roosterjs we are using:
```
"roosterjs-content-model": "0.5.0"
"roosterjs-editor-*": "8.46.0"
``` 

Which version of content model contains the fix you mentioned?

**Comment by JiuqingSong** [comment]
We realized this issue before and the API queryElements (used by adjustInsertPositionForHyperLink) cannot handle this case well. We are developing the new Content Model editor and with the new Content Model API [mergeModel](https://github.com/microsoft/roosterjs/blob/master/packages-content-model/roosterjs-content-model-editor/lib/modelApi/common/mergeModel.ts) can handle it better. Without Content Model editor, I think you can workaround it by creating an empty DIV and insert it after the signature DIV by using Node.insertBefore() directly, then use insertNode() to insert your content into this empty DIV.

**Comment by JiuqingSong** [comment]
Here is an example https://codepen.io/jiuqingsong/pen/yLQMBgg
