### ISSUE TITLE
Different indentation behavior in content model editor

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#1917]
Hi folks,

I recently noticed that while working with the Microsoft Editor SDK, the [setIndentation](https://microsoft.github.io/roosterjs/docs/modules/roosterjs_editor_api.html#setindentation) api would make squiggles misplaced.

While this is something worth reporting to Editor SDK team (assuming how the content is structured should not affect the SDK), I noticed some differences between Outlook Web (content model is enabled) and https://microsoft.github.io/roosterjs/ (content model is not enabled by default).

It seems in the old editor, `setIndentation` wraps the content into a `blockquote` to make it indented, while content model increase `margin-left` to make it indented. Is there any reason for such a difference?

Also, since we haven't migrated to content model, I also wonder if there's any way to work it around.

Thanks!

**Comment by JiuqingSong** [comment]
I think it is on purpose not show squiggles for quote, because content wrapped by BLOCKQUOTE means it is quoting content from other people, so even if there is spelling issue, it is not current author's fault. 

Using BLOCKQUOTE for indent incorrectly inherits this behavior, so causes this incorrect result. Using margin can solve it well.

**Comment by JiuqingSong** [comment]
The reason why we use BLOCKQUOTE for indent before, is just because the browser's build int command execCommand('indent') is working like this. Now that we are building Content Model and we have got rid of execCommand(), we now can change this implementation by using margin instead.

**Comment by JiuqingSong** [comment]
Another option is to create your own format API for indent.
