### ISSUE TITLE
Failed to get element's computed style in onExternalContentTransform

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#1927]
**Describe the bug**
Recently we encounter a dark mode color transformation issue in Outlook Mobile after integrating roosterjs 8.50.1. When user pastes some text with different colors into the editor in dark mode, all the colors will be transformed to white. 

According to our investigation, the root cause is Outlook's custom `onExternalContentTransform` implementation gets the element's original color by `window.getComputedStyle(element).color`, which requires that the element is already inserted into the html body. In previous roosterjs version, `coreApi.transformColor()` invokes `callback` first, then calls `onExternalContentTransform`, which means the element is inserted into the body before doing color transformation:

<img width="711" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/1731b4a8-4450-404d-aa45-40af638161a3">

However, this commit(https://github.com/microsoft/roosterjs/pull/1878) changed the execution order of `callback` and `onExternalContentTransform`. The `onExternalContentTransform` is invoked earlier and the element hasn't been inserted yet, so the color transformation logic in `onExternalContentTransform` can't work now. 

To fix this regression, is it possible to revert the execution order of `callback` and `onExternalContentTransform`?

**Comment by JiuqingSong** [comment]
In up coming version (8.51.0) we will change the function parameter of onExternalContentTransform() to allow transform color using roosterjs's build in color transformation function, so no need to call getComputedStyle() any more.

Please refer to https://github.com/microsoft/roosterjs/pull/1907

**Comment by Rain-Zheng** [comment]
I also noticed that commit. However, current implementation of `onExternalContentTransform()` has a check for color's contrast before transforming. If the contrast between text color and background color is valid, the transformation will be skipped. Does roosterjs's build in color transformation function support this logic? If not, we may still need to call `getComputedStyle()` in `onExternalContentTransform()`.

**Comment by JiuqingSong** [comment]
First, roosterjs does NOT provide an official implementation of onExternalContentTransform, it is your own work to implement it. 

Second, with the latest change, there is an additional parameter of onExternalContentTransform that allow you use the build in support of dark color (DarkColorHandler), you can use it to do color transformation which does not compare contrast at all. 

If you are referring the OWA implementation of onExternalContentTransform, it is not part of roosterjs, and we don't force you to use that code as well, and in OWA we don't use it for compose either. For compose, you can totally ignore the OWA implementation of onExternalContentTransform.

**Comment by JiuqingSong** [comment]
Here is an example to show how to user DarkColorHandler to do color transformation from onExternalContentTransform. It will only transform color from SPAN element, and leave other colors not changed. You can click "Dark Mode" button  to see how the colors are changed.

https://codepen.io/jiuqingsong/pen/gOQRdeR

**Comment by Rain-Zheng** [comment]
Thanks for your instruction and example. Currently we are directly using OWA's implementation as compose dark color solution, we will try to implement a new custom function to replace it. Do you know when will the roosterjs 8.51.0 version be ready?

**Comment by JiuqingSong** [comment]
8.51.0 was already released one week ago https://www.npmjs.com/package/roosterjs/v/8.51.0

**Comment by JiuqingSong** [comment]
Close this one since it has been mitigated in 8.51.0
