### ISSUE TITLE
iOS/macOS app's TableFeatureSettings.upDownInTable is false by default

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#1937]
**Describe the bug**
TableFeatureSettings.upDownInTable only enable for Browser.isChrome or Browser.isSafari
https://github.com/microsoft/roosterjs/blob/55b2135615844d8348e75f3fed95e395ad9d45b5/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/tableFeatures.ts#L175

but the up down arrow behavior in iOS/macOS app is also wrong, should it be disable by !Browser.isWebKit?

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

**Device Information**
 - OS: iOS/macOS
 - Browser: WKWebView

**Comment by miku1958** [comment]
Hi @JiuqingSong, do you know why defaultDisabled is using (!Browser.isChrome && !Browser.isSafari) here?

**Comment by JiuqingSong** [comment]
@miku1958 I think the only reason is Firefox can work well even without this feature. But it should be fine to also enable it to firefox.

**Comment by miku1958** [comment]
@JiuqingSong Ok, let me submit a change to remove this line

**Comment by miku1958** [comment]
Fixes #1941
