### ISSUE TITLE
Ctrl + K shortcut support for inserting the link

### ISSUE THREAD

**Issue by p-rk** [microsoft/roosterjs#1942]
Currently, the ctrl + k shortcut seems to be not implemented for inserting the link into the editor. If we select some text and use the shortcut ctrl + k it should open an insert link popup. 

**To Reproduce**
1. Add some text to the editor
2. Select the word where you want to embed the link
3. Press shortcut ctrl + k
4. It is by default going to the browser's search bar.

**Expected behavior**
It should open the create link popup with the shortcut ctrl + k.

**Device Information**
 - Edge, Chrome

**Additional context**
This is supported in Outlook, office applications, and ADO also. It would be great if we can add this shortcut support.

**Comment by JiuqingSong** [comment]
The insert link dialog is part of roosterjs-react. So The hotkey needs to be implemented there as well.

@p-rk do you want to submit a fix?

**Comment by p-rk** [comment]
@JiuqingSong - Sure can give it a try, but I need some reference in implementing this. I saw earlier PRs related to shortcuts for reference and could see shortcuts were implemented as part of the ContentEdit plugin. So, need some reference if it is implemented in any of the other components in roosterjs-react library.

**Comment by JiuqingSong** [comment]
The easiest fix should be just handle KeyDown event in RibbonPlugin, and check if the key is Ctrl+K, then invoke the same command of insert link button

**Comment by sathishsridhar** [comment]
@p-rk / @JiuqingSong Hey anyone working on this ? if not, I might give it a try.

**Comment by JiuqingSong** [comment]
@sathishsridhar  please feel free to start on it. Thanks.

**Comment by Apoorvakothari** [comment]
@JiuqingSong Is this issue still open? If so, I would like to make my first open source contribution to this repository through this issue.

**Comment by romanisa** [comment]
@Apoorvakothari Sure feel free to submit a PR and add Jiuqing as reviewer

**Comment by Ghanem10** [comment]
Hey, if no one is working on this I have a PR ready for review @JiuqingSong

**Comment by Ghanem10** [comment]
Hey, @JiuqingSong could you please take a look at the PR when you can, thank you!

**Comment by JiuqingSong** [comment]
Solved by #2333
