### ISSUE TITLE
[Regression] Image aspect ratio is not respected when window is small

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#1976]
**To Reproduce**

- Copy and paste an image into the editor
- Resize it (we can set `preserveRatio: true` to make the difference easier to be noticed)
- Dismiss the image edit handles by clicking on other places
- Resize the browser window

**Expected behavior**

The image aspect ratio is respected when resizing the window, when the width is too small, it should make the content horizontally scrollable, check video:

https://github.com/microsoft/roosterjs/assets/6745066/5011e45e-27c6-464c-b11a-8433e1460920

**Actual behavior**

The image height is kept, resulting in a thinner image, check video:

https://github.com/microsoft/roosterjs/assets/6745066/f6403a3e-36f1-48de-8076-89c874145204

**Additional context**

This issue can be also reproduced in Outlook Web, both reading and writing scenarios. It is a regression of [remove new max-width #1527](https://github.com/microsoft/roosterjs/pull/1527), the video captured for expected behavior can demonstrate that.

**Comment by juliaroldi** [comment]
Hey @cyanzhong, thanks for the feedback. Here is a fix for the issue https://github.com/microsoft/roosterjs/pull/1978
