### ISSUE TITLE
How to add a handler for the editor's ContentChangedEvent

### ISSUE THREAD

**Issue by T-Roth** [Microsoft/roosterjs#199]
How can I add a handler for ContentChangedEvent to update my model when the Editor's contents change?

**Comment by JiuqingSong** [comment]
you need to write a plugin. Here is an example: https://github.com/Microsoft/roosterjs/wiki/Hello-plugin

**Comment by T-Roth** [comment]
So in my plugin that is going to update my model, I would have to filter on the event types and then get contents like this: 
```
    onPluginEvent(event: rooster.PluginEvent) {
        if (event.eventType == rooster.PluginEventType.ContentChanged || event.eventType == rooster.PluginEventType.KeyUp) {
            this.value(this.editor.getContent());
        }
    }
```

**Comment by JiuqingSong** [comment]
That's right.
