### ISSUE TITLE
Is there a way to setup the dialog classnames for "insert dialog" button?  

### ISSUE THREAD

**Issue by Shtoosha** [microsoft/roosterjs#2003]
Is there a way to setup the classNames for Dialog in InsertLink prop dialog?  I do not see ant props, exposed on RibbonButton for that.

https://github.com/microsoft/roosterjs/blob/master/packages-ui/roosterjs-react/lib/ribbon/component/buttons/insertLink.ts
![image](https://github.com/microsoft/roosterjs/assets/53274526/6c0da513-0fa9-4d1a-b68f-f6d6175d6afc)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**

**Additional context**

**Comment by JiuqingSong** [comment]
There is not too much customization options for roosterjs-react since it is mostly used for demo or prototype.

If you need to customize it, we encourage you to create your own insertLink API and dialog implementation
