### ISSUE TITLE
Delete the first List item mark will also delete the newline character.

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2026]
**To Reproduce**
1. type something like:

<img width="160" alt="image" src="https://github.com/microsoft/roosterjs/assets/24806909/73a348cc-4960-4945-9858-f1eb8709be6c">

2. change item to a list

<img width="121" alt="image" src="https://github.com/microsoft/roosterjs/assets/24806909/c6e3908d-b7ef-47f7-b1ba-2841e7e2ca7e">

3. move the cursor to the mark and delete it

<img width="130" alt="image" src="https://github.com/microsoft/roosterjs/assets/24806909/783a02eb-6794-48d2-b570-c673d3b674a9">

4. the newline also be deleted

<img width="156" alt="image" src="https://github.com/microsoft/roosterjs/assets/24806909/1d670bfb-1648-4e08-abaf-cf316014f385">

**Expected behavior**
Only the mark is deleted
<img width="129" alt="image" src="https://github.com/microsoft/roosterjs/assets/24806909/cdbd2750-2158-4804-a7a9-cb447e906fdd">

**Device Information**
 - OS: macOS
 - Browser WKWebview
 - Version 8.52.0

**Additional context**
If I revert first after step 2, and make it back to a list, then the delete action will delete the mark only.

**Comment by JiuqingSong** [comment]
There is a content edit feature to handle this, although it is not enabled by default:

![image](https://github.com/microsoft/roosterjs/assets/23065085/0eebd3de-6750-4475-9394-326e29c63bfe)

And here is the related code

![image](https://github.com/microsoft/roosterjs/assets/23065085/873c8070-78e5-43d9-bde2-c6bc59c5a886)
