### ISSUE TITLE
If we implement Rooster editor in popup or dialog and try to add link by insert link ribbon button then link popup is flickering 

### ISSUE THREAD

**Issue by Sudarshan191191** [microsoft/roosterjs#2032]
If we implement Rooster editor in popup or dialog box and try to add link by "insert link ribbon button" then link popup is flickering.

**To Reproduce**
1. Make sure Rooster editor in dialog box or any popup
2. Click on "link insert" from rooster editor ribbon button
3. try to type in link dialog box web url
4. See it will not able to insert text or flicker issue will be there

**Expected behavior**
Flickering or text input should be allowed in above repro step

**Screenshots**
<img width="298" alt="image" src="https://github.com/microsoft/roosterjs/assets/142475134/82767322-3ffc-40e1-aeb2-8f2a37f43c6b">

**Device Information**
 - OS: [Windows]
 - Browser [MS Edge]
 - Version [115.0.1901.203]

**Comment by JiuqingSong** [comment]
Can you provide more details of the issue? Does it happen on roosterjs demo site? I tried but everything works fine to me. If possible please attach a video of the repro. Thanks.

**Comment by Sudarshan191191** [comment]
If rooster editor in "dialog box or popup" then try to click on link button so, there is one more popup to add link info. In that top popup cursor is flickering.

**Comment by JiuqingSong** [comment]
I'm still not able to repro it. Does it happen on the demo site? If it does, can you take a video of the end to end repro? (from opening the page, to it finally happen). If not, can you build a local repro (e.g. using codepen or similar site) so that I can check?

**Comment by Sudarshan191191** [comment]
Hi,
I have created small demo app but some styling not there for ribbon button.
[LocalProject Working.zip](https://github.com/microsoft/roosterjs/files/12646155/LocalProject.Working.zip)

follow below step to run app (ignore some css are not done properly in demo app):
1. export project and copy path and open in VS code to run application
2. open terminal do npm i
3. then npm start
4. it will open below web page:
<img width="880" alt="image" src="https://github.com/microsoft/roosterjs/assets/142475134/b6b9965a-94f6-4472-8edd-04723e7a35b9">

Try to do same highlight thinks then it will open one more popup for link dialog:
<img width="739" alt="image" src="https://github.com/microsoft/roosterjs/assets/142475134/1371b316-5296-46ba-8d3a-ebf25748e843">
try to type some text ex; www.ms.com and observe some of the text is not captured

**Comment by JiuqingSong** [comment]
This seems like a problem from FluentUI.

For roosterjs-react, it is mostly used for demo purpose. If it doesn't work well to you, we recommend to build your own UI and do not use roosterjs-react.

Thanks.
