### ISSUE TITLE
view Source code or html code option or ribbon button is not available in rooster editor

### ISSUE THREAD

**Issue by Sudarshan191191** [microsoft/roosterjs#2034]
view Source code or html code option or ribbon button is not available in rooster editor

**To Reproduce**
1. Go to Rooster Editor and check source code or html conversation option or button is available or not

**Expected behavior**
view Source code or html code option or ribbon button is should be available in rooster editor

**Device Information**
OS: [Windows]
Browser [MS Edge]
Version [115.0.1901.203]

**Comment by JiuqingSong** [comment]
Roosterjs focus on rich textedit, viewing html source is actually a separate functionality which roosterjs won't cover. You can build this feature in your own code.
