### ISSUE TITLE
setFontSize doesn't work when using soft keyboard

### ISSUE THREAD

**Issue by Foolment** [microsoft/roosterjs#2061]
**Describe the bug**
After calling `RoosterApi.setFontSize()` without selecting any text, typing something but the font size didn't get changed.
It only happens when using the soft keyboard to input.

**To Reproduce**
1. Open [RoosterJs Demo Site](https://microsoft.github.io/roosterjs/index.html) in browser app (Edge, Chrome) with an Android phone.
2. Tab on the increase font size button several times.
3. Input something by soft keyboard.
4. Check the font size whether it's correct.

**Expected behavior**
The font size should get changed

**Screenshots**
Screen recording:
https://github.com/microsoft/roosterjs/assets/3321518/64f4b94b-38aa-4348-b60d-11451d27e6de
The first `hello` I inputed by physical keyboard, DOM result:
![image](https://github.com/microsoft/roosterjs/assets/3321518/f9667612-6a3b-45b4-a7b6-35f919cac702)

The second `hello` I inputed by soft keyboard, DOM result:
![image](https://github.com/microsoft/roosterjs/assets/3321518/473cd511-480b-481e-a8da-c6bd459d878a)

**Device Information**
 - OS: Android
 - Browser: Edge, Chrome

**Comment by JiuqingSong** [comment]
Thanks for reporting.

Can you help me check from https://microsoft.github.io/roosterjs/index.html#event, when use soft keyboard on Android, what events are fired? I tried on Windows but everything works well, so not sure for Android.

**Comment by Foolment** [comment]
|Physical keyboard|Soft keyboard|
|:--:|:--:|
|![physical-keyboard](https://github.com/microsoft/roosterjs/assets/3321518/47416965-953f-4e94-8d7b-b429cdb04069)|![soft-keyboard](https://github.com/microsoft/roosterjs/assets/3321518/813bb136-20ca-4b1c-ad41-3670ad60cff8)|

Looks like there is one more `KeyPress` event of each typing when using physical keyboard.

**Comment by JiuqingSong** [comment]
Can you debug if it can hit the code below (packages\roosterjs-editor-core\lib\corePlugins\PendingFormatStatePlugin.ts) in  and if it working correctly when press a key?

<img width="508" alt="image" src="https://github.com/microsoft/roosterjs/assets/23065085/32b29912-47ff-4eb5-ba8e-b9c11a019951">

Also, can you try content model editor (https://microsoft.github.io/roosterjs/index.html?cm=1) see if the same scenario is working well in Android.

**Comment by Foolment** [comment]
Thanks for sharing the related code, which allow us to see clearly about this issue now.
I put some log to into code, and when I input a character by physical keyboard, everything is ok since we can receive the character correctly by `event.rawEvent.key`:
![image](https://github.com/microsoft/roosterjs/assets/3321518/e3113f88-374e-4952-bafc-303c7b504837)
But when I input the same character by soft keyboard on the Android platform, we receive `Unidentified` and stop us from inserting the node with style later.
![image](https://github.com/microsoft/roosterjs/assets/3321518/05a39cfe-8ce0-4c86-9200-2beb80ab16a1)

For the unidentified key issue, I raised a related issue before: [Space key doesn't trigger the auto link feature in Android WebView](https://github.com/microsoft/roosterjs/issues/513)

**Comment by JiuqingSong** [comment]
Thanks. Can you try if the Content Model editor works? https://microsoft.github.io/roosterjs/index.html?cm=1 It is using Input event instead.

![image](https://github.com/microsoft/roosterjs/assets/23065085/5f4242d3-c009-4a82-88ec-206b07b6ec48)

**Comment by Foolment** [comment]
It's weirder when testing in content model editor. The increase font size button didn't work either.
Two screenshots attached,
[content-model-increase-font-size.mp4](https://github.com/microsoft/roosterjs/assets/3321518/7dfff600-c5b3-45bf-b83e-e7d9eda9c466)
[content-model-set-font-size.mp4](https://github.com/microsoft/roosterjs/assets/3321518/6bf6b331-618b-43c4-9861-7d2b60d1615d)

Working on debug the code when using Content Model, will circle back later
