### ISSUE TITLE
Cursor is lost after inserting entity

### ISSUE THREAD

**Issue by kangning-c** [microsoft/roosterjs#2063]
**Describe the bug**

I created a Ribbon button to insert entities. After an entity is inserted, the cursor is lost, and I have to explicitly click behind the inserted entity to be able to type again.

**To Reproduce**

I believe this particular issue was recently fixed but for some reasons it doesn't work for me even with packages upgraded. This is not reproducible on RoosterJs demo site. 

**Expected behavior**

Editor won't lose focus after inserting entity.

**Screenshots**

Screen recording shows that cursor is lost after inserting entity, and typing again requires explicit clicking behind entity.

https://github.com/microsoft/roosterjs/assets/110475875/24c63659-8588-49bc-a3c8-ee69310948c9

**Device Information**

Chrome, Firefox

**Additional context**

Maybe my implementation is correct? Code is below. Also wanted to note that this editor lives in a modal. I read about [the editor not acting as expected in popups](https://github.com/microsoft/roosterjs/issues/2032). I had similar challenges and not sure if being in a modal contributes to this lost cursor issue.

```
type DynamicTokenStringKey = 'buttonNameInsertVariable';
const ENTITY_TYPE = 'DYNAMICTOKEN_WRAPPER';

export function createDynamicTokenButton(className?: string): RibbonButton<DynamicTokenStringKey> {
  const dynamicToken: RibbonButton<DynamicTokenStringKey> = {
    key: 'buttonNameInsertVariable',
    unlocalizedText: 'Insert Variable',
    iconName: 'Add',
    dropDownMenu: {
      items: {
        item1: 'item 1',
        item2: 'item 2',
        item3: 'item 3',
      },
    },
    onClick: (editor, key) => {
      const newEntity = insertEntity(
        editor,
        ENTITY_TYPE,
        editor.getDocument().createTextNode(key),
        false /*isBlock*/,
        true /*isReadonly*/,
        undefined,
        undefined,
        true /*focusAfterEntity*/
      );

      if (className) {
        newEntity.wrapper.classList.add(className);
      }

      editor.focus();
    },
  };

  return dynamicToken;
}
```

I also noticed how my HTML looks different from that of the demo site with entities inserted

Mine:

<img width="1007" alt="Screenshot 2023-09-11 at 3 44 47 PM" src="https://github.com/microsoft/roosterjs/assets/110475875/720278fd-df90-4a23-90ba-60836b6fe434">

Demo site:

<img width="701" alt="Screenshot 2023-09-11 at 3 46 34 PM" src="https://github.com/microsoft/roosterjs/assets/110475875/e7511b88-8fbc-4296-97e7-6f2809f5eb8a">

**Comment by JiuqingSong** [comment]
Please try add experimental feature `InlineEntityReadOnlyDelimiters`. Here is how demo site adds it:

![image](https://github.com/microsoft/roosterjs/assets/23065085/d64395dd-d9e9-498c-a2ee-0d1fa873fe0e)

**Comment by kangning-c** [comment]
`InlineEntityReadOnlyDelimiters` didn't fix the cursor issue for me, although it did insert the `entityDelimiter span` around entities and brought the html closer to that of the demo site. I also moved the editor out of the modal but got the same lost cursor behavior. Anything else I could try?

**Comment by JiuqingSong** [comment]
Can you build a simple repro so that we can try to debug on it?

**Comment by kangning-c** [comment]
Hi again, I wasn't able to reproduce the same loss of cursor behavior in codesandbox (https://codesandbox.io/p/sandbox/stoic-snow-txstmh?file=%2Fsrc%2Findex.tsx%3A45%2C22). But as I was examining our editor again, I think the culprit might be the fact that the ribbon button is stealing focus after inserting entity - as shown in the screen recording above, once an entity is inserted, the custom ribbon button {{var}} receives focus again (as indicated by the outline around {{var}} button). We do have the same implementation in our codebase as in codesandbox. Do you happen to know what could have caused it? Thank you! @JiuqingSong

**Comment by JiuqingSong** [comment]
You can manually call editor.focus() to set focus back to editor.
