### ISSUE TITLE
replaceNode in PickerPlugin does not trigger ContentChanged event

### ISSUE THREAD

**Issue by liangdrime** [microsoft/roosterjs#2080]
**Describe the bug**
In PickerPlugin, `replaceNode` function does not trigger `ContentChanged` event. For example:

Input a mention like `@Ying Zhong` then press backspace key to delete the last name, to modify the mention to `@Ying`. I think it should be in the scope of content change but `ContentChanged` event was not triggered.

However, while inputing a mention (`@Ying Zhong`) by invoking `insertNodeCallback`, it will post the `ContentChanged` event since `this.editor.addUndoSnapshot` was called in which the core api [triggered](https://github.com/microsoft/roosterjs/blob/a76905c9e0fbdd93ffd75390b50edc24e78db3ca/packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts#L74C9-L74C64) this event.

**Expected behavior**
[replaceNode](https://github.com/microsoft/roosterjs/blob/a76905c9e0fbdd93ffd75390b50edc24e78db3ca/packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts#L264) can trigger `ContentChanged` event as well if `currentNode` is not equal to `replacementNode`.

**Comment by JiuqingSong** [comment]
Yes, as a lower level API, replaceNode (as well as insertNode, removeNode, ...) they won't trigger ContentChangedEvent. This is because we allow doing a bunch of action together, for example, we need to insert/remove/replace more than one nodes, but we should not trigger the event for each of them. So your code is suppose to trigger the event together:

```ts
  editor.addUndoSnapshot(() => {
     editor.insertNode(...);
     editor.removeNode(...);
     editor.replaceNode(...);
  });
```

This will trigger ContentChangedEvent altogether once all the actions are done, and undo snapshot will be added.

**Comment by haven2world** [comment]
BTW, how could we know which api will trigger content change event, and which won't? Do we have a doc for it?

**Comment by liangdrime** [comment]
> This will trigger ContentChangedEvent altogether once all the actions are done, and undo snapshot will be added.

Does it mean for [tryRemoveNode](https://github.com/microsoft/roosterjs/blob/a76905c9e0fbdd93ffd75390b50edc24e78db3ca/packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts#L507) function in PickerPlugin it's better to call `addUndoSnapshot` while replacing the node via `replaceNode`?

And have another stupid question, will it lead an unexpected result if remove and insert a same node while calling `addUndoSnapshot`?

**Comment by JiuqingSong** [comment]
I see. I misunderstood. Now I agree that is indeed a problem. I need to take a closer look and we should add undo snapshot and trigger ContentChanged event there.

**Comment by JiuqingSong** [comment]
@liangdrime  @haven2world  I have a PR here #2173  Would you please verify it? Thanks.

**Comment by liangdrime** [comment]
@JiuqingSong thanks for your quick fix. I'll be verifying it soon, and back to here after that.

**Comment by liangdrime** [comment]
Verified the PR [#2173](https://github.com/microsoft/roosterjs/pull/2173), I believe it fixed this issue. Cc @JiuqingSong @haven2world

**Comment by JiuqingSong** [comment]
> Verified the PR [#2173](https://github.com/microsoft/roosterjs/pull/2173), I believe it fixed this issue. Cc @JiuqingSong @haven2world

Thanks for verify!

PR is merged, so close this one.
