### ISSUE TITLE
Cannot display the Spaces with New Lines

### ISSUE THREAD

**Issue by Li-Wanjing** [microsoft/roosterjs#2096]
**Describe the bug**
By typing two lines of text, placing my cursor before the first character of the first word of the second line, and typing a lot of spaces. No matter how many spaces were typed, the text did not move. 

**To Reproduce**
1. Open RoosterJS demo in Safari/Chrome mobile iOS 
2. Typing a lot of words that the length could automatically fill with two lines.
3. Move the cursor to the first position of the second line.
4. Typing a lot of spaces

**Expected behavior**
The spaces that I typed should be displayed in editor

**Screenshots**
Attached repro video:

https://github.com/microsoft/roosterjs/assets/11981186/7bdaa9e2-9576-4501-8dd7-22111bf6ef52

**Device Information**
 - OS: iOS 17.0 and MacOS 13.5.2,
 - Browser: Safari/Chrome
 - Version iOS 17.0 and MacOS 13.5.2,

**Comment by JiuqingSong** [comment]
It is actually a rendering issue. When input more spaces, there will be a scroll bar at the bottom because the spaces can't be broken. I made a fix to allow breaking spaces. In your project you need to do the same.

**Comment by Li-Wanjing** [comment]
It looks like within this CSS attribute, the structure` <div> </div>` `<div><br></div>` looked higher than before in Editor

For some reason, we may add some DOM structures in Editor (see the red block):

![image](https://github.com/microsoft/roosterjs/assets/11981186/e190a9ba-e8a6-4544-b0f6-a50af07052c5)
but after adding the `white-space: break-spaces` to editor, the red block is much higher than blue.

same issue happened in this structure:

![image](https://github.com/microsoft/roosterjs/assets/11981186/b076777e-0bf5-4de5-bd3b-046d5767f377)

**Comment by JiuqingSong** [comment]
In that case, I believe it is a rendering issue of Safari. I tried on Chrome it doesn't has this problem. But in Safari as long as the content is under "contenteditable=true", the spaces can't be rendered correctly, even it is just a pure HTML page without any javascript at all. You can try this url https://codepen.io/jiuqingsong/pen/MWZQbxw compare the rendering result between Safari and Chrome. Note that it is just a pure HTML page.

Suggest open bug to Safari.
