### ISSUE TITLE
How to properly style editor using ThemeProvider?

### ISSUE THREAD

**Issue by kangning-c** [microsoft/roosterjs#2108]
Hi, this is more of a question. I have a working editor but have been having trouble styling it using `ThemeProvider`. I tried mimicking what's done in the demo code and wrapped my `Ribbon` and `Rooster` components with `ThemeProvider` but didn't see any style changes.

Here's an abbreviated version of my code. My understanding is that `Ribbon` and `Rooster` are built with Fluent UI and wrapping them with `ThemeProvider` should just work. Are there any additional setup that I missed? Thank you.

```
import { PartialTheme, ThemeProvider } from '@fluentui/react/lib/Theme';

...

  const lightTheme: PartialTheme = {
    palette: {
      themePrimary: '#0099aa',
      themeLighterAlt: '#f2fbfc',
      themeLighter: '#cbeef2',
      themeLight: '#a1dfe6',
      themeTertiary: '#52c0cd',
      themeSecondary: '#16a5b5',
      themeDarkAlt: '#008a9a',
      themeDark: '#007582',
      themeDarker: '#005660',
      neutralLighterAlt: '#faf9f8',
      neutralLighter: '#f3f2f1',
      neutralLight: '#edebe9',
      neutralQuaternaryAlt: '#e1dfdd',
      neutralQuaternary: '#d0d0d0',
      neutralTertiaryAlt: '#c8c6c4',
      neutralTertiary: '#a19f9d',
      neutralSecondary: '#605e5c',
      neutralPrimaryAlt: '#3b3a39',
      neutralPrimary: '#323130',
      neutralDark: '#201f1e',
      black: '#000000',
      white: '#ffffff',
    },
  };

...

  return (
    <ThemeProvider theme={lightTheme}>
      <div className={s.editorWrapper}>
        <Ribbon
          plugin={ribbon}
          buttons={toolbarOptionButtons}
          className={s.ribbon}
        />
        <Rooster
          plugins={plugins}
          className={s.rooster}
          initialContent={initialContent}
          inDarkMode={darkMode}
          getDarkColor={getDarkColor}
          editorCreator={editorCreator}
        />
      </div>
    </ThemeProvider>
  );

```

**Comment by JiuqingSong** [comment]
Hi, can you build a repro on codepen and clarify what is not working as expected?

Thanks.

**Comment by kangning-c** [comment]
Styles declared through `ThemeProvider` aren't being reflected in editor.

Has anyone been able to build a sandbox using `rooster-react ` with success recently? I tried but it's throwing error - [sandbox linked here](https://codesandbox.io/p/sandbox/busy-hypatia-pc23pz?file=%2Fsrc%2FEmailEditor.js%3A2%2C1-2%2C43).

Commenting out `import { Rooster } from "roosterjs-react";` would make the app render again (I do have `roosterjs-react` installed as can be seen in the dependency list).

**Comment by JiuqingSong** [comment]
Not sure for sandbox. But code pen works fine to me: https://codepen.io/jiuqingsong/pen/JjweQwz
