### ISSUE TITLE
Rooster removed style tag in the initial content

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2112]
**Describe the bug**
The initial content has a style tag, but after initializing the editor, the style tag is removed.

**To Reproduce**
1. change the initialContent in demo code to be:
```
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="ProgId" content="Word.Document" />
    <meta name="Generator" content="Microsoft Word 15" />
    <meta name="Originator" content="Microsoft Word 15" />
    <style>
      <!--
      @font-face
      	{font-family:"Cambria Math"}
      @font-face
      	{font-family:Calibri}
      @font-face
      	{font-family:Aptos}
      p.MsoNormal, li.MsoNormal, div.MsoNormal
      	{margin:0cm;
      	font-size:11.0pt;
      	font-family:"Aptos",sans-serif}
      a:link, span.MsoHyperlink
      	{color:#467886;
      	text-decoration:underline}
      a:visited, span.MsoHyperlinkFollowed
      	{color:#96607D;
      	text-decoration:underline}
      span.EmailStyle17
      	{font-family:"Calibri",sans-serif;
      	color:windowtext}
      .MsoChpDefault
      	{font-size:11.0pt;
      	font-family:"Aptos",sans-serif}
      @page WordSection1
      	{margin:72.0pt 72.0pt 72.0pt 72.0pt}
      div.WordSection1
      	{}
      -->
    </style>
  </head>
  <body
    lang="EN-IN"
    link="#467886"
    vlink="#96607D"
    style="word-wrap: break-word"
  >
    <div class="WordSection1">
      <p class="MsoNormal">
        <span style="font-family: 'Calibri', sans-serif">Line1</span>
      </p>
      <p class="MsoNormal">
        <span style="font-family: 'Calibri', sans-serif">Line2</span>
      </p>
      <p class="MsoNormal">
        <span style="font-family: 'Calibri', sans-serif">Line3</span>
      </p>
      <p class="MsoNormal">
        <span style="font-family: 'Calibri', sans-serif">Line4</span>
      </p>
    </div>
  </body>
</html>
```
2. run the demo

**Expected behavior**
The text style shouldn't change

**Screenshots**
![image](https://github.com/microsoft/roosterjs/assets/17299418/ffadd292-4981-4a38-81b2-11752a34a058)
![image](https://github.com/microsoft/roosterjs/assets/17299418/6ad86d3f-e9b9-4650-85ba-b6d723b2fbec)

**Device Information**
 - OS: MacOS
 - Browser Chrome
 - Version 8.55.0

**Additional context**
This message is created on outlook windows

**Comment by haven2world** [comment]
It can be reproduced on both legacy version and content model

**Comment by JiuqingSong** [comment]
This is intentional and on purpose.

Global STYLE tag will cause style bleeding to other part of the page, so we must convert it into inline style.

RoosterJs doesn't guarantee HTML content is not changed during editing.

**Comment by haven2world** [comment]
So how does OWA handle email from Outlook win? convert global style to inline style for each message?

**Comment by JiuqingSong** [comment]
yes.

https://github.com/microsoft/roosterjs/blob/9dfda12f104285ffa14c53404bc3eaf9f0e13b9b/packages/roosterjs-editor-dom/lib/htmlSanitizer/HtmlSanitizer.ts#L139
________________________________

**Comment by haven2world** [comment]
thanks!
