### ISSUE TITLE
Type on image selection, type result is wrong

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#2113]
1. Insert image
2. Select the image
3. Type "ab"

Expected result: 
Image is gone, and content is "ab"

Actual result:
Image is still there, with content "ba"

**Comment by romanisa** [comment]
@juliaroldi this only repro's in Rooster and not in OWA. I am less worried about image being there, but more worried about the cursor positioning after first character. Can you please take a look? Thanks!

**Comment by juliaroldi** [comment]
Hey @romanisa and @JiuqingSong, 

The behavior of rooster is the same of Word Online. 
![typeOnImage](https://github.com/microsoft/roosterjs/assets/87443959/ac7dab16-644d-4981-b18b-15322df3a1f2)

That is the behavior on Win32 
![typeOnImageWind32](https://github.com/microsoft/roosterjs/assets/87443959/e8c230a9-e57e-4d83-af08-f98aa56875f0)

Should we make a fix to work like win32. I'll have to debug on OWA to check why key press is deleting the image.
