### ISSUE TITLE
No plugin event while editing the image

### ISSUE THREAD

**Issue by jiten-ally** [microsoft/roosterjs#2124]
Bug
Is there any Pluginevent fired that is fired when an image uploaded in Rooster is resized without clicking outside the image? Right now the event is fired only is I click outside of the image

**To Reproduce**
1. Tried to resize/cropped/rotate the image
2. No plugin event is fired to capture this change unless the user clicks outside the image

**Expected behavior**
Plugin event should be fired when the user does any changes in editing the image.

**Comment by JiuqingSong** [comment]
@juliaroldi , I'm thinking about adding a parameter to ImageEdit plugin to allow trigger event every time user finish an edit operation even not click away, and apply the edit result to the final image, although it is not shown at this point.

What do you think?

**Comment by JiuqingSong** [comment]
Fixed in #2133
