### ISSUE TITLE
Delete when editor contains a single bullet and Ctrl + A + DELETE is not deleting the bullet

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/roosterjs#2174]
1. Create a new bullet
2. Ctrl + A to select everything
3. Press delete

No content is deleted

snapshot
`<div><ul data-editing-info="{&quot;orderedStyleType&quot;:1,&quot;unorderedStyleType&quot;:1}"><li style="list-style-type: disc;"><span><br></span></li></ul></div><!--{"type":0,"isDarkMode":true,"start":[0,0,0,0,0],"end":[0,0,0,0,0]}-->`

**Comment by JiuqingSong** [comment]
Assign to @juliaroldi since she is working on this one.

**Comment by JiuqingSong** [comment]
This is now fixed.
