### ISSUE TITLE
Impossible to remove empty line in between two block entities

### ISSUE THREAD

**Issue by stonebk** [microsoft/roosterjs#2183]
If you create two block entities in a row, it creates an empty line in between the two entities which cannot be removed.

![blockentityemptyline](https://github.com/microsoft/roosterjs/assets/1432010/a62ec482-f0a4-4ba2-95c5-f9b00b6b61d1)

In an editor like Word, you can usually still put your cursor in front of or behind the block which would allow you to manipulate the content around the block without needing an empty line.

Here is an undo snapshot that reproduces this behavior:

```
<div><br></div><div class="_Entity _EType_divider _EId_divider_2 _EReadonly_1" contenteditable="false"><span><hr></span></div><div><br></div><div class="_Entity _EType_divider _EId_divider_3 _EReadonly_1" contenteditable="false"><span><hr></span></div><div><br></div><!--{"type":0,"isDarkMode":false,"start":[2,0],"end":[2,0]}-->
```

**Comment by stonebk** [comment]
Here's a workaround that @BryanValverdeU suggested:

> If you use a entity of type inline-block and then set width: 100% could provide the functionality you are looking for?
>
> I have this snapshot on how it would work:
 
```
<div><span class="entityDelimiterBefore"></span><span class="_Entity _EType_divider _EId_divider_2 _EReadonly_1" contenteditable="false" style="display: inline-block;width: 100%;"><span><hr></span></span><span class="entityDelimiterAfter"></span></div>
```

**Comment by BryanValverdeU** [comment]
We have added the functionality in the latest RoosterJS Content Model bump when insertEntity is set to be as block.
