### ISSUE TITLE
Can't control the theme colors of the ribbon buttons using a theme provider

### ISSUE THREAD

**Issue by nickzoum** [microsoft/roosterjs#2193]
**Describe the bug**
I'm trying to use `ThemeProvider` to define the colors of the ribbon buttons.
I've added a theme provider and placed the ribbon and the editor inside:
```tsx
<ThemeProvider theme={theme} applyTo="element">
  <Ribbon plugin={ribbonPlugin} buttons={buttons} />
  <Rooster plugins={plugins} initialContent={value} inDarkMode={inDarkMode} />
</ThemeProvider>
```
I can't seem to be able to alter the colors of the ribbon and the editor only seems to change theme based on the `inDarkMode` property.

**To Reproduce**
1. Created a react app with CRA 5 
```bat
npx create-react-app test --template typescript
```
2. Installed the following packages:
```json
"@fluentui/react": "8.112.6",
"roosterjs": "^8.54.0",
"roosterjs-editor-types": "^8.54.0",
"roosterjs-react": "^8.51.0",
```
3. Edited the package `@fluentui/react-portal-compat-context` in `package-lock.json` to `9.0.6` as instructed [here](https://github.com/microsoft/fluentui/issues/29107#issuecomment-1721310081)
4. Created the following component
```tsx
import { useMemo } from "react";
import { IEditor, getDarkColor } from "roosterjs";
import {
  createRibbonPlugin,
  getButtons,
  Ribbon,
  RibbonButton,
  Rooster,
  AllButtonKeys,
} from "roosterjs-react";
import { initializeIcons } from "@fluentui/react/lib/Icons";
import { ThemeProvider, DefaultPalette } from "@fluentui/react";

const darkPalette = Object.entries(DefaultPalette).reduce(
  (result, [name, color]) => ({ ...result, [name]: getDarkColor(color) }),
  { ...DefaultPalette }
);

initializeIcons();

export function RoosterEditor({ value }: {value?: string) {
  const themeMode = "dark"; // using a custom provider with a different name + hook in the actual code
  const ribbonPlugin = useMemo(createRibbonPlugin, []);
  const plugins = useMemo(() => [ribbonPlugin], [ribbonPlugin]);
  const buttons = useMemo(() => getButtons(AllButtonKeys), []) as RibbonButton<string>[];

  const inDarkMode = themeMode === "dark";
  const themePalette = inDarkMode ? darkPalette : DefaultPalette;
  const theme = { palette: themePalette };

  return (
    <ThemeProvider theme={theme} applyTo="body">
      <Ribbon plugin={ribbonPlugin} buttons={buttons} />
      <Rooster plugins={plugins} initialContent={value} inDarkMode={inDarkMode} />
    </ThemeProvider>
  );
}

```
5. Updated index.tsx:
```tsx
import React from "react";
import ReactDOM from "react-dom/client";
import { RoosterEditor } from "./RoosterEditor";

const root = ReactDOM.createRoot(document.getElementById("root") as HTMLElement);
root.render(<React.StrictMode><RoosterEditor /></React.StrictMode>);
```

**Expected behavior**
On the example on `https://microsoft.github.io/roosterjs/` I can see that the classnames of the ribbon buttons change after the theme changes, I was expecting the same would happen with my code.

**Sample Repo**
Created a test repo with the steps mentioned above:
[https://github.com/nickzoum/react-rooster-test/](https://github.com/nickzoum/react-rooster-test/)
[Netlify](https://effulgent-llama-b686e9.netlify.app/)

**Comment by JiuqingSong** [comment]
Since it works in demo site, it should not be a roosterjs issue. Can you please debug and see what are the difference?

**Comment by nickzoum** [comment]
> Since it works in demo site, it should not be a roosterjs issue. Can you please debug and see what are the difference?

Hello @JiuqingSong,
This is a blank project created with CRA.
I used the example at [https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controls/MainPane.tsx](https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controls/MainPane.tsx) to generate the little bit of code the project actually contains.
Am I missing a step?

**Comment by JiuqingSong** [comment]
I'm sorry we mainly focus on roosterjs editor itself. For roosterjs-react and the demo site, it is mainly used for demo and testing. And for FluentUI question, especially for fluentUI theme, suggest to post it on FluentUI github site. We are also not very familiar with FluentUI but just use it for better demo.
