### ISSUE TITLE
Error when using ImageResize plugin

### ISSUE THREAD

**Issue by AlphaGeek** [Microsoft/roosterjs#220]
I figure I am doing some incorrect here, just don't know what as there are very few examples on the site.  I am trying to add in the ImageResize plugin to my editor as follows:

```javascript
<script>
import { ImageResize } from 'roosterjs-plugin-image-resize';

...

mounted() {
    var roosterjs = require('roosterjs')
    var editorDiv = document.getElementById('editorDiv')
    let options = {
        plugins: [new ImageResize()]
    }
    let editor = roosterjs.createEditor(editorDiv, options)

    ...
}
```
    
however get this error in the console:

vue.runtime.esm.js?2b0e:1832 TypeError: plugin.initialize is not a function
    at eval (Editor.js?6844:26)
    at Array.forEach (<anonymous>)
    at new Editor (Editor.js?6844:26)
    at Object.createEditor (createEditor.js?4b83:27)

I am doing this from a VueJS app in the mounted() event for a component, but that should not matter much as I was able to get the adding of an image into the editor to work by creating a file input dynamically and firing the click() event (as the demo does).  

Also, is there an unminified version of demo.js?  If you are going to provide an example, using an unminified file would be best.

Thanks for any help.

**Comment by JiuqingSong** [comment]
Suggest adding break point at the line:

let editor = roosterjs.createEditor(editorDiv, options)

and see what is actually in options, is it a real "ImageResize" object?

**Comment by AlphaGeek** [comment]
Working now, rather than passing an array of plugins using the options var, I just pass the ImageResize pluging directly as the second arg, however now I am wondering how I would pass multiple plugins?

This works:

    var roosterjs = require('roosterjs')
    var editorDiv = document.getElementById('editorDiv')
    let editor = roosterjs.createEditor(editorDiv, new ImageResize())

**Comment by JiuqingSong** [comment]
According to [https://microsoft.github.io/roosterjs/docs/modules/roosterjs.html#createeditor](https://microsoft.github.io/roosterjs/docs/modules/roosterjs.html#createeditor), the second parameter of createEditor function is an array of plugin, but not an "options" object. So your original code should be replaced with:

 let editor = roosterjs.createEditor(editorDiv, [new ImageResize()])
