### ISSUE TITLE
Markdown conversion without spaces

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#2217]
Hey folks,

We recently got positive feedback regarding the built-in markdown conversion, thanks! For example, converts `~deleted~` to ~deleted~ as you type.

However, we also noticed that the conversion only works when the syntax is surrounded by spaces, for example, `[~deleted~]` would not do the convert.

While this is a minor issue, I would like to get clarification if this is by design.

Thank you!

**Comment by JiuqingSong** [comment]
@jvillalobos to help answer the question.

Thanks.
