### ISSUE TITLE
Shift-enter to avoid creating bullets

### ISSUE THREAD

**Issue by cyanzhong** [microsoft/roosterjs#2220]
Hey,

I have a question about the auto bullet feature. For example, when I hit enter at the end of a bullet item, it is expected to create a new bullet. However, if the shift key is held, it will insert a newline instead of creating a newline with bullet.

<img width="150" alt="image" src="https://github.com/microsoft/roosterjs/assets/6745066/56f6f02f-a5b1-421b-b3eb-61bb399c031d">

This is the expected behavior, but I noticed this doesn't work in Safari, it always creates a newline with bullet for me.

Is this something built in roosterjs, or something inside the browser implementation which we don't have control?

I've tried but wasn't able to find which piece of the code in roosterjs controls it. Would you mind sharing some insights?

Thanks!

**Comment by JiuqingSong** [comment]
It is browser's behavior. It doesn't need any js code, you can try this:
```html
<html>
<body>
<div contenteditable>
<ol>
<li>test</li>
</ol>
</div>
</body>
</html>
```

Currently we don't handle the enter key but just rely on browser's implementation.

However, I'm changing this behavior in our new Content Model editor. Here is a draft PR https://github.com/microsoft/roosterjs/pull/2215 It is not done yet.
