### ISSUE TITLE
Pasting inline text generates new HTML node

### ISSUE THREAD

**Issue by william57m** [microsoft/roosterjs#2246]
**Describe the bug**
In the context of Viva Engage, we have an at mention feature, when we type "@" character followed by a name, it opens a suggestions list. We are using a plugin that listen for "@" and catch the text attached to @.

Typing text naturally generates a single HTML node
<img width="170" alt="type" src="https://github.com/microsoft/roosterjs/assets/3273681/1ffa620a-6a6b-479a-938f-713f47073e7b">

However, pasting text, generates a new HTML node.
<img width="191" alt="paste" src="https://github.com/microsoft/roosterjs/assets/3273681/70745fa5-6a5b-4311-bd9a-cd6690e0b7eb">

That cause our feature to break since we cannot catch the actual text that comes after the "@" character.

**To Reproduce**
Try in the playground https://microsoft.github.io/roosterjs/index.html#event

Type "@brian" and inspect the element, you will see one node.
Type "@" and paste "brian" and inspect the element, visually it looks the same, but you will see 2 nodes ("@" and "brian")

**Expected behavior**
When inline text is paste, keep it in the same node.

Thanks in advance for any help.

**Comment by JiuqingSong** [comment]
Can you help me understand what is the impact to have two nodes?

**Comment by JiuqingSong** [comment]
It is not guaranteed to have a single text node in any places. You can use the following ways to see the text before:
1. editor.getPositionContentSearch(). It will return a helper class that can give you text before the cursor
2. Use Content Model to get the text mode before current selection marker.

**Comment by haven2world** [comment]
I'm wondering if `node.normalize()` helps here? Could we execute `node.normalize()` at some moments like after `paste`, `setContent`, or before generate `content model`?

**Comment by william57m** [comment]
@JiuqingSong I understand it's not guaranteed depending of what you paste, but I feel like a simple string with no formatting should not generate a new node. I tried in different editor, contenteditable, draftjs, ckeditor, quill... and they all behave the same way. RoosterJS seems to be the exception here, it doesn't seems correct to me but I may be wrong.

I'm not sure if our @mention feature should handle that differently, it could for sure, to be more robust and handle those splitted node, but is it the right thing? I'm a bit shared, because a real node split may mean that we should not handle @mention? I'm not sure honestly, I probably need more input to process that.

**Comment by JiuqingSong** [comment]
@haven2world is right. If you really want to merge those nodes, you can call node.normalize(). Here node can be either a parent node of the text nodes or the root level DIV element.

**Comment by william57m** [comment]
@JiuqingSong is it something we can call from our side at any point? We have a PastePlugin to handle some Copy Paste from different text format.
Or @haven2world was maybe referring to call that from your side?

**Comment by JiuqingSong** [comment]
Fixed in v9
