### ISSUE TITLE
Wrong numbering in numbered list when starting an item on iOS

### ISSUE THREAD

**Issue by rickygao** [microsoft/roosterjs#2250]
## Summary

Wrong numbering in numbered list when starting an item on iOS

## Repro Steps

1. Select numbered list command.
2. Type something.
3. Enter a linefeed.
4. Repeat.
5. Observe wrong numbering when starting an item.

## Screenshots

![image](https://github.com/microsoft/roosterjs/assets/26463169/c837cb71-6a92-46a9-9cec-a0fe29cd71c8)

![20231208_064638348_iOS](https://github.com/microsoft/roosterjs/assets/26463169/5b452d59-72c9-4a2e-8a71-646200d64736)

## Device Information

 - iOS
 - Safari
 - roosterjs: ^8.51.0, also the latest on demo site

**Comment by JiuqingSong** [comment]
Does this issue happen in content model editor? (https://microsoft.github.io/roosterjs/index.html?cm=1)

**Comment by rickygao** [comment]
> Does this issue happen in content model editor? (https://microsoft.github.io/roosterjs/index.html?cm=1)

No, not reproducible in content model editor.

**Comment by JiuqingSong** [comment]
Ok. In that case, we will treat it as fixed by content model since we will soon deprecate the old editor and replace it with Content Model editor.

**Comment by JiuqingSong** [comment]
Fixed with Content Model.
