### ISSUE TITLE
How about supporting opening brace "(" + "triggerCharacter" in picker plugin?

### ISSUE THREAD

**Issue by liangdrime** [microsoft/roosterjs#2260]
**Background**
In general, we're using picker plugin for @ mention scenario, and set up "@" as the `triggerCharacter`. 

By design, `onIsSuggestingChanged` is only called while typing "@" after a space. For example:
- `rooster editor@` does not trigger suggesting-change.
- `rooster editor @` does.

**Expected behavior**
In a scenario, users would like to enable @ mention when inputing `(@`, like `new editor (@rooster)`. Many editors have supported this, like Word, Github comment.

Can roosterjs support this ability as well? Or is there a workaround to achieve it?

**Comment by JiuqingSong** [comment]
It makes sense to allow trigger picker after something that is not a letter.

Do you want to contribute a fix?

**Comment by liangdrime** [comment]
I'm happy to do it, but I'm afraid I'm not able to look into it recently due to the bandwidth😅. I'll do more investigation or do a fix when I'm available.

**Comment by gm-al** [comment]
Hey, @JiuqingSong if this is abandoned and no one is working on it, I can take a look at it as well

**Comment by romanisa** [comment]
@gm-al You are more than welcome to contribute to this!

**Comment by gm-al** [comment]
This conditional statement currently checks if the trigger character is preceded by a whitespace character, we can check to include cases where the trigger character is preceded by a non-letter character e.g. `(`.

https://github.com/microsoft/roosterjs/blob/eff8f0028148b2a080fbf807189a427fb3f391cc/packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts#L346-L350

Will submit a PR shortly, thanks for the update @romanisa.
