### ISSUE TITLE
The insertion caret jumps back to last position

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2261]
**Describe the bug**
Input a lot of words, then move the caret and delete characters, the caret randomly jump back to the last position when pressing backspace. 

**To Reproduce**
Refer to the video

**Expected behavior**
editor should always delete the character before the caret.

**Screenshots**

https://github.com/microsoft/roosterjs/assets/17299418/163bc92b-7799-4ac9-bd8f-c6ea375e6738
In this recording, the editor works correctly, until the last seconds, wherever I moved the caret and pressed delete, the editor always removing the character on the second line.

**Device Information**
 - OS: iOS
 - Browser  safari

**Additional context**
cacheModel: off

here is the content model after I delete the wrong character
![image](https://github.com/microsoft/roosterjs/assets/17299418/5faa629b-00f3-4f2a-a45e-b2947e65361c)

**Comment by haven2world** [comment]
And in this screenshot, I moved the caret to the line before the signature, but when I output the content model, the selection marker is still in the second paragraph
![image](https://github.com/microsoft/roosterjs/assets/17299418/cdbaa261-38c6-4fd6-821d-e9336e418cde)

**Comment by haven2world** [comment]
I can consistently repro this issue, if you cannot repro it, could you give me some suggestion like where to debug? I'm not sure how we update the selection marker in content model.

**Comment by JiuqingSong** [comment]
can you try disable the content model cache see if it still happen?

**Comment by haven2world** [comment]
Do you mean the option `cacheModel`? It's already turned off.

**Comment by haven2world** [comment]
I found, we have cached the selection and content model, and then, sometimes, I move the caret, selection change is triggered but before we update cached model, we compare the cached selection with the current one. For some reason, the cached selection was changed before comparison, so they're the same and the update is skipped.
I haven't found which code change the cached selection since we have so many places updating it, and itself is a reference, it can be event updated by browser for some reason.
That's what I found. 
Any idea?

**Comment by haven2world** [comment]
Based on my investigation, it's most possible to be changed by browser

**Comment by haven2world** [comment]
maybe we need clone the range

**Comment by haven2world** [comment]
```
  coreApiOverride.getSelectionRangeEx = (core: EditorCore) => {
    const range = getSelectionRangeEx(core);
    if (range.type === SelectionRangeTypes.Normal) {
      range.ranges = range.ranges.map((r) => r.cloneRange());
    }
    return range;
  };
```
I simply overrides it like this in our codebase, and it fixed this issue.

**Comment by JiuqingSong** [comment]
Does this happen in demo site?

**Comment by haven2world** [comment]
I can't tell, I only repro it in iOS WKWebView. But my log shows that, every code where we may change the cached selection is not called, but when we use the cached selection, it has been changed.

**Comment by JiuqingSong** [comment]
I'd like to understand more about the issue. Without a local repro it is hard to tell.

**Comment by haven2world** [comment]
Since we cannot upgrade to the latest version roosterjs, I cannot verify if it still exists in the latest version, I'll close this issue since I can workaround it for now. If it still exists after we upgrade the package in the future, I'll reopen this issue.
