### ISSUE TITLE
Copying a table does not carry over inline styles and class as expected

### ISSUE THREAD

**Issue by florian-msft** [microsoft/roosterjs#2267]
**Describe the bug**
When copy-pasting a table using the new content model, some inline styles and class names (and maybe also other properties) get removed when pasting.

**To Reproduce**
1. Open this repro example: https://codepen.io/florian-msft/pen/RwvmwGv
2. Click on the button labeled "click me" (this will insert a table with the bottom right cell in red with rounded corners and a class set)
3. Select and copy the table
4. Insert some line breaks and paste the table below

**Expected behavior**
The table will be inserted with the rounded corners and the same class

**Actual behavior**
The table does not have the rounded corners and the class name got removed

**Screenshots**
![image](https://github.com/microsoft/roosterjs/assets/87671048/89f02073-f948-4954-95ee-e39f92cce98e)

![image](https://github.com/microsoft/roosterjs/assets/87671048/ab235f3c-d7b8-496b-9891-30d83c6e9120)

**Device Information**
 - OS: Windows 11
 - Browser: Edge
 - Version: 119.0.2151.97 (Official build) (64-bit)

**Additional context**
Our code relied on the class being copied over to run additional code when we detected "special" tables.

**Comment by JiuqingSong** [comment]
For round corner, we should keep it.

For the class names, we generally remove all the attributes that are not directly related to representing. You can customize this behavior by creating your own format handler and pass it via editor options to keep it.

**Comment by florian-msft** [comment]
Just another detail I wanted to add is that this does not affect only `border-radius`, but also other properties like `border-spacing` and `border-collapse`
