### ISSUE TITLE
formatTable cell coloring behavior is inconsistent between old and new content model

### ISSUE THREAD

**Issue by florian-msft** [microsoft/roosterjs#2273]
**Describe the bug**
When calling `formatTable` with the new content model and `hasBandedRows: false`, the cells are shaded `bgColorEven` color, but with the old content model it would be transparent.

**To Reproduce**
1. Open this link: https://codepen.io/florian-msft/pen/OJdYEGr?editors=0010
2. Click on the text "click here" to focus the table in the editor
3. Click the button "format table (new)" (this will run `formatTable` code below)
4. The entire table turns red (the background color for even rows)

```
roosterjsContentModel.formatTable(editor, {
    hasBandedRows: false,
    bgColorEven: "red",
    bgColorOdd: "green",
});
```

**Expected behavior**
Maintaining the existing behavior of keeping transparent cells (verify using the "format table (old)" button which will run the same code but using the old content model)

**Screenshots**
N/A

**Device Information**
 - OS: Windows 11
 - Browser: Edge
 - Version: 119.0.2151.97 (Official build) (64-bit)

**Additional context**
N/A

**Comment by JiuqingSong** [comment]
@Andres-CT98 do you want to take a look?

**Comment by JiuqingSong** [comment]
I feel this is by design. If you want the table to be transparent, please do not pass in color when format
