### ISSUE TITLE
Copy/cut will fail if trustedTypes default policy filters comment out

### ISSUE THREAD

**Issue by Yexiaoxing** [microsoft/roosterjs#2289]
**Describe the bug**

When we have trusted thpes default policy on, and the createHTML filters comment out, the copy action will fail.

**To Reproduce**

Enable trusted types default policy as follows:

```javascript
  window.trustedTypes.createPolicy("default", {
      createScriptURL:  str => str,
      createScript: str => str,
      createHTML: str => DOMPurify.sanitize(str),
  });
```

And try to copy in editor, it will fail.

**Expected behavior**

- Content could be copied.
- Roosterjs relys on comment node to save start and end selection data. Maybe throw a console warning when the data is missing?

  Related code: 
  - Here sets the comment node: https://github.com/microsoft/roosterjs/blob/2df5113c2c4e394f1b70f3cef8b600131c847e21/packages/roosterjs-editor-dom/lib/selection/getHtmlWithSelectionPath.ts#L22
  - And it reads the data: https://github.com/microsoft/roosterjs/blob/2df5113c2c4e394f1b70f3cef8b600131c847e21/packages/roosterjs-editor-dom/lib/selection/setHtmlWithSelectionPath.ts#L101

**Screenshots**
n/a

**Device Information**
 - OS: Windows + macOS
 - Browser: Edge + Chrome
 - Version: 120.0.2210.77

**Additional context**

**Comment by JiuqingSong** [comment]
The old editor does rely on comment when cut/copy. So you need to enable comment in DOMPurify config as well. 

https://github.com/microsoft/roosterjs/blob/2df5113c2c4e394f1b70f3cef8b600131c847e21/demo/scripts/utils/trustedHTMLHandler.ts#L5

The new Content Model editor (https://microsoft.github.io/roosterjs/index.html?cm=1) does not rely on comment.

**Comment by Yexiaoxing** [comment]
@JiuqingSong I understand that comment is needed in old mode, can we state it somewhere in the document, or warn user when it happens?

**Comment by JiuqingSong** [comment]
Please feel free to submit a PR about this. You can add comment to the trustHTMLHandler code or type declaration.

Thanks.

**Comment by JiuqingSong** [comment]
Close old bug without new replies, and given that we are deprecating old editor and replace with new editor based on Content Model which doesn't have this issue anymore, we won't fix this one.
