### ISSUE TITLE
[Content Model] The style on SelectionMarker is not up to date after setFontSize more than one time

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2305]
**Describe the bug**
If user set font size twice, the `fontSize` format on `SelectionMarker` won't be updated to the latest state. But if `applyDefaultFormat` in `ContentModelFormatPlugin` is called, it will use the style on the current selectoin marker to generate the new pending format and lose the latest font size style. 

**To Reproduce**
1. Open demo site under content model
2. set font size to 8 pt
3. set font size to 12 pt
4. check the format on selection marker
5. trigger `applyDefaultFormat` (in my case, the plugin received a `KeyDown` event with `ProcessKey`)

**Expected behavior**
The format on selection marker should be updated to the latest so we can always generate correct pending format

**Screenshots**
<img width="1106" alt="image" src="https://github.com/microsoft/roosterjs/assets/17299418/a5faa2f0-7da6-481b-a84e-ea5b312a5c83">

**Device Information**
 - OS: iOS
 - Browser WKWebView

**Comment by haven2world** [comment]
<img width="1112" alt="image" src="https://github.com/microsoft/roosterjs/assets/17299418/5dbb1c54-a4fe-4f6a-b1a6-535de9f00297">
Do you think this fix makes sense?

**Comment by JiuqingSong** [comment]
Can you mark that part that you have changed? Feel free just submit a PR so I can take a deeper look.

Thanks.

**Comment by haven2world** [comment]
I created the PR #2309

**Comment by JiuqingSong** [comment]
@haven2world  Please verify if https://github.com/microsoft/roosterjs/pull/2331 can fix this problem. Thanks.

PR is not fully done yet, I still need to fix test case and add more test cases

**Comment by haven2world** [comment]
@JiuqingSong  it works like a charm!
