### ISSUE TITLE
Read-only entity element can't be deleted by pressing backspace key when using Android IME

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#2318]
**Describe the bug**
When using Android soft keyboard (Gboard), the read-only entity element can't be deleted by pressing backspace. Similar to some previous issues, the root cause is some Android IMEs don't support `KeyboardEvent.key` and this value will always be `229`(Unidentified). To workaround the compatibility issue, we should use `InputEvent` instead. 

We may need to handle `InputEvent` in at least 2 plugins:

- `EditPlugin`, it should dispatch the input event to `entityFeatures`. And the related features including `RemoveEntityBetweenDelimitersFeature`, `DeleteBeforeEntityFeature`, `BackspaceAfterEntityFeature` should also support input event. 
- `ContentModelEditPlugin` and its related logic like `keyboardDelete` should support input event.

**To Reproduce**
1. Insert a read-only entity into the demo editor
2. Try to delete it using Android IME

**Screenshots**

https://github.com/microsoft/roosterjs/assets/67583056/faca7b93-086d-4396-8657-e1308f6f97fe

**Device Information**
 - OS: Android
 - Browser Chrome
 - Version 119

**Additional context**
Similar issues:
https://github.com/microsoft/roosterjs/issues/513
https://github.com/microsoft/roosterjs/issues/2061

**Comment by Rain-Zheng** [comment]
@JiuqingSong could you take a look at this issue?

**Comment by JiuqingSong** [comment]
Thanks for reporting. Would you like to contribute a fix?

Thanks.

**Comment by Rain-Zheng** [comment]
@JiuqingSong I created a PR: https://github.com/microsoft/roosterjs/pull/2402, could you take a look when you have time? Thanks.
