### ISSUE TITLE
MatchLink should be able to match a link inside quotes

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#232]
Link such as "\\server\path" should be able to be matched.

**Comment by Lego6245** [comment]
Should we extend this behavior to parens as well?

**Comment by Lego6245** [comment]
RFC for context: https://tools.ietf.org/html/rfc1123

**Comment by JiuqingSong** [comment]
> Should we extend this behavior to parens as well?

Yes.

**Comment by JiuqingSong** [comment]
Close old issues.
