### ISSUE TITLE
SPFx (Sharepoint Framework) and Rooster React

### ISSUE THREAD

**Issue by rgcircum** [microsoft/roosterjs#2324]
**Describe the bug**
I tried to use Rooster JS React in SharePoint with the SPFx Framework.

it's working, but i have a big problem.

On RichText editor, if i add a link, the enter key on keyboard do not work anymore (shift+enter working)

After remove link the enter key work

I do not reproduce the bug on codeSandbox or another external solution, the bug occur only in SharePoint.

I don't understand, if you have any idea for debug this, i would be happy :D

repos of my test : https://github.com/rgcircum/spfx-rooster-js-react

**To Reproduce**
Add webpart in page, and add link on RichText content.

**Expected behavior**
Line wrapping with the enter key on the keyboard should work

**Device Information**
 - OS: All
 - Browser: Edge, Chrome, I don't have tested on Firefox
 - Version: Latest

**Additional context**
I reported the bug on sp-dev-doc, but I didn't get a response, if anyone from the Rooster team has an idea, I would be happy. Thanks.

https://github.com/SharePoint/sp-dev-docs/issues/9438

I have tested with simple mode and content model editor

**Comment by romanisa** [comment]
Hi, we think this might be an issue at the SharePoint framework side and so we would still urge to get some investigation done on that side first.

**Comment by rgcircum** [comment]
Hi,
I reported the bug on sp-dev-doc without response ...
https://github.com/SharePoint/sp-dev-docs/issues/9438

SharePoint native richText use CKEditor, But I wanted to use Rooster, too bad.

**Comment by JiuqingSong** [comment]
If you can provide something that I can debug directly (e.g. a codepen link, or anywhere you deployed your project), I can take a look.

**Comment by JiuqingSong** [comment]
Close old bug without new replies. 

Please feel free to reactive with more info that I can debug with.

**Comment by rgcircum** [comment]
Sorry for response delay.

All information is in first post (Github repos for test), but, you need a M365 dev plateform (https://developer.microsoft.com/en-us/microsoft-365/dev-program).

Is not reproductible in other context, only Sharepoint/Teams context in SPFx.

[VesaJuvonen](https://github.com/VesaJuvonen) from SPFx Teams have modified issue on sp-dev-doc repos, but without response.

The bug is not resolved, please re-open de issue.

**Comment by JiuqingSong** [comment]
The bug is not actionable to us, and for now we are not even sure if it is a bug in roosterjs, unless we have a local repro.

**Comment by JiuqingSong** [comment]
And as an open source software, if you see any issue that only happens in some special environment, you should debug it from your side and find out the root cause. If it is proved to be a bug of roosterjs, you should be able to build a minimum repro then we can discuss how to fix. Otherwise we have nothing to do with it.
