### ISSUE TITLE
Content Model: General block element is not transformed to dark mode

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#2380]
**Describe the bug**
We are using a custom element processor for transforming the div element with id to a general block, so that we can keep its id in content model. However, if the div has background color, the color will not be handled by DarkColorHandler. 

Problematic div (with an id, transformed to general block, background color is not handled):

<img width="484" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/4993978e-a23f-48a1-ad3e-4d38f252416c">

Normal div (without an id, transformed to format container, background color is handled):

<img width="500" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/5d13f20a-1721-4249-84a3-a201a05775ab">

Is this expected behavior?

**Comment by JiuqingSong** [comment]
What is the end to end repro ste? @Rain-Zheng

**Comment by JiuqingSong** [comment]
@Rain-Zheng please feel free to push a branch with your code change so I can debug with it.

Question: When and how do you switch to dark mode?

**Comment by Rain-Zheng** [comment]
@JiuqingSong I created a branch here: https://github.com/Rain-Zheng/roosterjs/tree/test/general_block_dark_mode

The issue only exists when the default editor style is dark mode. If it's switched from light to dark, the element will be transformed correctly.

**Comment by JiuqingSong** [comment]
Good finding. Here is a fix https://github.com/microsoft/roosterjs/pull/2397

(Still need to add more test cases)
