### ISSUE TITLE
Cannot access ambient const enums when 'isolatedModules' is enabled 

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2387]
**Describe the bug**
Some of the constants are exported as enums from 'roosterjs-editor-types' (for example, `GetContentMode`) that aren't accessbile in TS files when [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) option is enabled in ts config file.

**To Reproduce**
1. Create a react project that uses TS
2. Create a typescript config with `"isolatedModules": true`
3. Try to import `import {GetContentMode } from 'roosterjs-editor-types';` in a file
4. Try to use `GetContentMode` somewhere in code
5. See the error

**Expected behavior**
The exported constants can be used  when 'isolatedModules' is enabled 

**Screenshots**

![image](https://github.com/microsoft/roosterjs/assets/98852890/648cae36-00cd-499a-b395-a7108fccb25d)

**Device Information**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] - 
 - Version [e.g. 22] "roosterjs-editor-types": "^8.59.0",

**Additional context**
More information on the issue: https://ncjamieson.com/dont-export-const-enums/

**Comment by JiuqingSong** [comment]
Please check out the `roosterjs-editor-types-compatible` package. It is just to solve this problem. It provides enum without const with the same value. All functions that accepts the const enum type can also accept the compatible types.

**Comment by vhuseinova-msft** [comment]
I see, thank you very much for the fast response!
