### ISSUE TITLE
Content Model: Setting Rooster content div innerHTML equal to a variable containing html inserts quotes around element property values

### ISSUE THREAD

**Issue by Geoffsc** [microsoft/roosterjs#2391]
When I set the Rooster content div equal to a variable containing html, quotes are getting inserted around element property values i.e.
When I do the following (where roosterFieldValue is a variable containing html I want to load into rooster):
`document.getElementById("EditorContainer").childNodes[0].childNodes[0].innerHTML = roosterFieldValue`

colspan=2 becomes colspan="2"
and
id=imageSelected0 becomes id="imageSelected0"

**Device Information**
 - OS: Windows 10
 - Browser: Edge
 - Version: 8.59.0

**Comment by JiuqingSong** [comment]
I believe this is the behavior of browser. To prove it, create an empty HTML file and paste the following code:
```html
<html>
<body>
<div id="div1"></div>
<script>
window.onload = function() {
var str = "<table colspan=2><tr><td id=imageSelected0>test</td></tr></table>";
var div = document.getElementById("div1");
console.log("Before: " + div.innerHTML);
console.log("String to insert: " + str);
div.innerHTML = str;
console.log("After: " + div.innerHTML);
}
</script>
</body>
</html>
```

When run it, you will see the output from console:
<img width="489" alt="image" src="https://github.com/microsoft/roosterjs/assets/23065085/24e9e91e-27fb-45e2-9478-beac84492018">

As you can see, it is just some pure javascript without any roosterjs code, it can still happen. Browser never guarantee the innerHTML you retrieved is the same with the one you set. There are some other cases that can cause HTML to be changed. From the same example, you can see browser also added `<tbody>` to the HTML which does not exist in source.
