### ISSUE TITLE
'Align center' doesn't work when copy and paste the text

### ISSUE THREAD

**Issue by Thomaskfang** [microsoft/roosterjs#2424]
**Describe the bug**
When I copy the text which is center alignment, and then paste it.
The 'Align center' doesn't work on the pasted text.
The same issue is also on 'Align right'.

**To Reproduce**
1. Go to [Roosterjs demo site](https://microsoft.github.io/roosterjs/index.html)
2. Type in the text "Hello world"
3. And then click 'Align center', and copy the text "Hello world"
4. And then click 'Align left', and paste the text "Hello world"
5. And click 'Align center', it doesn't work

**Expected behavior**

**Screenshots**

**Device Information**

**Additional context**

https://github.com/microsoft/roosterjs/assets/79448542/13fff973-64e3-4e05-8008-b14a9eca9772

**Comment by JiuqingSong** [comment]
Thanks for reporting.

This is already fixed in the new Content Model Editor (https://microsoft.github.io/roosterjs/index.html?cm=1)

**Comment by JiuqingSong** [comment]
It is the next version of roosterjs editor. It is now available from package roosterjs-content-model and its sub packages.

https://microsoft.github.io/roosterjs/docs/modules/roosterjs_content_model.html

**Comment by Thomaskfang** [comment]
> It is the next version of roosterjs editor. It is now available from package roosterjs-content-model and its sub packages.
> 
> https://microsoft.github.io/roosterjs/docs/modules/roosterjs_content_model.html

Hi @JiuqingSong , sorry to bother you again. Could you please give me a demo on how to use this `new Content Model`? Thank you.

**Comment by JiuqingSong** [comment]
Please navigate to https://microsoft.github.io/roosterjs/index.html#options, there is a button "Try roosterjs in CodePen" on the right side. Click it, you will see a simple demo on how to use the new editor code.
