### ISSUE TITLE
Watermark plugin's text value can't be updated or localized

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2430]
**Describe the bug**
It looks like there is no way to update the Watermark's plugin text value after the Watermark plugin is added to an Editor. This causes issues when watermark needs to be localized later after the component is shown. Please see steps to reproduce for the RoosterJS Demo Site when watermark is updated

**To Reproduce**
1. Open RoosterJS Demo Site
2. Open plugins panel
3. Turn on Watermark plugin
4. Update text in the watermark plugin

**Expected behavior**
The watermark text can be updated or at least localized.

**Screenshots**

https://github.com/microsoft/roosterjs/assets/98852890/855969ac-6711-480e-b431-e6c88ca381eb

**Device Information**

- OS: MscOS
- Browser Edge
- Version 121.0.2277.112 (Official build) (arm64)

**Comment by JiuqingSong** [comment]
Thanks for reporting. Yes, it is the current behavior. I think Watermark plugin can provide a callback function in its ctor to allow you provide a latest text. Do you want to make a fix as a self service?

**Comment by vhuseinova-msft** [comment]
It would be great if RoosterJS team has capasity to add this functionality. 
Thanks!

**Comment by vhuseinova-msft** [comment]
https://github.com/microsoft/roosterjs/pull/2507 is merged with updated Watermark plugin functionality
