### ISSUE TITLE
Only number 1 is shown for list items in the numbered list instead of a sequence

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2437]
**Describe the bug**
Numbered list doesn't have correct list items, it's always stuck on 1

**To Reproduce**
1. Open RoosterJS Demo website
2. Click Numbered list button
3. Type something, press Enter
4. Observe that the next item has "1." as list item number instead of "2"

**Expected behavior**
The numbered list should work

**Screenshots**

https://github.com/microsoft/roosterjs/assets/98852890/280ea35e-92c5-4d88-b3ab-3429d0e1f720

**Device Information**
OS: MacOS
Browser Edge
Version 121.0.2277.112 (Official build) (arm64)

**Additional context**

**Comment by haven2world** [comment]
We fixed it by making the `MaintainListChain` edit feature asynchronous. 
I'm not sure if RoosterJS maintainers want to fix it internally since the legacy editor is being deprecated.

```typescript
import { ListFeatures } from 'roosterjs-editor-plugins/lib-mjs/plugins/ContentEdit/features/listFeatures';
import { GenericContentEditFeature, PluginKeyboardEvent } from 'roosterjs-editor-types';

// Run maintainListChain edit feature in async to fix the issue "The number of the new line is not increased after typing return"

const { maintainListChain } = ListFeatures;

/**
 * Maintain the list numbers in list chain
 * e.g. we have two lists:
 * 1, 2, 3 and 4, 5, 6
 * Now we delete list item 2, so the first one becomes "1, 2".
 * This edit feature can maintain the list number of the second list to become "3, 4, 5"
 */
export const AsyncMaintainListChain: GenericContentEditFeature<PluginKeyboardEvent> = {
  keys: maintainListChain.keys,
  shouldHandleEvent: maintainListChain.shouldHandleEvent,
  handleEvent: (event, editor) => {
    setTimeout(() => {
      maintainListChain.handleEvent(event, editor);
    }, 50);
  },
};
```

**Comment by vhuseinova-msft** [comment]
Hi @haven2world,
I see, thank you very much for sharing the code!

**Comment by JiuqingSong** [comment]
@juliaroldi can you take a look? The recent change should not impact legacy editor, but I remember this should work not too long ago.

**Comment by JiuqingSong** [comment]
Ok, this is because in demo site some content edit features are not enabled by default. Once enabled, this would work. 
![image](https://github.com/microsoft/roosterjs/assets/23065085/66ed00c2-24f4-4986-8769-5a26a383c722)

@juliaroldi  I think we should only turn them off for content model demo site.

**Comment by JiuqingSong** [comment]
#2439
