### ISSUE TITLE
Use border shorthand CSS property and hex colors for table editor

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2438]
**Describe the bug**
Currently **every** cell in a table created by table editor is at least 130 characters long and this can create some restrictions for customers. (The 5*5 table has length of more than 3200 characters without any text in that table). 
`<td style="width: 100px; border-width: 1px; border-style: solid; border-color: rgb(171, 171, 171); vertical-align: top;"><br></td>`
This can be drastically improved by using shorthand `border` CSS prop that is supported by all major desktop and mobile browsers for [a long time.](https://developer.mozilla.org/en-US/docs/Web/CSS/border) 
Also, colors are currently set as rgb values that take 10-16 characters when hex value could be used and it's only 7 characters.

Please let me know if there is any workaround for this.

**To Reproduce**
1. Open RoosterJS demo web site
2. Add a table
3. Open Developer menu
4. Check the html code for the table's cells

**Expected behavior**
The shortest styling desciptions should be used as it increases length of the text that consumers doesn't see or use directly.

**Screenshots**
<img width="1327" alt="image" src="https://github.com/microsoft/roosterjs/assets/98852890/ca2a05d0-ddd9-427c-b260-3ad232a59a45">

**Device Information**
 - OS: MacOS
 - Browser: Edge

**Additional context**

**Comment by JiuqingSong** [comment]
1. For old editor, we will not fix it.
2. For new (content model) editor, today we just use innerHTML directly with all properties handled separately. This is for performance since additional calculation (check if all 4 borders are the same) will take more time
3. But when export HTML, I think we can have a format applier override to do this kind of additional calculation to make the generated HTML shorter.

**Comment by JiuqingSong** [comment]
@vhuseinova-msft 
I created a demo using Content Model editor with a format applier override to merge border style together if it can.

![image](https://github.com/microsoft/roosterjs/assets/23065085/a28afa45-548a-4c58-85da-233222954b6a)

https://codepen.io/jiuqingsong/pen/MWREKPK
