### ISSUE TITLE
Copying content from a dark mode website into a dark mode Rooster editor results in flipped colors

### ISSUE THREAD

**Issue by florian-msft** [microsoft/roosterjs#2449]
**Describe the bug**
Copying light text on dark background content (commonly found in dark mode) into a Rooster editor results in the pasted content being flipped.

**To Reproduce**
1. Go to a website with light text on dark background
2. Copy the text and paste it into the demo site

**Expected behavior**
The pasted content is similar to the copied content (light on dark)

**Actual behavior**
The pasted content has dark text on light background (see below)

**Screenshots**
Copied content:
![image](https://github.com/microsoft/roosterjs/assets/87671048/55808de2-1a3e-4b4f-88fe-eb5cb86d597e)
Pasted into demo site:
![image](https://github.com/microsoft/roosterjs/assets/87671048/355a9960-97b5-43ee-b214-d2410b1e79b2)

**Device Information**
 - OS: Windows 11
 - Browser: Edge
 - Version: 121.0.2277.128

**Additional context**
N/A

**Comment by JiuqingSong** [comment]
This is by design. The copy side should make it copy in light mode.

From our side, we don't know if it is copied from dark mode or it is intentional to be light on dark, so we always treat it as light content and do color conversion.
