### ISSUE TITLE
Content Model: Feature to add anchor ids

### ISSUE THREAD

**Issue by Geoffsc** [microsoft/roosterjs#2456]
It would be great if the content model had a feature to add anchor ids, particularly to Header elements. That way users could create a Table of Contents with hyperlinks that link to the anchor ids for the different section headers.

**Comment by JiuqingSong** [comment]
Can you provide more details, such as the source HTML, the related content model you expect? For now I'm not quite understand the requirement.

**Comment by Geoffsc** [comment]
@JiuqingSong thanks for your response. I think ideally the feature might work something like this:

- The user highlights some text towards the bottom of the editor
- The user clicks an "Anchor" button with options "insert Anchor" or "remove Anchor". Insert Anchor has a field to enter the anchor id. If the user doesn't enter anything in the field and clicks ok, nothing in the html changes (similar to if you don't enter a URL for the hyperlink button). 
- When insert anchor is clicked, the text is then wrapped in an anchor tag like:
`<a id="Heading1"</a>`
- User can then highlight text above the anchored text and click an "anchor link" button
![image](https://github.com/microsoft/roosterjs/assets/28767461/3e3a8560-5cf4-4d43-ac58-220431e22012)
Which wraps that text in an anchor hyperlink:
`<a href="#Heading1">Heading 1</a>`

That way the user can create as many of these anchor ids and corresponding anchor links as they wish to create a Table of Contents at the top of the editor, which links to the corresponding sections below.

**Comment by JiuqingSong** [comment]
I see. Actually you mean something like `<a name="...">` rather than `<a id="...">` right?

**Comment by Geoffsc** [comment]
> I see. Actually you mean something like `<a name="...">` rather than `<a id="...">` right?

I think that should work!

**Comment by JiuqingSong** [comment]
This can be done by creating your own format parser for link and store the name property, and write it back when create DOM tree. 

Then for the input dialog, you can do it in your own code.
