### ISSUE TITLE
[Improvement] Allow setBackgroundColor and setColor to be used without editor gaining focus

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2480]
**Describe the bug**
Currently, rooster js editor always have a background color that can't be changed with `DefaultFormat` props. Because of this, `setBackgroundColor` can be used to set the background color instead (without updating styles for `div` directly). Currently, `setBackgroundColor` and `setColor` always cause the editor to be focused even when it wasn't focused by before the functions were called.

**To Reproduce**
Check files:
- content model - https://github.com/microsoft/roosterjs/blob/2ae2dec3053eadf24b251a76668aaa671310e518/packages/roosterjs-content-model-api/lib/publicApi/segment/setBackgroundColor.ts#L12
- current RoosterJS GA version - https://github.com/microsoft/roosterjs/blob/2ae2dec3053eadf24b251a76668aaa671310e518/packages/roosterjs-editor-api/lib/format/setBackgroundColor.ts#L15
- content model - https://github.com/microsoft/roosterjs/blob/2ae2dec3053eadf24b251a76668aaa671310e518/packages/roosterjs-content-model-api/lib/publicApi/segment/setTextColor.ts#L9
- current RoosterJS GA version - https://github.com/microsoft/roosterjs/blob/2ae2dec3053eadf24b251a76668aaa671310e518/packages/roosterjs-editor-api/lib/format/setTextColor.ts#L16

**Expected behavior**
The editor shouldn't always be focused when backgorund or text colors are set.

**Comment by JiuqingSong** [comment]
Can you explain more why you don't want editor to be focused?

**Comment by vhuseinova-msft** [comment]
For example I have a situation, when I want to change the default background color and text color. I need to set `doNotAdjustEditorColor` to `true` so everything isn't set back to defaults when the theme(dark/light mode) is changed. 
But in this case, if the editor wasn't focused before, and I change the theme and use `setBackground` or `setColor` functions, the editor will be focused by default.
I think there also may be issues with focus in case if there are a few rooster js editors on the same webpage.

Just to share more info, it's not a blocking issue for me, just wondering if this functionality can be improved.

**Comment by JiuqingSong** [comment]
Do you mean you want to change background color of the editor root DIV?

**Comment by vhuseinova-msft** [comment]
These ones:
https://github.com/microsoft/roosterjs/blob/ac262d81340b06c8c5bb3a30b44cfb353481c150/packages/roosterjs-editor-core/lib/corePlugins/LifecyclePlugin.ts#L14

**Comment by JiuqingSong** [comment]
Not quite understand. LifecyclePlugin is using the down level API `setColor` to change background color, not `setBackgroundColor`, they are two different thing.

**Comment by JiuqingSong** [comment]
`setBackgroundColor` should only be used by ribbon button, when user click on the button to change color of selected text. In that case we expect editor to be focused so user can keep typing.

It should not be used in other case.

For all other cases, you can use the down level API `setColor` instead.

**Comment by vhuseinova-msft** [comment]
I see, thanks for the clarifications! It would be great to have a link for `setColor` in the documentation for `setBackgroundColor` (or some other documentation in place) as sometimes it's not very easy to find this kind of documentation withou code checking.
