### ISSUE TITLE
Link color resets and doesn't persist

### ISSUE THREAD

**Issue by angelusmcnally** [microsoft/roosterjs#2500]
**Describe the bug**
Text link color doesn't persist.  Was able to repro in demo site and OWA.

**To Reproduce**

1. On the Rooster demo site, add a link.
![image](https://github.com/microsoft/roosterjs/assets/113393579/3283e180-97b2-4a33-b983-845dfcd3473c)
2. Change the link color and wait a few seconds.
![image](https://github.com/microsoft/roosterjs/assets/113393579/c256ee40-300a-40c2-9559-5b0198a25a1e)
3. Notice the link color changing back from the set state.
![image](https://github.com/microsoft/roosterjs/assets/113393579/2fb2972a-eb92-4153-aff0-a66ec15a4e81)

**Expected behavior**
Selected link color should persist.

**Comment by JiuqingSong** [comment]
Waited more than one hour but the color doesn't change to me. So not repro.
