### ISSUE TITLE
Content Model: creating a DOM tree using selection marker results in blank window and/or throws an error. 

### ISSUE THREAD

**Issue by gm-al** [microsoft/roosterjs#2505]
**Describe the bug**
The selection marker has a few issues when trying to create a DOM tree using the selection marker, inputting a value in any of the style inputs results in a blank window or throws onUpdate is not a function. 

**To Reproduce**
1. Open roosterjs dome site. and click on the side pane.
2. Click on the content model, and hover over the document word to see "the search icon" and click on it.
3. Similarly, hover over the selection marker to see the option and click on format.

-> Throws onUpdate is not a function: 4. Input a value in any of these fields `Font size`, `Font family`, or `Bold`.
-> Window goes blank -> 4.  Input a value in any of these fields `Text color`, or `Back color`.

**Expected behavior**
To update a value correctly.

**Current behavior**
Throws an error, and/or goes blank

**Screenshots**
Throws, onUpdate is not a function.
![isajdoiasjdoiasjdoiasjd](https://github.com/microsoft/roosterjs/assets/107857762/d21f270e-81f7-496c-bbe7-763648c7f7a7)

The window goes blank.
![doiwndoiuand](https://github.com/microsoft/roosterjs/assets/107857762/51e9deef-d412-45b5-a771-536b7f6cb865)

**Comment by JiuqingSong** [comment]
I can't repro. 

Do you mean just hover on the icon, no other operations? I tried but t here isn't any error to me
![1](https://github.com/microsoft/roosterjs/assets/23065085/e81ddda6-ae38-4013-9c4c-bf853ec8bf88)

**Comment by gm-al** [comment]
Oh sorry. So, when you hover over SelectionMarker and the options pop up, next to the search icon click on the format icon
 
![Screenshot 2024-03-14 011516](https://github.com/microsoft/roosterjs/assets/107857762/944aa1c9-8381-4003-ba74-1f173bfd4ff7)

For onUpdate is not a function, try inputting a value in any of these fields, and check the dev console for the error:
![Screenshot 2024-03-14 011758](https://github.com/microsoft/roosterjs/assets/107857762/af786153-8a70-437d-9d7f-c125c6681de3)

**Comment by gm-al** [comment]
Try inputting a value here and watch the window of the app go blank/white:

![Screenshot 2024-03-14 012112](https://github.com/microsoft/roosterjs/assets/107857762/2de87bc2-22d6-45ca-99d9-7a8bed1dd4f7)

**Comment by JiuqingSong** [comment]
I see. Now I can repro.

The demo site is just a demo (or a debugging tool), but not part of production. I'll take a look when I have got some time. You can also submit a fix if you want. Thanks.
