### ISSUE TITLE
Editing a url does not update the link

### ISSUE THREAD

**Issue by dmhabib** [microsoft/roosterjs#254]
When pasting a url into the editor, it correctly turns it into a hyperlink.  Later, if I go back and edit the link text it does not update the link address.  For example, if I paste 'http://www.github.net' into the editor, realize it's wrong and update it to 'http://www.github.com' it will still link to the old url.

**To Reproduce**
1. Add a url to the editor
2. Using the keyboard, go back and edit the text of the url
3. Notice:  The text is updated but the link is not.

**Expected behavior**
I would expect that if the text of the link originally matches the target address, editing the link text would update the link url.

**Comment by JiuqingSong** [comment]
This is a valid issue. Thanks for reporting. We'll prioritize the fix.

**Comment by JiuqingSong** [comment]
This will be fixed in 8.0.0
