### ISSUE TITLE
[Bug]: roosterjs-content-model-api - changeFontSize not working as expected

### ISSUE THREAD

**Issue by pradeept95** [microsoft/roosterjs#2568]
**Describe the bug**
changeFontSize (doc [here](https://stackblitz.com/edit/vitejs-vite-jgmyq1?file=src%2FExample.tsx)) not working if we does not set font size explicitly. 

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/vitejs-vite-jgmyq1?file=src%2FExample.tsx&terminal=dev'
2. Select text and click on 'Increase font size' or 'Decrease font size' - it does not increase or decrease the font size of the selected text
3. select text and apply font size using ''select font size" dropdown, and click on 'Increase font size' or 'Decrease font size', indeed it does work and change the size of the text accordingly 

**Current behavior**
If we don't set font size explicitly, it does not seems changing font size of the block. 

**Expected behavior**
It should either use the current font size or default font size if not explicitly specified 

**Device Information**
 - OS: Any
 - Browser: Any
 - Version: 9.0

If you have any questions or suggestion, please let me know.

**Comment by JiuqingSong** [comment]
The changeFontSize API requires the selected already has a font size. Normally this can be done by setting a default format for editor, then all text typed in editor will have a default font size. If initial content is set programmatically, the initial content also need to have a font size.

**Comment by pradeept95** [comment]
Thank you so much for quick response. do you have docs ref or simple example how I can set default font size.

**Comment by JiuqingSong** [comment]
Here is the code we use in demo site https://github.com/microsoft/roosterjs/blob/a4457db8c9806400b27a1567c206b2bc5bf40290/demo/scripts/controlsV2/mainPane/MainPane.tsx#L349

**Comment by pradeept95** [comment]
Thank you so much. It helped a lot!
