### ISSUE TITLE
Using ContentChangedEvent

### ISSUE THREAD

**Issue by AlphaGeek** [Microsoft/roosterjs#257]
How do I just add an event to capture when the text in the editor changes or when an image is pasted into the editor or when an image is resized.  Do I need to create a plugin for that?  Seems like I should just be able to wire up contentChanged to the editor object, e.g....

`this.editor.contentChanged( function() { //do something } )`

**Comment by JiuqingSong** [comment]
For now, creating a plugin is the only way to receive any event from editor.
You can handle both ContentChanged event (for non-user-input change) and Input event (for user-input change).

**Comment by AlphaGeek** [comment]
Thanks for the reply, I really like the editor so far.
