### ISSUE TITLE
contentModelToText treat some elements as empty string

### ISSUE THREAD

**Issue by milliezhang-qinlan** [microsoft/roosterjs#2601]
**Describe the bug**
Currently, Outlook Android is using `RoosterEditor.getContent(GetContentMode.PlainText)` to get the plainText of the editor content and use the plainText to determine if it is empty in the compose editor.

However, when there are only images and entities in the editor, `RoosterEditor.getContent(GetContentMode.PlainText)` will return empty string.

After checking the implementation in roosterjs, we find that:
`contentModelToText `will treat some elements as empty string, such as image and entity. 
![Screenshot 2024-04-25 at 15 39 07](https://github.com/microsoft/roosterjs/assets/63031370/d430995f-c029-40ba-b6c1-719e17d0ed38)

**To Reproduce**
Only insert images or entities in the editor and then check the result of `RoosterEditor.getContent(GetContentMode.PlainText)`

**Expected behavior**
Can we append some 'placeholder string' for these elements?
For example:
image elements as: IMG
entity: ENTITY

**Device Information**
- Can be reproduced for all kinds of browsers

**Comment by JiuqingSong** [comment]
I think we can add a callback parameter to allow caller customize the string for each element.
