### ISSUE TITLE
Watermark plugin doesn't work well with the indentation change when editor doesn't have any content

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2622]
**Describe the bug**
Watermark doesn't work well when there is no text in the editor and indentation is changed. Please see the attached video for more details.

**To Reproduce**
1. Open [RoosterJS demo website](https://microsoft.github.io/roosterjs/index.html#options)
2. Check that Watermark plugin text is shown
3. Increase/decrease indentation

**Expected behavior**
Either the Watermark plugin text needs to be updated and indentation for it should change 
or 
the Watermark plugin text should be hidden and indentation should change.

**Screenshots**

https://github.com/microsoft/roosterjs/assets/98852890/c1449f32-94ba-4801-9242-fb94785bbdd5

**Device Information**
 - OS: MacOS
 - Browser Edge
 - Version 9.2.0

**Additional context**

**Comment by JiuqingSong** [comment]
Do you want to submit a fix?

**Comment by vhuseinova-msft** [comment]
@JiuqingSong, not sure if I have capacity for this during the next few weeks. It would be great if you have time to looks into it

**Comment by JiuqingSong** [comment]
Sorry I don't have. 
Watermark plugin is a low pri to us since we don't use it at all. It is totally for 3rd party.

**Comment by vhuseinova-msft** [comment]
Fixed in https://github.com/microsoft/roosterjs/pull/2625
