### ISSUE TITLE
Content Model convert "dir" attribute to "direction" style

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2644]
**Describe the bug**
Content Model's `directionFormatHandler` convert "dir" attribute to "direction" style, but in MDN, "direction" is not recommended.
First, "direction" style doesn't support "auto"
And even more, the "dir" attribute is still preserved, if "dir" is "auto" and "direction" is left, the RTL support will be broken.
https://developer.mozilla.org/en-US/docs/Web/CSS/direction
<img width="789" alt="image" src="https://github.com/microsoft/roosterjs/assets/17299418/cafd4fd3-448a-4214-8404-445412d04eab">

**To Reproduce**
1. add "dir=auto" on any Div
2. trigger Content Model conversion

**Expected behavior**
Keep "dir" as recommended

**Comment by JiuqingSong** [comment]
I'll close this one since I think it is already solved.

If you think we should still use dir instead of direction (as warned shown), please reactivate and I can go with the existing PR
