### ISSUE TITLE
How to get table border options with new version of rooster.

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/roosterjs#2662]
**Describe the bug**
As of now we are using rooster ^8 version. We want to upgrade the package to rooster ^9 with all the table border functionalities.

As of now we are using following plugins
```
const ribbonPlugin = useRef<RibbonPlugin>(createRibbonPlugin());
const imageEdit = new ImageEdit({ preserveRatio: false });
const plugins = [
	updateContent.current,
	new ContentEdit(),
	new AutoFormat(),
	new Paste(),
	new CustomReplacePlugin(),
	new HyperLink(),
	imageEdit,
	new CutPasteListChain(),
	new TableCellSelection(),
	new TableResize(),
	createContextMenuPlugin(),
	createTableEditMenuProvider(),
	createListEditMenuProvider(),
	createImageEditMenuProvider(imageEdit),
	createEmojiPlugin(),
	ribbonPlugin.current
]

//creating editor in the following way
editorRef.current = new Editor(containerRef.current, getEditorOptions());
```
In order to get the table border functionalites is there any plugin to be used or is package upgrade is enough ?

**Comment by BryanValverdeU** [comment]
Hello,
The package upgrade is enough to be able to use the new table border API no plugin is needed, you just have to call the new public API [applyTableBorderFormat ](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-content-model-api/lib/publicApi/table/applyTableBorderFormat.ts)to set the table borders as needed.

**Comment by bhanu345-cmd** [comment]
Could you please provide the sample code for applyTableBorderFormat. How to use that?

**Comment by BryanValverdeU** [comment]
Sample code for this and using the Ribbon can be found here:
https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controlsV2/demoButtons/tableBorderApplyButton.ts

And the buttons to set the border color to be applied can be found here:
https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controlsV2/demoButtons/tableBorderColorButton.ts
https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controlsV2/demoButtons/tableBorderStyleButton.ts
https://github.com/microsoft/roosterjs/blob/master/demo/scripts/controlsV2/demoButtons/tableBorderWidthButton.ts

**Comment by bhanu345-cmd** [comment]
Is this exported from any package or not? Can we directly use this button, or should we have to write the code manually?

Here you are using Editor from rooster-content-model-core package whereas in older version we are using editor from rooster-editor-core package.

Which editor is supported for this? If we use the new editor, all the above plugins mentioned are supported?

getButtons is being used from new package. shouldn't we use getButtons from older package?

**Comment by BryanValverdeU** [comment]
> Is this exported from any package or not? Can we directly use this button, or should we have to write the code manually?

The specific function to set the borders (https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-content-model-api/lib/publicApi/table/applyTableBorderFormat.ts) is only available in v9 RoosterJS. The buttons are a example you can use to write your own component on top of RoosterJS.

> Here you are using Editor from rooster-content-model-core package whereas in older version we are using editor from rooster-editor-core package.

Right, the option to set the table borders is only available with the v9 RoosterJS package. In the v8 RoosterJS this API is not available.

> Which editor is supported for this? If we use the new editor, all the above plugins mentioned are supported?

Yes, the v9 RoosterJS is compatible with old v8 plugins. So old plugins can still work in v9 Editor. You only need to pass in the v8 plugins to the legacyPlugins in the Editor props.

> getButtons is being used from new package. shouldn't we use getButtons from older package?

The RoosterJS React package is not a Production ready code, it is only a way to demo how you can build your Component. If you decide to use this same approach as the Rooster React you can use those same function.

**Comment by bhanu345-cmd** [comment]
It would be really very helpful if you could provide sample code about using old plugins, tableBorderButton with new version. It is not looking straight forward and little bit confused.

**Comment by bhanu345-cmd** [comment]
Could you please add below old plugins as well and Ribbon as well along with tableBorderButton.
This is how we are initializing the editor with old version. What changes needs to be done to support new version and tableBorderButton

```
import { EditorOptions, EditorPlugin } from 'roosterjs-editor-types';
import { ContentEdit, AutoFormat, CustomReplace as CustomReplacePlugin, Paste, HyperLink, ImageEdit, CutPasteListChain, TableCellSelection, TableResize } from 'roosterjs-editor-plugins';
import { createListEditMenuProvider, createImageEditMenuProvider, createContextMenuPlugin, ReactEditorPlugin, createTableEditMenuProvider, createRibbonPlugin, Ribbon, RibbonPlugin, createEmojiPlugin, getButtons, AllButtonKeys, createUIUtilities, UpdateMode, AllButtonStringKeys, RibbonButton } from 'roosterjs-react'
import { Editor } from 'roosterjs-editor-core';

export const Rooster=()=>{
const ribbonPlugin = useRef<RibbonPlugin>(createRibbonPlugin());

const setUtilitiesToPlugins = (plugins: EditorPlugin[]) => {
	if (containerRef.current) {
		const uiUtilities = createUIUtilities(containerRef.current, theme);
		plugins.forEach((plugin) => {
			if (isReactEditorPlugin(plugin)) {
				plugin.setUIUtilities(uiUtilities)
			}
		})
	}
}
const getAllPlugins = () => {
	if (!allPluginsRef.current.length) {
		const imageEdit = new ImageEdit({ preserveRatio: false });
		const plugins = [
			new ContentEdit(),
			new AutoFormat(),
			new Paste(),
			new CustomReplacePlugin(),
			new HyperLink(),
			imageEdit,
			new CutPasteListChain(),
			new TableCellSelection(),
			new TableResize(),
			createContextMenuPlugin(),
			createTableEditMenuProvider(),
			createListEditMenuProvider(),
			createImageEditMenuProvider(imageEdit),
			createEmojiPlugin(),
			ribbonPlugin.current
		]
		allPluginsRef.current = plugins;
		setUtilitiesToPlugins(plugins);

		return plugins
	} else {
		return allPluginsRef.current;
	}

}

  const getEditorOptions = (): EditorOptions => {
	return {
		plugins: getAllPlugins(),
		/*initialContent: props.initialContent,*/
		defaultFormat: {}

	}
}

useEffect(()=>{
   const isInitializing = !editorRef.current;
    if (isInitializing && containerRef.current) {
	editorRef.current = new Editor(containerRef.current, getEditorOptions());
    }
},[])
<div className="rooster">
<Ribbon plugin={ribbonPlugin.current} buttons={[...getButtons([...AllButtonKeys])] as RibbonButton<AllButtonStringKeys>[]} /> : null}
<div aria-label="editor" className="roosterContainer"></div>
</div>
}
```

**Comment by BryanValverdeU** [comment]
If you provide a codepen/repo I can advice how to do it. 
I do not have bandwidth right now to start it from zero.

**Comment by BryanValverdeU** [comment]
Closing this for now, if you have a repo/codepen we can take a look feel free to reopen.
