### ISSUE TITLE
How to create an anchor with content-model

### ISSUE THREAD

**Issue by Alex-Brines** [microsoft/roosterjs#2665]
Hi, I am trying to create an anchor `(<a name=“????”></a>)` based on the insertLink method. Comment that I have 2 problems:
1.- It does not generate me the HTML code mentioned above, it only creates the <a> tag without the name attribute.
2.- When I export with the exportContent method of the roosterjs-content-model-core package it removes the `<a>` tag.

Attached is the complete code:

```
 export function insertAnchor(editor: IEditor, name?: string) {
    editor.focus();

    if (name) {
        const anchors: ContentModelLink[] = [];
        let anchorNode: Node | undefined;

        editor.formatContentModel(
            (model, context) => {
                const segments = getSelectedSegments(model, false);
                const originalText = segments
                    .map(x => (x.segmentType == 'Text' ? x.text : ''))
                    .join('');
                const text = originalText || '';

                if (
                    segments.some(x => x.segmentType != 'SelectionMarker') &&
                    originalText == text
                ) {
                    segments.forEach(x => {
                        const link = createAnchor(name);
                        addAnchor(x, link);
                        if (x.link) {
                            anchors.push(x.link);
                        }
                    });
                } else if (
                    segments.every(x => x.segmentType == 'SelectionMarker') ||
                    (!!text && text != originalText)
                ) {
                    const segment = createText(text, {
                        ...segments[0]?.format,
                        ...editor.getPendingFormat(),
                    });
                    const doc = createContentModelDocument();
                    const link = createAnchor(name);

                    addAnchor(segment, link);
                    addSegment(doc, segment);

                    if (segment.link) {
                        anchors.push(segment.link);
                    }

                    mergeModel(model, doc, context, {
                        mergeFormat: 'mergeAll',
                    });
                }

                //adjustTrailingSpaceSelection(model);
                return segments.length > 0;
            },
            {
                changeSource: ChangeSource.CreateLink,
                onNodeCreated: (modelElement, node) => {                    
                    if (!anchorNode && anchors.indexOf(modelElement as ContentModelLink) >= 0) {
                        anchorNode = node;
                    }
                },
                getChangeData: () => anchorNode,                
            }
        );
    }
}
const createAnchor = (name: string): ContentModelLink => {
    return {
        dataset: {},
        format: {
            name: name            
        },
    };
};
const addAnchor = (segment: ContentModelSegment, link: ContentModelLink): void => {
    if (link.format.name) {
        segment.link = {
            format: { ...link.format },
            dataset: { ...link.dataset },
        };
    }
};
```

**Comment by JiuqingSong** [comment]
Currently this is not supported. To make it work, we need to create a new segment type.

**Comment by Alex-Brines** [comment]
Hello Jiuqungsong

I have found a way to do it and it is by forcing onNodeCreated by adding the name attribute:

```
onNodeCreated: (modelElement, node) => {
    if (!anchorNode && anchors.indexOf(modelElement as ContentModelLink) >= 0) {
        if (node instanceof HTMLAnchorElement)
            node.setAttribute("name", name);
        anchorNode = node;
    }
},
```

The main problem is when exporting the content to HTML (exportContent), either to show the source of the text or to recover the value and carry out the appropriate procedures in each case.

Is there any way to not delete the anchor tag when exporting?

**Comment by JiuqingSong** [comment]
Can you build a minimum repro on a online js debugging platform (e.g. [codepen](https://codepen.io/pen/)) and send the link to me so I can debug?

**Comment by Alex-Brines** [comment]
Hello @JiuqingSong 

In the following link there is a mini example.

https://codepen.io/alexbrines/pen/BaeRaPz

Add text, select it and press the "Add anchor" button. Once the anchor is created, press the "Export" button and the html code referring to the anchor does not appear in the textarea.

Another problem that I have seen is that when pressing enter on an anchor already created, it generates anchors, 1 for each enter.

**Comment by JiuqingSong** [comment]
I think normally when talking about an anchor, we usually create an empty A tag, for example
```html
some text
<a name="xxxx"></a>
some text
```

So it is not possible to put cursor into the empty A tag.

And the problem of the anchor is, once applied, there is not any visually changes, so it is impossible for user to tell if there is an anchor or not. We need to specially render something to let user know. The best way is to create a new type of segment to specially support this.

Go back to your example, it generally works, the only problem is you also need to customize the behavior of `exportContent`, the 3rd parameter of this function allows you pass in more options to override default behavior.

**Comment by Alex-Brines** [comment]
Is there an example of how to create a new type of segment?

**Comment by JiuqingSong** [comment]
I mean that need to happen inside our core code.

For your case, maybe you can use General model to hold an A tag as a workaround.

I have a prototype here
https://codepen.io/jiuqingsong/pen/bGyoKwr

**Comment by Alex-Brines** [comment]
Hello @JiuqingSong 

I have found a possible bug regarding the insertion of the anchor.
1.- Text is entered in the prototype that you have provided.
2.- Next, the anchor is inserted after the text.
3.- It is positioned at the end of the text entered in point 1 and when deleted the anchor disappears

I attach a video, I have modified the CSS so that the anchor is displayed.


https://github.com/microsoft/roosterjs/assets/171062631/e4465bf5-1f2d-45d4-aa73-b1431f63d2d5

**Comment by Alex-Brines** [comment]
I have tried adding the options for the exportContent to include the anchor. Unfortunately I'm not very clear on how to do it. Could you give me the guidelines or an example of how to do it?

**Comment by JiuqingSong** [comment]
Things like empty A tag may have this kind of issue. In general, the main goal of roosterjs is to build a rich text editor, but not a web page builder. So things like empty anchor is not well supported, since it is not visible at all. From a user, there is no way to tell if there is an anchor or not. So that is not in our goal. The whole concept of content model is trying to forget HTML and DOM, but just create content instead. HTML and DOM is just a way to represent the content. In theory there can be other ways than HTML.

If want, you may need to let content model render something for an anchor, such like a SPAN. Then only when export final HTML, write the empty anchor instead. But that means some other work is required, not a very simple example.

I'd suggest not use roosterjs to create anchor. If anchor is a very import concept to you, roostejrs may not be the best choice.

**Comment by Alex-Brines** [comment]
OK thanks. I will choose to show in rooster an image that represents the anchor and develop two functions to import and export the HTML code from/to rooster.
