### ISSUE TITLE
cursor move to the left of the link after create it

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2666]
**Describe the bug**
cursor move to the left of the link after create it， can repro it on OWA but not in Demo

**To Reproduce**
Input `http://bing.com` and type space

**Expected behavior**
The cursor can go to the end of link

**Screenshots**

https://github.com/microsoft/roosterjs/assets/24806909/7097fbc2-09f6-4d06-baf7-d149eafef11b

**Device Information**
 - OS: macOS
 - Browser Safari
 - Version 14.5

**Additional context**

**Comment by JiuqingSong** [comment]
Hmm, I tried on mac OS with both Safari and Edge, on both demo site and OWA, but none of them can repro

**Comment by miku1958** [comment]
Wait, have you update OWA's roosterjs last week?

**Comment by miku1958** [comment]
Sorry it is safari issue, I wrote the wrong broswer.

**Comment by JiuqingSong** [comment]
I'm still not able to repro on Safari.
