### ISSUE TITLE
Assignment of css class (class attribute) in selection

### ISSUE THREAD

**Issue by Alex-Brines** [microsoft/roosterjs#2667]
Hi, I am developing a functionality which in a selector loaded with css styles, when selecting one, add the class attribute to the selection, if it is text create a `<span>` tag with the class attribute. If it is a whole object, for example a `<div>` add the class attribute to that object.

I have not found anything about adding the class attribute to a selection.

Thank you very much.

**Comment by BryanValverdeU** [comment]
Hello @Alex-Brines 
Have you tried adding [::selection](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection) pseudo selector to the elements you want to style different when selected?

**Comment by Alex-Brines** [comment]
Sorry but my English is not too good

I have an editor UI with a select that contains CSS styles from a style sheet loaded on the page. What I want is for the element selected in the editor, whether it is a text or an element, to have the class attribute added with the value of the selected option. Attachment Screenshot

![ScreenShot](https://github.com/microsoft/roosterjs/assets/171062631/49d00fc6-640a-4fc7-abcb-f09bfd0eff97)

**Comment by JiuqingSong** [comment]
To apply a customized CSS class name, you need to override default Content Model handlers to let it write your class object. You also need to customize the code where we parse HTML DOM to let it recognize the class.

You first need to create a customized format type. For example
```ts
type ClassNameFormat = {
   className?: string;
}

type SegmentWithClassNameFormat = ContentModelSegmentFormat & ClassNameFormat;
```

Then create a format parser and applier:
```ts
const classNameParser: FormatParser<ClassNameFormat> = (format, element) => {
  const className = element.className;
  if (className) {
      format.className = className;
  }
}

const classNameApplier: FormatApplier<ClassNameFormat> = (format, element) => {
   if (format.className) {
     element.className = format.className;
  }
}
```

Then append these parser and applier to segments when create editor:
```ts
const editor = new Editor(div, {
   ...
   defaultDomToModelOptions: {
     additionalFormatParsers: {
        segment: [classNameParser]
     }
   },
   defaultModelToDomOptions: {
      additionalFormatAppliers: {
         segment: [classNameApplier]
      }
   }
});
```
   
This will make your editor recognize className and preserve it. Finally, you can create your own format API to apply the class:
```ts
export function setClassName(editor: IEditor, className: string) {
  formatSegmentWithContentModel(editor, 'setClassName', format => {
     const classFormat = format as SegmentWithClassNameFormat;
     classFormat.className = className;
  }
}
```

**Comment by BryanValverdeU** [comment]
I have a demo codepen with the implementation Jiuqing suggested if it helps:
https://codepen.io/Bryanvalverdeu/pen/LYoxRoO

**Comment by Alex-Brines** [comment]
Thanks for the explanation. It works for me
