### ISSUE TITLE
Table size selection shows incorrectly on mobile

### ISSUE THREAD

**Issue by palatter** [microsoft/roosterjs#2669]
**Describe the bug**
As shown below, the table size selection is missing squares at bottom right.

![IMG_20C964E0CEFC-1](https://github.com/microsoft/roosterjs/assets/73612854/3af9cdb9-7935-4e38-bf75-d05e7a774e55)

**To Reproduce**
1. Open https://microsoft.github.io/roosterjs/index.html#format on a mobile device
2. Create table
3. Table size selection prompt isn't displayed properly.

**Expected behavior**
This is a screenshot from the desktop version. You can see the table size selection shows correctly.

![image](https://github.com/microsoft/roosterjs/assets/73612854/b40ab042-de47-4e9d-a9d5-1920a1e95882)

**Screenshots**

**Device Information**

**Additional context**

**Comment by JiuqingSong** [comment]
Thanks for reporting. The demo site is only used for feature demo is intentional to used on desktop environment only. Demo code is not part of production.
