### ISSUE TITLE
Auto correction make list number become default font size 

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2672]
**Describe the bug**
Auto correct make list number become default font size.

I found it is easier to repro it in Safari, because Safari's auto correction is more frequent.
The reason for this may be that WebKit creates a new li element when there has span in li. Adding fonts to ol will fix this.

**To Reproduce**
1. Turn browser's grammar check on
3. Create a list, set different font size and typos like
```html
<ol start="1" data-editing-info="{&quot;orderedStyleType&quot;:1}" style="list-style-type: decimal;"><li style="font-family: Calibri; font-size: 26pt; color: var(--darkColor__000000, #000000);"><div style="font-family: Calibri; color: var(--darkColor__000000, #000000);"><span style="font-size: 26pt;">a</span></div></li><li style="font-family: Calibri; font-size: 26pt; color: var(--darkColor__000000, #000000);"><div style="font-family: Calibri; color: var(--darkColor__000000, #000000);"><span style="font-size: 26pt;">b</span></div></li><li style="font-family: Calibri; font-size: 26pt; color: var(--darkColor__000000, #000000);"><div style="font-family: Calibri; color: var(--darkColor__000000, #000000);"><span style="font-size: 26pt;">micro</span><span style="font-size: 36pt;">oft&nbsp;</span></div></li></ol>
```
![image](https://github.com/microsoft/roosterjs/assets/24806909/ab550224-60f4-44a3-9b9b-baee0c3a5ee4)
4. Change some text to other size (to add span)
![image](https://github.com/microsoft/roosterjs/assets/24806909/e47c9ff9-f0bc-478c-ab7c-6d0adced7aab)
5. Correct it
![image](https://github.com/microsoft/roosterjs/assets/24806909/8fab138f-db94-4524-b453-182ce87a67f7)

**Expected behavior**
List number's font won't change

**Device Information**
 - OS: macOS
 - Browser safari
 - Version 14.5

**Comment by JiuqingSong** [comment]
Partially fixed by https://github.com/microsoft/roosterjs/pull/2683
