### ISSUE TITLE
'imageSelectionBorderColor' config doesn't take effect in Safari

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#2676]
**Describe the bug**
In Safari, the image border color is always blue, regardless of the value of `imageSelectionBorderColor`:

|Safari|Chrome|
|--|--|
|<img width="188" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/b17d373c-ee72-43d6-966e-5bdc1a4c6749">|<img width="188" alt="image" src="https://github.com/microsoft/roosterjs/assets/67583056/f397caf2-67fb-489b-b0f0-65b0f1b2a038">|

It seems that if the `outline-style` is set to `auto`, the `outline-color` won't take effect. 

**To Reproduce**
1. Open roosterjs demo page
2. Insert an image and cilck it
3. Check the border's color

**Expected behavior**
The border's color should respect to the value of `imageSelectionBorderColor`. 

**Device Information**
 - OS: MacOS 14
 - Browser: Safari
 - Version: 17.5

**Comment by JiuqingSong** [comment]
Hi, thanks for reporting. Do you want to submit a fix?

**Comment by JiuqingSong** [comment]
This should have been fixed by https://github.com/microsoft/roosterjs/pull/2670
