### ISSUE TITLE
Watermark plugin creates empty trailing div

### ISSUE THREAD

**Issue by T-Roth** [microsoft/roosterjs#270]
**Describe the bug**
When using the Watermark plugin the first character typed gets put before the div. 
```
"a"
<div></div>
```

Subsequent characters will cause the text to get put in a div, but the trailing empty div at the end remains
```
<div>ab</div>
<div></div>
```

**To Reproduce**
1. Include the Watermark plugin
2. Type a single character
3. Check the editors contents

**Expected behavior**
Would expect the first character to be put in a div with no trailing empty div

**Device Information**
 - OS: Win 10
 - Browser Chrome
 - Version 72

**Comment by JiuqingSong** [comment]
Can you help me understand how to get the state? 
```html
"a"
<div></div>
```

Does it happen in https://microsoft.github.io/roosterjs/?

**Comment by T-Roth** [comment]
Repro steps:

- Create a editor with a watermark plugin
- Type a single character
- Check the editors contents

[roosterjs sample.zip](https://github.com/Microsoft/roosterjs/files/3066339/roosterjs.sample.zip)

**Comment by JiuqingSong** [comment]
Thanks for the report. I can repro it now.
