### ISSUE TITLE
Remove default style added to every div

### ISSUE THREAD

**Issue by T-Roth** [Microsoft/roosterjs#271]
Is there a way to remove the default styles added to every div?

`<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">`

**Comment by JiuqingSong** [comment]
Yes. You can pass "{}" as the value of default format when create the editor.

new Editor(div, {
  defaultFormat: {},
});

**Comment by T-Roth** [comment]
I get an exception when I try to pass anything other than an array of plugins for the 2nd param.  The documentation and typescript also seem to only show it as an array of plugins



This will fail on some internal plugin initialization code
```
let editorDiv = document.getElementById('editorDiv');

let plugins = [new roosterPlugins.Watermark("watermark test...")];

let options = {
  plugins: plugins,
  defaultFormat: {}
};

let editor = roosterjs.createEditor(editorDiv, options);

```

**Comment by JiuqingSong** [comment]
There are two ways to create an editor:

https://github.com/Microsoft/roosterjs/wiki/Create-an-editor-using-createEditor()-API
https://github.com/Microsoft/roosterjs/wiki/Create-an-editor-using-Editor-class

To specify a default format, you need to use the second way which allow you to customize a lot of things including the default format.
