### ISSUE TITLE
autoUnlink will turn any link into plain text unconditionally

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2720]
**Describe the bug**

**To Reproduce**
1. Open demo
2. Enable auto unlink in plugin list
3. Use Insert link button to insert a link or paste a html link element manually
4. Press `Backspace`

**Expected behavior**
Only the autoLinked link turns into plain text, but autoUnlink just turn any link into plain text unconditionally
https://github.com/microsoft/roosterjs/blob/be7889d8ce3ec707715bb8eb6fa108fbc41fd53f/packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts#L232C1-L243C6

**Additional context**
Also, if I move the cursor to the middle of the link and Backspace, it will become this:
![image](https://github.com/microsoft/roosterjs/assets/24806909/edda8393-bfd2-4df0-9f40-cc450dbda50d)

**Comment by JiuqingSong** [comment]
This feature is something we are considering to delete, since it has multiple problems, and there is no requirement to support it. That is why it is disabled by default.

**Comment by miku1958** [comment]
Closed as no plan to fixed
