### ISSUE TITLE
Text Color issue

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2721]
**Describe the bug**
Text Color only apply to the last word

**To Reproduce**
1. Go to Demo
2. Type something
3. Select partial text
![image](https://github.com/microsoft/roosterjs/assets/24806909/a6b6ebcd-1392-4013-92e2-d1a54a9ed59f)
4. Add a background color <- Selection is missing
![image](https://github.com/microsoft/roosterjs/assets/24806909/7d1fbdae-b245-4429-b78a-eac2074f12ad)
5. Change the Text Color <- Color is applied to wrong target
![image](https://github.com/microsoft/roosterjs/assets/24806909/557d06a9-06f0-4ecc-813a-7d5ce7007b37)

**Comment by JiuqingSong** [comment]
This is intentional. We unselect text after applying background color. Otherwise user can't see the background color because of the selection. Word has the same behavior:
![image](https://github.com/microsoft/roosterjs/assets/23065085/3bc7a336-8ad7-46a4-b5af-7965b24f999d)
