### ISSUE TITLE
How to listener focus and blur events

### ISSUE THREAD

**Issue by Alex-Brines** [microsoft/roosterjs#2722]
Hello
How to capture focus and blur events in roosterjs. The idea is to show a toolbar when the roosterjs editor has focus and when it loses focus the toolbar is hidden.

Thank you so much

**Comment by JiuqingSong** [comment]
You can use [IEditor.attachDomEvent](https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_content_model_types.ieditor.html#attachdomevent)
