### ISSUE TITLE
Options for Tabbing behaviour

### ISSUE THREAD

**Issue by palatter** [microsoft/roosterjs#2725]
**Describe the bug**
Hi,

I saw that an [older version](https://github.com/microsoft/roosterjs/blob/deb6cf74714cfe58f006d1475bb4b8b0814abf6b/packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEdit.ts#L67) of roosterJS seemed to have a way to turn off tabbing to indent. We need to prevent this from happening as it prevents A11Y keyboard navigation.

Can this please be added to the 'Edit Plug'
 
Thanks!

**To Reproduce**
1. Press Tab button when in editor.

**Expected behavior**

Tab should move focus to next UI element. Without this it breaks A11Y behaviour.

**Screenshots**

**Device Information**

**Additional context**

**Comment by BryanValverdeU** [comment]
This should be out in the latest RoosterJS version.
https://github.com/microsoft/roosterjs/releases/tag/v9.7.0
