### ISSUE TITLE
Images in tables are not properly copied from Word

### ISSUE THREAD

**Issue by itsein123** [microsoft/roosterjs#2736]
**Describe the bug**
Pasting images in table from Word into Rooster don't display images properly

**To Reproduce**
1. Create table with images in Word (win32)
2. Select table, copy
3. Paste into Rooster demo site

**Expected behavior**
Images in table are not displayed properly.
Pasting only images without tables work as expected

**Screenshots**
![image](https://github.com/microsoft/roosterjs/assets/174150343/e4933a3f-53c1-4077-bbfc-0bd99c995599)

Table with images clipboard data:
<table class="MsoTableGrid" border="1" cellspacing="0" cellpadding="0" style="border-collapse:collapse;border:none;mso-border-alt:solid windowtext .5pt;
 mso-yfti-tbllook:1184;mso-padding-alt:0in 5.4pt 0in 5.4pt">
 <tbody><tr style="mso-yfti-irow:0;mso-yfti-firstrow:yes">
  <td width="208" valign="top" style="width:155.8pt;border:solid windowtext 1.0pt;
  mso-border-alt:solid windowtext .5pt;padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><span style="mso-no-proof:yes"><img width="238" height="180" src="file:///C:/Users/einchang/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg" alt="Image result for cats" v:shapes="Picture_x0020_4"></span><o:p></o:p></p>
  </td>
  <td width="208" valign="top" style="width:155.85pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><span style="mso-no-proof:yes"><img width="268" height="180" src="file:///C:/Users/einchang/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg" alt="Image result for cats" v:shapes="Picture_x0020_5"></span><o:p></o:p></p>
  </td>
  <td width="208" valign="top" style="width:155.85pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
 <tr style="mso-yfti-irow:1;mso-yfti-lastrow:yes">
  <td width="208" valign="top" style="width:155.8pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><o:p>&nbsp;</o:p></p>
  </td>
  <td width="208" valign="top" style="width:155.85pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><o:p>&nbsp;</o:p></p>
  </td>
  <td width="208" valign="top" style="width:155.85pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0in 5.4pt 0in 5.4pt">
  <p class="MsoNormal" style="margin-bottom:0in;line-height:normal"><o:p>&nbsp;</o:p></p>
  </td>
 </tr>
</tbody></table>

**Comment by BryanValverdeU** [comment]
Hello @itsein123,
We are considering this as a Word bug, as the images that are added to the clipboard on copy contain local file paths as the src attribute. The Word team have a open issue and they are working on it.
