### ISSUE TITLE
Two list types of bullet are the same.

### ISSUE THREAD

**Issue by liyaxin116** [microsoft/roosterjs#2754]
**Describe the bug**
The bullet list types of long arrow and double long arrow are the same.

Long arrow:
<img width="120" alt="image" src="https://github.com/user-attachments/assets/8cedf629-33d6-47c1-ab0a-74c9f9605dae">
Double long arrow:
<img width="132" alt="image" src="https://github.com/user-attachments/assets/e287dc40-5542-4308-b7f9-f1ddd4faac7d">

**To Reproduce**
Select the bullet style in toolbar of demo site and check the style of arrows.
<img width="262" alt="image" src="https://github.com/user-attachments/assets/1648a26b-28fd-4850-b83d-41f686d8e33a">

**Expected behavior**
The arrow of double long arrow should be longer.

**Screenshots**
Attached above.

**Comment by JiuqingSong** [comment]
@juliaroldi would you please take a look? Thanks

**Comment by juliaroldi** [comment]
@JiuqingSong I'll work on this.

**Comment by juliaroldi** [comment]
We categorize the bullet types by the character used to trigger the auto list. LongArrow and DoubleLongArrow trigger the same list type, but the characters that trigger are different. LongArrow is triggered by -> and DoubleLongArrow -->. I think we only need to DoubleLongArrow in this list.
