### ISSUE TITLE
Rooster version 9.7 removes table formatting

### ISSUE THREAD

**Issue by viveksharma0906** [microsoft/roosterjs#2757]
1. **ISSUE 1**
I have recently upgraded rooster to version 9.7 and It seems to be removing the formatting of a table which is created manually with some style. I am sharing a screenshot of the issue.

![image](https://github.com/user-attachments/assets/3e78d918-a426-478d-a83e-70d53c6042e8)

Before creating editor object contentDiv at line 139 had table border formatting present and after editor object creation, exported content doesn't have that border. It seems like some internal formatting is happening while editor is created. Screenshot also shows createEditor function which shows the options being used to create editor. Let me know if I missed something to avoid this.

2. **ISSUE 2**
Sharing more example of some formatting from editor:
![image](https://github.com/user-attachments/assets/e7a10cf4-589e-4b01-9f66-81515f5b415a)
Incoming content's styling seems to be distributed amonng additional span tag's and this content loses "tabIndex" in this instance. Which makes the placeholder button:
![image](https://github.com/user-attachments/assets/eb3bf11d-bab0-4ec0-a6bb-50bb9ec17f7b)

3. **ISSUE 3**
Another important business use case is that we are adding a QR Code div id which is being removed from formatting of editor. We need id preserved from editor as we refer to it in code and decide api payload.
![image](https://github.com/user-attachments/assets/031740b5-7936-4e7b-a921-f48b5d9ffc8c)
Content before had div id "QRCode" in it later insertedContent doesn't have it.

**Comment by JiuqingSong** [comment]
Here is some test code I have tried to preserve id and tabIndex from DIV, and border from TABLE:
```ts
import { isElementOfType } from 'roosterjs-content-model-dom';
import {
    ContentModelBlockFormat,
    ContentModelTableFormat,
    DomToModelOption,
    FormatApplier,
    FormatParser,
    IdFormat,
    ModelToDomOption,
} from 'roosterjs-content-model-types';

type TableBorderFormat = {
    htmlBorder?: string;
};

type TabIndexFormat = {
    tabIndex?: number;
};

type ContentModelTableFormatEx = ContentModelTableFormat & TableBorderFormat;

const tableBorderFormatParser: FormatParser<ContentModelTableFormatEx> = (format, element) => {
    if (isElementOfType(element, 'table') && element.border) {
        format.htmlBorder = element.border;
    }
};

const tableBorderFormatApplier: FormatApplier<ContentModelTableFormatEx> = (format, element) => {
    if (isElementOfType(element, 'table') && format.htmlBorder) {
        element.border = format.htmlBorder;
    }
};

const blockFormatParser: FormatParser<ContentModelBlockFormat & IdFormat & TabIndexFormat> = (
    format,
    element
) => {
    if (isElementOfType(element, 'div') && element.id) {
        format.id = element.id;
    }

    if (isElementOfType(element, 'div') && element.tabIndex) {
        format.tabIndex = element.tabIndex;
    }
};

const blockFormatApplier: FormatApplier<ContentModelBlockFormat & IdFormat & TabIndexFormat> = (
    format,
    element
) => {
    if (format.id) {
        element.id = format.id;
    }

    if (format.tabIndex) {
        element.tabIndex = format.tabIndex;
    }
};

export const domToModelOptions: DomToModelOption = {
    additionalFormatParsers: {
        table: [tableBorderFormatParser],
        block: [blockFormatParser],
    },
};
export const modelToDomOptions: ModelToDomOption = {
    additionalFormatAppliers: {
        table: [tableBorderFormatApplier],
        block: [blockFormatApplier],
    },
};
```

When create editor:
```ts
const editor = new Editor(div, {
   ...
   defaultDomToModelOptions: domToModelOptions,
   defaultModelToDomOptions: modelToDomOptions,
});
```

Then these properties can be preserved:

![image](https://github.com/user-attachments/assets/504f4b9b-6608-4a7e-ba79-22f4038ac878)

BTW, according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#border, `border` property on TABLE element is deprecated, please try not using it.
