### ISSUE TITLE
Selecting/right-clicking on an image in a table doesn't seem to work as expected

### ISSUE THREAD

**Issue by itsein123** [microsoft/roosterjs#2758]
**Describe the bug**
Sometimes, images in tables don't seem to be selected properly, but they look selected (image has resize handles)
![image](https://github.com/user-attachments/assets/f62149b8-afb8-41c2-9b8b-8b9163fe8fe0) 
For images in tables, copying or right-clicking to see the image menu options doesn't seem to work as expected.

**To Reproduce**
**Bug 1:**
1. Create a table 2*2
2. Insert an image in one cell
3. Add text another
4. Click to select the image (have it show the resize handles)
5. Click to select the text
6. Right-click or select the image
7. ![image](https://github.com/user-attachments/assets/6ae76d1a-a31c-432d-80f4-f49da1d32bbe)

**Expected:** see image menu options (like resize)
**Actual:** see table menu options 

**Bug 2:**
1. Create a table 2*2
2. Insert an image in one cell
3. Add text another
4. Select on the image
5. Press Ctrl+C to copy image
6. Press Ctrl+V to paste image

**Expected:** to paste image
**Actual:** image wasn't copied properly and didn't paste

**Device Information**
 - Browser: Edge

**Comment by JiuqingSong** [comment]
@juliaroldi I think this is fixed now, right?

**Comment by juliaroldi** [comment]
@JiuqingSong this was fixed by https://github.com/microsoft/roosterjs/pull/2781
