### ISSUE TITLE
 js/incorrect-suffix-check - Using indexOf to implement endsWith functionality is error-prone if the -1 case is not explicitly handled.

### ISSUE THREAD

**Issue by sswathisri** [microsoft/roosterjs#2771]
Hello, 

We have a  Code QL bug reported in this library for js/incorrect-suffix-check
Error: Using indexOf to implement endsWith functionality is error-prone if the -1 case is not explicitly handled.
Severity: High and Important

FIle is under \roosterjs-editor-dom\lib-mjs\utils\getComputedStyles.js. Screenshot shows the function and line to add check.

**Expected behavior**
Suggested fix: if (px && px.indexOf('px') !== -1 && px.indexOf('px') == px.length - 2) {

**Screenshots**
![image](https://github.com/user-attachments/assets/ebc90c66-066d-43d1-be42-eb34d7fb495f)

**Device Information**
 N/A

**Additional context**
N/A

Please kindly address this issue as soon as possible. Thank you.

**Comment by JiuqingSong** [comment]
The v8 code (roosterjs-editor-*) is not deprecated and we will not fix more bugs for it. Please use v9 instead.
