### ISSUE TITLE
Select an Image and cmd+c will cause the selection change

### ISSUE THREAD

**Issue by Echo-az** [microsoft/roosterjs#2790]
**Describe the bug**
Select an image then cmd+copy will cause the selection jump to the beginning of the editor. Clicking it twice has the same effect. It seems like Safari only.

**To Reproduce**
1. Go to RoosterJS Demo Site in Safari
2. Insert an image and select it
3. Cmd+C to copy it

**Expected behavior**
Selection doesn't change

**Screenshots**
Selection changed, cursor goes to the beginning of the editor.

**Device Information**
 - OS: macOS 14.6.1
 - Browser: Safari

**Comment by romanisa** [comment]
@juliaroldi can you please take a look?
