### ISSUE TITLE
adjustLinkSelection does not select whole link

### ISSUE THREAD

**Issue by jdhuntington** [microsoft/roosterjs#2804]
**Describe the bug**
When editing an existing link using `adjustLinkSelection` where the link has multiple words (eg `<a href="#">foo bar baz</a>`), only a single word will be returned when the cursor is on `bar` and no selection exists.

**To Reproduce**
1. Go to https://microsoft.github.io/roosterjs/index.html
1. Type "this is a test foo bar baz"
1. Highlight "foo bar baz"
2. Click the ribbon icon to insert a link
3. Keep "foo bar baz" as "Display as", pick anything for the URL (eg `#`)
4. Click "ok"
5. Clear the selection
6. Put the cursor in the middle of "baz" (which is now part of a link)
7. Click "Insert link" again
8. Notice "Display as" contains only "baz"

**Expected behavior**
In the final step, "Display as" should contain "foo bar baz"

**Screenshots**
![Screenshot 2024-09-19 at 11 07 32 AM](https://github.com/user-attachments/assets/4c9db32c-e394-4313-9b7b-e61407555b87)
![Screenshot 2024-09-19 at 11 07 46 AM](https://github.com/user-attachments/assets/da03966d-c3da-49e7-bd2c-d51318e6a5ee)
![Screenshot 2024-09-19 at 11 08 47 AM](https://github.com/user-attachments/assets/5a60a8bc-817f-45b6-bf4b-d6e07b6ed154)
![Screenshot 2024-09-19 at 11 10 39 AM](https://github.com/user-attachments/assets/26965f12-aabb-4b91-bb81-dea8c6a3fdff)
![Screenshot 2024-09-19 at 11 10 43 AM](https://github.com/user-attachments/assets/942254a2-81a5-49d0-93b4-984e6d3dde39)

**Device Information**
macOS, firefox (evergreen)

**Comment by JiuqingSong** [comment]
Thanks, I can repro.
