### ISSUE TITLE
Bold style is missing when select the bold text and input

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2825]
**Describe the bug**
(under content model)
When I select the bold text and then input some characters, the new characters which replaced the bold text is not bold

**To Reproduce**
1. Go to demo site
2. Input some text and set them to bold
3. Select them and input some new stuff

**Expected behavior**
The new added text should also be bold like the legacy editor

**Screenshots**
https://github.com/user-attachments/assets/0f6c1c54-43ae-45f5-bf62-9c4c755a2e8f

**Device Information**
 - OS: mac
 - Browser chrome
 - Version latest

**Comment by JiuqingSong** [comment]
![Image](https://github.com/user-attachments/assets/fd8931ab-b855-4473-a377-e45d18334cf2)

I can't repro. Which version of roosterjs did you test on?

**Comment by JiuqingSong** [comment]
Got it. So you mean select the whole part of bold text, and type something to replace it, right?
