### ISSUE TITLE
Using ctrl while moving an image copies it to cursor location

### ISSUE THREAD

**Issue by viveksharma0906** [microsoft/roosterjs#2829]
**Describe the bug**
While moving the image if you press ctrl and drag & drop the image, it will copy the image in new cursor location which shouldn't happen. It should just move the image not create a copy of the image.

**To Reproduce**
1. Add an image. 
2. Press and use Drag & drop on image.
3. Observe that is copies the image

**Expected behavior**
It should just move the image

**Device Information**
 - Browser : chrome

This was repro on rooster demo site too. https://microsoft.github.io/roosterjs/index.html

**Comment by JiuqingSong** [comment]
This is by design. Drag and drop image with CTRL pressed will copy the image. Word has the same behavior:

![Image](https://github.com/user-attachments/assets/1e15f064-fade-4471-a964-de6389a5665f)
