### ISSUE TITLE
Margin of image is being copied to following div's

### ISSUE THREAD

**Issue by viveksharma0906** [microsoft/roosterjs#2830]
**Describe the bug**
Styling of images wrapped within a div with margin is being applied to div's that are added after the image in editor.

**To Reproduce**
1. Add an image.
2. Add margin to this image styles from dev tools.
3. Enter after image and add some text, enter and repeat adding text in new lines.
4. Observe that spacing between lines is same as margin applied to image.

**Expected behavior**
Space between lines after image should not be the margin applied to image.

**Screenshots**
![Image](https://github.com/user-attachments/assets/25de1b6d-bb85-45c7-b9f2-421e3bc6949d)

**Device Information**
 - Browser : chrome

**Comment by JiuqingSong** [comment]
If you set margin to the DIV, then ENTER should inherit this style, it is by design.

If you set margin to the IMG instead, ENTER won't inherit the style.
