### ISSUE TITLE
Regression: All subsequent content is deleted after tab/shift-tab to navigate in empty table cell

### ISSUE THREAD

**Issue by Echo-az** [microsoft/roosterjs#2831]
**Describe the bug**
All subsequent content is deleted after tab/shift-tab to navigate in empty table cell. It's a regression caused by #2764.

**To Reproduce**
1. Input something
2. Create a table and ensure there's other content after it
3. Use tab/shift-tab to navigate inside the table and ensure the target table cell is empty (only a \<br\>)
4. Input anything

**Expected behavior**
The new input will show in the table cell and other remains the same.

**Problmatic behavior**
The new input shows but all subsequent content is deleted. It seems like all subsequent content is selected and replaced by the new input.

**Screenshots and Video**
https://github.com/user-attachments/assets/4cb8339b-ddb5-4e8c-a202-e12c39761ae3
Before:
![Image](https://github.com/user-attachments/assets/9dd3d3db-4fc8-493d-b80e-ec6f56fe3638)
After:
![Image](https://github.com/user-attachments/assets/5c7784ae-b793-4729-96f9-c0b861ed984f)

**Device Information**
 - OS: macOS14.7
 - Browser: webKit

**Comment by JiuqingSong** [comment]
This is known and is already fixed in https://github.com/microsoft/roosterjs/pull/2809

Can you verify?

Thanks.

**Comment by Echo-az** [comment]
Thanks a lot!! Verified it's fixed in 9.11.0. Will upgrade it soon.
