### ISSUE TITLE
[Regression] input \n after typing url will not become link

### ISSUE THREAD

**Issue by miku1958** [microsoft/roosterjs#2832]
**Describe the bug**

**To Reproduce**
1. Go to Demo
2. input a url like http://www.microsoft.com
3. input EnterKey

**Expected behavior**
url become link

**Screenshots**
![Image](https://github.com/user-attachments/assets/afaee3e4-cc01-4517-8233-bf0e218810c4)

**Device Information**
 - OS: macOS
 - Browser safari
 - Version 18.0.1

**Comment by JiuqingSong** [comment]
Please check out the PR #2837, and it requires enabling an experimental feature `HandleEnterKey`.

For example:
```ts
const editor = new Editor(div, {
  experimentalFeatures: [ 'HandleEnterKey' ],
  ...
}
```
