### ISSUE TITLE
Add a parameter for formatContentModel to allow auto detection of new/removed entities

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#2855]
We have the auto detection code in `EntityPlugin` but it is only executed when `context.newEntities` is undefined. When using `formatContentModel`, this array is already defined, so those code will not be executed.

We can add something as parameter (in context or somewhere) or do a smart detection to decide if we should do the detection, so we can safely add/remove entities in `formatContentModel` and no need to do extra work to make them hydrated/cleaned up.

**Comment by ndjonbor** [comment]
@JiuqingSong Can confirm this work well, and I can remove my old hack 👍 Tnx
