### ISSUE TITLE
Highlighting a piece of text and typing over it/replacing it doesn't maintain the text's formatting treatments.

### ISSUE THREAD

**Issue by bateau** [microsoft/roosterjs#2862]
**Describe the bug**
For example, if you type over "A" in situation like this:
![Image](https://github.com/user-attachments/assets/a412858a-b663-4526-8bb1-893e6421da78)

New text will be blue and bold rather than black and normal. I can repro this in rooster demo site with attached HTML

**To Reproduce**
1. Load the attached HTML file into demo site [foo.txt](https://github.com/user-attachments/files/17624447/foo.txt)
2. Locate text "What is it?" with bold like image above. Select text after it that's not bold and type something to replace it.

**Expected behavior**
New text should be plain, like the original, not bold and blue like preceding text. 

**Screenshots**

**Device Information**

**Additional context**

**Comment by JiuqingSong** [comment]
Thanks. Minimum repro:
```html
<div style="text-align: left; text-indent: 0px; margin: 0px;" class="elementToProof"><span style="color: rgb(12, 100, 192);"><b>What is it? </b></span><span style="font-size: 14.6667px; background-color: rgb(255, 255, 255);">A</span></div><!--{"type":"range","start":[0,1,0,0],"end":[0,1,0,1],"isReverted":true,"isDarkMode":false}-->
```

It is because we first delete selected content, then let browser handle the input. If the content before selection has different format, this can happen. Maybe we need to place a ZeroWidthSpace to replace the selection instead of just a selection marker after delete. I need to try it
