### ISSUE TITLE
Are we going to support selection path under Content Model?

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#2869]
SelectionPath can be serialized which is really helpful in hybrid development. Sometimes we have to let the native side handle some selection logic but we cannot pass an element or range to the native side.

I found the SelectionPath is removed in the Content Model. So could we still support it? or provide a similar serializable structure to present selection?

**Comment by JiuqingSong** [comment]
selection path is not needed for editor itself now, so we removed it. If you still want to use it, you can add it into your code.
