### ISSUE TITLE
Images missing when pasting from Word

### ISSUE THREAD

**Issue by TomaGas** [microsoft/roosterjs#288]
When pasting text with multiple images, the images are missing.

**To Reproduce**
0. Prepare word document with some text and images.

1. Open https://microsoft.github.io/roosterjs/index.html and paste the document contents into editor.
2. Current result: Text is pasted, but images are missing (empty rectangles)

**Expected behavior**
Document content is pasted including formatting and images.

**Device Information**
IE 11 / Chrome 73 
Word - Office 365 desktop app

**Additional context**
Case 2:
Open VSTS and go to create new work item (eg bug). 
Paste document contents into text description field.
Expected: Document content is pasted, including styling and images.
Current result: On IE 11, images paste ok. On chrome/edge images are missing.

Why does it work with IE 11 on VSTS (form uses roosterjs), but does not work in other cases?

**Comment by JiuqingSong** [comment]
This is a known limitation. If you inspect into the HTML it copied, you will see the images are copied as a local file address, e.g. file:///c:/temp/...
When you paste into a desktop app, it can read the file from this temp folder, however this can't be done from browser, so it results in a broken IMG tag.
