### ISSUE TITLE
Issues with pasting

### ISSUE THREAD

**Issue by Alex-Brines** [microsoft/roosterjs#2883]
When you paste plain text when you configure the editor without segmentFormatModel, it automatically adds formatting to the paste. This can be reproduced in the demo by removing the style with the developer tools and performing a paste.

![Image](https://github.com/user-attachments/assets/1742789a-f3df-4c18-8ecd-58e43beee776)

**Comment by JiuqingSong** [comment]
I think this is expected. Text without any format may have some issue somewhere especially when put them into a container that has format, they will use container's format.

**Comment by Alex-Brines** [comment]
Hello,
I'm sorry but I've been reading other threads and I haven't been able to review the answer. It seems to me more like an error than an expected operation. Is there a way to configure the editor so that it doesn't have a default format, so that the CSS class of the container panel predominates? I'm attaching an example in the real scenario.

![Image](https://github.com/user-attachments/assets/3fddd868-737d-4942-bbd2-7e85dcead517)

If there is any other option to solve this problem that would be great.

Thanks and regards.
