### ISSUE TITLE
Add `compositionupdate` and `compositionstart` events to be available in PluginEventType enum and triggered by the editor

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/roosterjs#2902]
**Describe the bug**
Currently, only `compositionend` is available [as part of PluginEventType](https://github.com/microsoft/roosterjs/blob/334e038952eb191053948d407223c9ab45cfc5e2/packages/roosterjs-content-model-core/lib/corePlugin/domEvent/DOMEventPlugin.ts#L214). However, there is no way to handle `compositionupdate` and `compositionstart` events that are helpful for such functionality as typing indicator (`contentChanged` event is not send by RoosterJS during composition session).
Please add `compositionupdate` and `compositionstart` to allow customers to be able to customize behavios for all available languages/inout types.

**To Reproduce**
1. Open demo app
2. Select Japanese (Romaji) as input language in the Operation System
3. Type something in the roosterjs editor
4. Notice that there are no `compositionupdate` and `compositionstart` events set to RoosterJS editor consumers.

**Expected behavior**
Customers can handle `compositionupdate` and `compositionstart` events.
- https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event
- https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event

**Screenshots**

**Device Information**
 - OS: MacOS
 - Browser Edge

**Additional context**

**Comment by JiuqingSong** [comment]
You can use editor.attachDomEvent() to attach them manually.
