### ISSUE TITLE
Picker Example - Character Trigger

### ISSUE THREAD

**Issue by stap123** [microsoft/roosterjs#300]
By any chance does anyone have an example of how to use the picker plugin to trigger a popup. I'm specifically looking to be able to type @ and then present a popup with users (similar to how GitHub or Azure DevOps does this).

Has anyone got a successful implementation of this they wouldn't mind sharing?

**Comment by JiuqingSong** [comment]
PickerPlugin doesn't provide UI, it is just a controller. You need to build your own UI and trigger it. Please reference to code under https://github.com/microsoft/roosterjs/tree/master/publish/samplesite/scripts/controls/samplepicker

**Comment by stap123** [comment]
Thanks :)

**Comment by EmaAlina** [comment]
Hello, 
The link above given as reference
https://github.com/microsoft/roosterjs/tree/master/publish/samplesite/scripts/controls/samplepicker  is no longer valid. 

Has anyone got a successful implementation of this they wouldn't mind sharing (for the last version publishes)?

Thank you,
