### ISSUE TITLE
Track Changes Plugin

### ISSUE THREAD

**Issue by chimon2000** [microsoft/roosterjs#304]
**Describe the bug**
Plugin to track changes to a document.

**To Reproduce**
n/a

**Expected behavior**
* Ability to track adds/updates/deletes
* Ability to visually see changes
* Ability to see who changed the document

**Screenshots**
In the following example, red represents deletions, green represents additions, and red/green represents edits.

![image](https://user-images.githubusercontent.com/6907797/58571295-73c23480-8207-11e9-9efc-3a666a933545.png)

**Device Information**
n/a

**Additional context**
This seems like an extension of the snapshot feature on the demo site.

**Comment by JiuqingSong** [comment]
Currently we don't have plan to add such plugin. But you are welcome to contribute.
