### ISSUE TITLE
Hyperlink not showing Text box

### ISSUE THREAD

**Issue by fwd079** [microsoft/roosterjs#307]
Hi 

On any visualstudio.com workitem (both Edge and Chrome) the Hyperlink button popup has Address box but not a Text box, so a big URL is just there without a proper Text.

Regards.

**Comment by JiuqingSong** [comment]
This is part of VSTS UI, which is not provided by roosterjs. Suggest to send feedback to VSTS.

**Comment by fwd079** [comment]
Huh.

Okay, their [blog  post](https://devblogs.microsoft.com/devops/new-advanced-text-editor-on-the-work-item-form-in-azure-devops/) says it differently. Apparently it is you?
 Anyway posted there as well. 

* Getting flashbacks of circular reference *

Regards.
