### ISSUE TITLE
How can I use the editor to make links open in a new window?

### ISSUE THREAD

**Issue by Shambo21** [microsoft/roosterjs#327]
With some other editors, there are options to target blank by hovering or right clicking on links. It would be useful to have the same feature in roosterjs if it already isn't there.

**Comment by JiuqingSong** [comment]
Are you asking for opening the link from editor, or opening from a document generated by the editor?

Inside editor, we already support opening in new window by press Ctrl key and left click.
For the document generated by editor, you can add your own plugin to change the default behavior.

**Comment by Shambo21** [comment]
Thank you so much, I’m trying to use the editor with react and typescript and I’m relatively new to both, but I’m sure I’ll figure out the plugin part 

Thank you!

**Comment by JiuqingSong** [comment]
I'll close this issue for now. If you get more question, feel free to reactivate. Thanks.
