### ISSUE TITLE
Data attribute cleared on clear-format (and clear-block) when it shouldn't be

### ISSUE THREAD

**Issue by bochong** [microsoft/roosterjs#328]
The data attribute should be preserved on clear-format and clear-block for scenarios like mentions.

**Comment by JiuqingSong** [comment]
I have a PR https://github.com/microsoft/roosterjs/pull/331 to fix this issue.

You can also use the 4th parameter of this API to preserve all known attributes:

export default function clearBlockFormat(
    editor: Editor,
    tagsToUnwrap: string[] = TAGS_TO_UNWRAP,
    tagsToStopUnwrap: string[] = TAGS_TO_STOP_UNWRAP,
    **attributesToPreserve: string[] = ATTRIBUTES_TO_PRESERVE**
) {

**Comment by JiuqingSong** [comment]
Fixed in #331
