### ISSUE TITLE
Make `transformOnInitialize` default to true?

### ISSUE THREAD

**Issue by imWildCat** [microsoft/roosterjs#336]
**Describe the bug**
While using `initialContent` option, the `inDarkMode` does not work.

For example,
```ts
        let options: EditorOptions = {
            plugins: plugins,
            defaultFormat: defaultFormat,
            undo: this.props.undo,
            inDarkMode: true,
            initialContent: 'This will break dark mode',
        };
```

With colors:
```ts
    defaultFormat: {
        textColors: {
            lightModeColor: 'black',
            darkModeColor: 'white',
        },
        backgroundColors: {
            darkModeColor: 'black',
            lightModeColor: 'white',
        },
    },
```

**To Reproduce**
As specified above.

If we get rid of `initialContent` in the options, it can work.

**Expected behavior**
This will break dark mode' will show in dark mode.

**Screenshots**
The content shows in light mode.

**Device Information**
 - OS: macOS
 - Browser: Chrome 76 or Edge for Mac Version 77.0.230.2 (Official build) Dev (64-bit)

**Comment by Lego6245** [comment]
Modify the editior options block as follows:

```
let options: EditorOptions = {
            plugins: plugins,
            defaultFormat: defaultFormat,
            undo: this.props.undo,
            inDarkMode: true,
            initialContent: 'This will break dark mode',
            darkModeOptions: {
                     transformOnInitialize: true
            },
        };
```

Then it should work as expected. Arguably this should be the default option.
