### ISSUE TITLE
Ctrl+ArrowKeyLeft does not stop at beginning of text field on WIT form

### ISSUE THREAD

**Issue by bochong** [microsoft/roosterjs#362]
Holding down or hitting Ctrl+ArrowKeyLeft multiple times should stop at the beginning of a text field and not go further after it has navigated to the beginning of a text field. However in the rooster editor, if you press Ctrl+ArrowKeyLeft when at the beginning of the text field, it circles to the end of the text field.

**Comment by jessicaudo** [comment]
@JiuqingSong do you think you'll be able look into this bug? I learnt that it might require more than a simple UI fix
