### ISSUE TITLE
Add option to keep watermark until text is entered

### ISSUE THREAD

**Issue by daweffe** [microsoft/roosterjs#363]
**Describe the bug**
We would like the watermark text to work like placeholder text. When the field is clicked upon, the text stays visible until the user inputs text. This could be optional.

**To Reproduce**
1. Implement a roosterJs field with watermark text
2. Click on the text box

**Expected behavior**
The placeholder text should be visible still

**Screenshots**

**Additional context**
This is a PM ask for the new Project

**Comment by StephenArk30** [comment]
Check my plugin [here](https://github.com/StephenArk30/roosterjs/blob/placeholder_plugin/packages/roosterjs-editor-plugins/lib/plugins/Placeholder/Placeholder.ts).

**Comment by JiuqingSong** [comment]
> Check my plugin [here](https://github.com/StephenArk30/roosterjs/blob/placeholder_plugin/packages/roosterjs-editor-plugins/lib/plugins/Placeholder/Placeholder.ts).

Thanks. Would you like to submit your change into roosterjs?

**Comment by StephenArk30** [comment]
> > Check my plugin [here](https://github.com/StephenArk30/roosterjs/blob/placeholder_plugin/packages/roosterjs-editor-plugins/lib/plugins/Placeholder/Placeholder.ts).
> 
> Thanks. Would you like to submit your change into roosterjs?

Sure. But what this plugin does is totally different from the Watermark plugin. Should I replace the Watermark or keep them both?

**Comment by JiuqingSong** [comment]
> > > Check my plugin [here](https://github.com/StephenArk30/roosterjs/blob/placeholder_plugin/packages/roosterjs-editor-plugins/lib/plugins/Placeholder/Placeholder.ts).
> > 
> > 
> > Thanks. Would you like to submit your change into roosterjs?
> 
> Sure. But what this plugin does is totally different from the Watermark plugin. Should I replace the Watermark or keep them both?

How about create a new plugin, such as WatermarkV2?

**Comment by StephenArk30** [comment]
> > > > Check my plugin [here](https://github.com/StephenArk30/roosterjs/blob/placeholder_plugin/packages/roosterjs-editor-plugins/lib/plugins/Placeholder/Placeholder.ts).
> > > 
> > > 
> > > Thanks. Would you like to submit your change into roosterjs?
> > 
> > 
> > Sure. But what this plugin does is totally different from the Watermark plugin. Should I replace the Watermark or keep them both?
> 
> How about create a new plugin, such as WatermarkV2?

ok

**Comment by JiuqingSong** [comment]
#2503 Fixes this issue.
