### ISSUE TITLE
Allow Watermark text to be styled

### ISSUE THREAD

**Issue by daweffe** [microsoft/roosterjs#364]
**Describe the bug**
The watermark code has the option to accept a style parameter, but the rest of the code does not pipe it to 3rd party code as part of the API. We would like this option so we do not have to override the style with CSS "!important".

**Additional context**
This is an ask for code cleanliness in the new Project

**Comment by JiuqingSong** [comment]
Not quite understand about the ask. What do you mean by "the rest of the code does not pipe it to 3rd party code as part of the API.".

Watermark plugin accepts a format parameter so that you can customize. Let me know if that is sufficient

**Comment by daweffe** [comment]
Oh I see. Yes you can close this issue
