### ISSUE TITLE
Double tab being replaced with 2 spaces

### ISSUE THREAD

**Issue by bochong** [microsoft/roosterjs#366]
https://developercommunity.visualstudio.com/content/problem/731393/azure-devops-double-tab-replaced-with-two-spaces.html

When a user pastes in a code block, it replaces double tabs with 2 spaces. Single tabs work fine.

**Comment by JiuqingSong** [comment]
@bochong , would you please repro this bug in https://microsoft.github.io/roosterjs/index.html#event, then from the right pane, expand "BeforePaste" event and all its child nodes, then copy everything and paste here? This can help debugging.

Thanks.

**Comment by bochong** [comment]
Sure, here is the before paste event results: 
15:47:43.280 BeforePaste
Types=text/plain
Plain text
if found > 0 then error = error; error_message="test" return end if;
Sanitized HTML
<span>if found &gt; 0<br></span><div>then<br></div><div> error = error;<br></div><div> &nbsp;error_message=&quot;test&quot;<br></div><div>return<br></div><span>end if;</span>


This is the test I copied from notepad which has a double tab:
if found > 0
then
	error = error;
		error_message="test"
return
end if;

**Comment by bochong** [comment]
Heres a picture of the before paste results. Githubs comment thing keeps changing the html into just text. 
![image](https://user-images.githubusercontent.com/42078122/66965383-4fd48380-f02e-11e9-829d-e3fc47c46b40.png)

**Comment by JiuqingSong** [comment]
Ok, thanks for the info. I think I know the reason. I'll make a fix
