### ISSUE TITLE
When pasting multiple lines of text, it is always inserted on a new line regardless of the focus position.

### ISSUE THREAD

**Issue by wakame-isono** [microsoft/roosterjs#370]
**Describe the bug**

When pasting multiple lines of text, it is always inserted on a new line regardless of the focus position. If the text is a single line, it is inserted at the focus position.

**To Reproduce**

1. Go to [RoosterJs Demo Site v7.8.0](https://microsoft.github.io/roosterjs/index.html)
2. Write multiple lines of text
3. Copy them
4. Focus and paste in the middle of them

**Expected behavior**

Multiple lines of text is inserted at the focus position.

**Screenshots**

![Oct-25-2019 14-43-03](https://user-images.githubusercontent.com/30013568/67545920-cca1e480-f735-11e9-8b41-62abc0437d0c.gif)

**Device Information**

 - OS: macOS Mojava 10.14.6
 - Browser Chrome 77.0.3865.120

**Additional context**

Thank you for awesome library!!!!

**Comment by JiuqingSong** [comment]
Fixed in 8.0.0-beta.8
