### ISSUE TITLE
Links are inaccessible via keyboard 

### ISSUE THREAD

**Issue by spicioccio** [microsoft/roosterjs#375]
**Describe the bug**
Links can't be tabbed to via the keyboard and can't be clicked on using shift/enter.  They can only be verified when using the mouse.

**To Reproduce**
1. Go to https://microsoft.github.io/roosterjs/index.html 
2. Create a link. 
3. Attempt to use keyboard only to navigate to that link (using tab and arrow keys)
4. Now attempt to activate the link using keyboard only (Shift + Enter).

**Expected behavior**
Instead of taking the user to that link, the editor adds a line return instead.

**Device Information**
 - OS: Windows
 - Microsoft Edge 44.18362.449.0

**Comment by JiuqingSong** [comment]
This should be expected behavior. I didn't see other text editor has this behavior. Link under edit mode is not a real link, it is text looks like a link.

**Comment by spicioccio** [comment]
Even in edit mode, if you create a link and then hover over it, it provides the tooltip to "Ctrl + Click to follow the link".  Is there a way to navigate to the link without the mouse?

**Comment by JiuqingSong** [comment]
You can write a plugin or a "Content edit feature" to override the default behavior.

A content edit feature is an object to perform an action when user press a specified key under a specified condition:

https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-core/lib/interfaces/ContentEditFeature.ts

Then you can call editor.addContentEditFeature() to make it live.

https://github.com/microsoft/roosterjs/blob/87347deb12f179b95c3aa78ba99bc709fc1dae3f/packages/roosterjs-editor-core/lib/editor/Editor.ts#L917

**Comment by spicioccio** [comment]
Thanks, will give that a try.

**Comment by spicioccio** [comment]
Is it possible to use proposed solution above with LeanRooster?  Seems that LeanRooster contains an instance of the Editor and does not currently expose a way to add content edit features.
