### ISSUE TITLE
ToggleUnderline and ToggleStrikethough bug

### ISSUE THREAD

**Issue by iendeavor** [microsoft/roosterjs#382]
**Describe the bug**
When we use both function alternatively, we'll getthe bug.

**To Reproduce**
1. Call the `toggleUnderline`.
2. Type something in editor.
3. Call the `toggleStrikeThrough`.
4. Type something in editor.
5. Call the `toggleUnderline`.
6. Type something in editor (You'll see that the `U` not be updated, but real html is changed).
7. Call the `toggleUnderline` again (There will be no changes).

**Expected behavior**

**Screenshots**
https://youtu.be/xtpTwcE7mic

**Device Information**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by JiuqingSong** [comment]
Thans for reporting.
I can repro the issue with the step.
We'll investigate.

**Comment by JiuqingSong** [comment]
After investigation, I believe this is a bug of Chrome. I can repro with this page:

```html
<html>
<body>
<div contenteditable id=div1>
<strike><u><b>test</b></u></strike>
</div>
<button id=buttonBold>test bold</button>
<button id=buttonUnderline>test underline</button>
<script>
function test(command) {
    document.getElementById('div1');
    div1.focus();
    var before = document.queryCommandState(command);
    document.execCommand(command);
    var after = document.queryCommandState(command);
    console.log('Test for ' + command + ', Before=' + before + '; After=' + after);
}

window.onload=function() {
  document.getElementById("buttonBold").addEventListener('click', function() { test('bold'); });
  document.getElementById("buttonUnderline").addEventListener('click', function() { test('underline'); });
}
</script>
</body>
</html>
```

When click "test underline", it always says "before=true, after=true". But click "test bold" doesn't have this issue.

I have opened bug to Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1060276
So close this one.

Thanks for reporting.
