### ISSUE TITLE
Edit box allows tables, but can't properly edit them

### ISSUE THREAD

**Issue by sopgenorth** [microsoft/roosterjs#398]
Currently, the edit box for these forms/text boxes seems to support some form of copy/paste for rich-text tables. However, once the table is in the text box, it is not possible to edit as a table. Many pieces of data are much better represented in a table than as a list or other means and can be much faster to visually parse.

It would be a great addition if this text box could support basic table operations (create an n-by-m table, add/delete columns and rows, merge cells, etc.).

**Comment by JiuqingSong** [comment]
![image](https://user-images.githubusercontent.com/23065085/77499179-9ebceb00-6e0e-11ea-9054-230455273c17.png)

We have API to edit table, please see the screenshot of demo site, and the API reference here about these APIs: https://microsoft.github.io/roosterjs/docs/modules/roosterjs_editor_api.html#edittable
