### ISSUE TITLE
Wrong Dom Element of InsertContent

### ISSUE THREAD

**Issue by Irelylnny** [microsoft/roosterjs#428]
**Describe the bug**
I want to insert something at the end of some element,

**To Reproduce**
1. open Chrome - go to demo page
2. open google dev tool
3. input code 
```
window.globalRoosterEditor.insertContent("test2")
window.globalRoosterEditor.insertContent("test4",{position:1}
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/11981186/84346649-08b18900-abe3-11ea-91ec-5d32cd747b6c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/11981186/84346700-28e14800-abe3-11ea-8fc7-c8ff72b52b1d.png)

**Device Information**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [7.12.1]

**Additional context**
In v7.7.0 we can get the expected behavior.

**Comment by JiuqingSong** [comment]
You need to use the same insert option for the two inserts too ensure they are inserted into the same position.
