### ISSUE TITLE
`checkXss` creates an unexpected href for subsequent checks in `createLink`

### ISSUE THREAD

**Issue by dps88** [microsoft/roosterjs#438]
**Describe the bug**
checkXss creates an unexpected href for the subsequent attempts to normalize the url.  
![image](https://user-images.githubusercontent.com/50461997/85443204-d50d2200-b545-11ea-83ff-97aa9da3c4ff.png)

In most cases, if the protocol is not supplied, this line creates an href with the current protocol/domain with the link from the caller appended 
![image](https://user-images.githubusercontent.com/50461997/85443784-8318cc00-b546-11ea-979c-f9b9d032ea93.png)

**To Reproduce**
Pass any string without a host eg: `'google.com'`

**Expected behavior**
resulting url to `'https://www.google.com/'`

**Comment by JiuqingSong** [comment]
Which browser and version does this happen in? I tried in Chrome  83.0.4103.116 and I can still get the original string "google.com" for the variable "url"

**Comment by dps88** [comment]
I'm seeing it happen in :
- Edge 83.0.478.61
- Firefox 77.0.1
- Chrome 83.0.4103.116


running 108-110 in the various browsers' dev consoles has the same issue as far as I can tell.

![image](https://user-images.githubusercontent.com/50461997/87102102-bd9c8d00-c205-11ea-9cab-30b0dedb78e0.png)

**Comment by JiuqingSong** [comment]
Please see the latest code of createLink.ts: https://github.com/microsoft/roosterjs/blob/a5e246b3a19509d82d5542014c5db840cda0bacb/packages/roosterjs-editor-api/lib/format/createLink.ts#L122

```ts
function checkXss(link: string): string {
    const santizer = new HtmlSanitizer();
    const doc = new DOMParser().parseFromString('<a></a>', 'text/html');
    const a = doc.body.firstChild as HTMLAnchorElement;

    a.href = link || '';
    santizer.sanitize(doc.body);
    // We use getAttribute because some browsers will try to make the href property a valid link.
    // This has unintended side effects when the link lacks a protocol.
    return a.getAttribute('href');
}
```

It is using "a.getAttribute('href'); here instead of "a.href". They will return different thing.

**Comment by dps88** [comment]
@JiuqingSong Ah, thanks for pointing that out.  We had attempted to update the rooster packages, but our package-lock.json was still running some dated versions.  Running `npm i <rooster-packages>@latest` properly updated the package and fixed the issue.
