### ISSUE TITLE
KeyboardEvent.key is not supported in WebView version below 51

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#439]
**Describe the bug**
The mention functionality in Outlook Android does not work properly in WebView version below 51. 

The root cause is _[PickerPlugin](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts)_ uses `event.rawEvent.key == UNIDENTIFIED_KEY` to identify events on Android. However, in the low version of WebView, the 'key' property of KeyboardEvent is not supported and always returns 'undefined'. So the `shouldHandleKeyUpEvent()` function always returns false and we don't know the`@` character is inputted.

Besides the 'key' property, can we also use 'keyCode', 'which' or 'charCode' property to identify Android? These properties are supported in the low version of WebView and the values of them seem to be 0 on Android.

<img width="211" alt="WX20200629-191030@2x" src="https://user-images.githubusercontent.com/67583056/85998173-0baed500-ba3d-11ea-8d74-339e216d926c.png">

**To Reproduce**
1. Open Outlook Android in a device with low version of WebView
2. Click 'New Message' button
3. Input '@' in message body
4. See the popup window does not appear.

**Expected behavior**
The popup window should appear after inputting '@'.

**Device Information**
 - OS: Android 6.0
 - Browser: WebView
 - Version: 7.12.1

**Comment by JiuqingSong** [comment]
#446
