### ISSUE TITLE
Paste (insertNode) under B/I/U tag causes the inserted content has B/I/U style

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#456]

**Comment by huahuahu** [comment]
Hi, any updates?

**Comment by JiuqingSong** [comment]
This needs a large redesign about how we handle the B/I/U tags. It is in our plan but may not happen very soon.
A workaround will be having a plugin to handle BeforePasteEvent, and split existing B/I/U tags if any, then put cursor out of those tags, so that pasting will work correctly in most cases. But in case B/I/U is put outside of a block node (e.g. DIV), there will still be issue.

**Comment by BryanValverdeU** [comment]
This should be fixed with

Experimental Feature: Paste with content model
