### ISSUE TITLE
No way to exit code editing

### ISSUE THREAD

**Issue by jbrown1618** [microsoft/roosterjs#457]
**Describe the bug**
When editing code text, there is no way to exit and enter non-code text below unless there is already non-code text below.

**To Reproduce**
1. Go to the [RoosterJs Demo Page](https://microsoft.github.io/roosterjs/index.html)
2. Click on the "Code block" button
3. Focus the textarea and enter some text
4. From here, try various ways to exit
    a. Enter two line breaks; new text will still be part of the code block
    b. Hit alt+Enter or ctrl+Enter or Shift+Enter; new text will still be part of the code block
    c. Press ArrowDown; new text will still be part of the code block
    d. Click on the "Code block" button again; the entire code block will change to normal text
    e. Click on the whitespace below the code block; nothing happens

**Expected behavior**
There should be some way to exit the code block with the keyboard. Some editors will exit on two consecutive blank lines at the end. Others will exit on alt+Enter or similar.

**Device Information**
 - OS: Windows 10
 - Browser: chrome version 84.0.4147.89
 - RoosterJs Demo Site v7.14.1

**Additional context**
This bug came up through a feedback ticket on Azure DevOps

**Comment by JiuqingSong** [comment]
Thanks. This is a valid issue.

**Comment by danhellem** [comment]
@JiuqingSong do you know if you will pick this up and resolve in the near future?

**Comment by JiuqingSong** [comment]
@danhellem may not be very soon. You can build a ContentEditFeature to exit the CODE tag when press ENTER, the similar behavior with BLOCKQUOTE. Please reference to https://github.com/microsoft/roosterjs/blob/dc15c09002e362684c4e5d045c2f865d13e76758/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/quoteFeatures.ts#L32
Then add it into editor by either [Editor.addContentEditFeature](https://github.com/microsoft/roosterjs/blob/dc15c09002e362684c4e5d045c2f865d13e76758/packages/roosterjs-editor-core/lib/editor/Editor.ts#L1004) or [EditorOptions.additionalEditFeatures](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-core/lib/interfaces/EditorOptions.ts#L59)

**Comment by jbrown1618** [comment]
@JiuqingSong thanks for the suggested workaround - something similar worked great for us.

We made it so that if the user hits Enter while on a blank line at the end of a code block, it will insert a new line outside the code block and place the cursor there.  Shift+Enter adds a new line inside the code block as usual.

**Comment by JiuqingSong** [comment]
Greate to hear, @jbrown1618 . Would you like to contribute your code back to roosterjs? So that other people can also be benefited. 

Thanks.

**Comment by jbrown1618** [comment]
That's a good idea - I've put it on my to-do list

**Comment by JiuqingSong** [comment]
I'll close this issue for now. @jbrown1618 if you have your change ready please feel free to submit a PR.
