### ISSUE TITLE
Support for formatting in Microsoft flow

### ISSUE THREAD

**Issue by iukea1** [microsoft/roosterjs#459]
Hello,

Would it be possible to get support for this in Microsoft flow?

My current use case is
- I do a HTTP post requests to Microsoft flow of a json object.

I then use MSflow to parse the json objects and then have it create Azure DevOps tickets.

My current issue is there is no way to actually format the text in the Description field  through MSflow or the Azure DevOps API. 

Keep up the good work guys :)

**Comment by JiuqingSong** [comment]
Hi, I'm actually not quite understand the issue. Could you please provide more details? (Screenshots, code, ...)

**Comment by M-050** [comment]
Mm
