### ISSUE TITLE
Feature Request: Ability to toggle "word wrap"

### ISSUE THREAD

**Issue by hoovercj** [microsoft/roosterjs#463]
It does not seem like it is currently possible to toggle "word wrap" so that content on each line does not wrap to a new line and instead the editor would overflow and scroll horizontally.

Do you have suggestions on how we could add that as consumers of the editor?

Otherwise, please consider adding this capability directly to the editor itself.

**Comment by JiuqingSong** [comment]
You just need to add some CSS styles to your DIV for roosterjs to force it not wrap:

![image](https://user-images.githubusercontent.com/23065085/89087178-3d6ed080-d348-11ea-9382-325fc1db79ed.png)

**Comment by hoovercj** [comment]
@JiuqingSong oh great, that will definitely meet our needs.

Thanks!
