### ISSUE TITLE
Blockquote does not preserve formatting when copy/pasted

### ISSUE THREAD

**Issue by stkillen** [microsoft/roosterjs#466]
**Describe the bug**
The formatting of the blockquote is not preserved when copy/pasted elsewhere.

**To Reproduce**
1. In the editor, make a blockquote
2. Copy it
3. Paste it to Word/OneNote/Outlook
4. Formatting of the blockquote is not preserved

**Expected behavior**
The formatting of the blockquote is preserved when copy/pasted elsewhere.

**Screenshots**
In RoosterJS editor:
![image](https://user-images.githubusercontent.com/65776111/89988572-08d01280-dc80-11ea-9365-cebe9d289972.png)

When pasted to Word:
![image](https://user-images.githubusercontent.com/65776111/89988597-17b6c500-dc80-11ea-8eff-e7998c2297b3.png)

**Device Information**
 - OS: Windows
 - Browser: Edge Chromium

**Comment by JiuqingSong** [comment]
This is not a bug of roosterjs because if you paste into somewhere else, blockquote can be preserved. Word explicitly remove the blockquote.
