### ISSUE TITLE
Custom implementation for toggleUnderline

### ISSUE THREAD

**Issue by zhuorantan** [microsoft/roosterjs#482]
Currently, here is a bug (or expected behavior?), in both Chrome and WebKit, that the underline state is not correctly reflected. The bug is detailed in [this issue](https://github.com/microsoft/roosterjs/issues/382).

The `toggleUnderline` method uses `document.execCommand` and now [it is obsolete and discouraged to use](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). Can roosterjs implement the `toggleUnderline` method without `document.execCommand` to avoid this issue?

**Comment by JiuqingSong** [comment]
need content state support

**Comment by JiuqingSong** [comment]
#1410
