### ISSUE TITLE
Does this editor has read only mode

### ISSUE THREAD

**Issue by raoshahid799** [microsoft/roosterjs#502]
Hi 
   Does this editor has read-only mode ? can we show the content of this editor without edit option ?  i searched on internet but i did not find any solution

**Comment by JiuqingSong** [comment]
To make it readonly, you just need to simply dispose the editor object:
```ts
editor.dispose();
```

and To make it editable again, create a new editor object:
```ts
editor = new Editor(div, ...);
```
