### ISSUE TITLE
Incorrect cursor rect after newline

### ISSUE THREAD

**Issue by Yat3s** [microsoft/roosterjs#509]
**Describe the bug**
Incorrect cursorRect after a newline

**To Reproduce**
1. Input a character, check `getCursorRect()`
2. Tap newline
3. Check cursorRect 

**Expected behavior**
CursorRect should be a new value instead old value after newline

**Screenshots**
It same as this issue:
https://stackoverflow.com/questions/59767515/incorrect-positioning-of-getboundingclientrect-after-newline-character

**Device Information**
 - OS: Android 10
 - Browser: Android WebView
 - Version: API 29
 - Roosterjs Version: 7.16.0

**Additional context**
This line should have work after newline, so I guess something wrong when `createRange` 
![image](https://user-images.githubusercontent.com/14801837/105278455-7e9dba00-5be0-11eb-9274-01678c3a2fe5.png)

**Comment by JiuqingSong** [comment]
Thanks for reporting this issue.
If you have a local fix, you are always welcome to contribute your fix back into roosterjs.

**Comment by JiuqingSong** [comment]
Close old issues
