### ISSUE TITLE
Please add markdown support

### ISSUE THREAD

**Issue by KirkMunro** [microsoft/roosterjs#511]
**Describe the bug**
This was requested over two years ago in #130, but you had no plans for markdown then.

This editor in ADO is very buggy, and quite difficult to work with.

I don't want to waste time identifying those bugs any more than I want to waste time dealing with and editor that thinks it knows how I want my work item text formatted.

Markdown is a productivity booster. If you had markdown support, I'd know exactly what I was going to get from the markdown syntax in any work items that I create in ADO. Without it, I'm futzing around with an editor that is getting in the way of other work I want to be doing and hampering productivity.

**To Reproduce**
1. In Azure DevOps, create a new work item.
2. In the work item description editor, try creating multi-level numbered lists, where the nested list items also contain paragraphs of text, code blocks and other details.
3. Once you have done that, save the work item. Then come back and edit your description, inserting additional numbered sub-items with additional text, removing another item, and use Shift+Enter a lot to get the output to appear the way you want (as text that continues beyond the nested numbered item).

**Expected behavior**
This should be easy, but not using a "rich" editor. Just provide markdown support in this editor that allows me to work in Markdown and see the rendered view, like we get in VS Code and other modern editing environments. It will allow me and others to know what we're going to get, every time.

**Device Information**
 - OS: Windows 10
 - Browser: Edge Chromium
 - Version: Not sure, latest as of today, it's on the other system where I work with Azure DevOps that I'm away from right now.

**Additional context**
None

**Comment by JiuqingSong** [comment]
Markdown is partially supported from 7.15.0. See #461 .

To use it, add ContentEdit plugin and markdown features will be added by default.

About multiple list, we now have our own implementation which will overwrite browser's one. To enable it, pass "enableExperimentFeatures: true" in editor options:

```ts
let options: roosterjs.EditorOptions = {
    plugins: plugins,
    enableExperimentFeatures: true,
};
let editor = new roosterjs.Editor(contentDiv, options);
```

In coming days we will put this implementation as default and deprecate the browser's one.

**Comment by KirkMunro** [comment]
I appreciate you guys putting some effort into markdown; however, that markdown support is really quite terrible. Teams is what I would consider a poor example of how to add markdown to a web UI, for a number of reasons:

1. By auto-converting numbered lists as you type, it discards the benefit of using one-dot numbering for all lists (including nested lists).
2. It does not support international keyboard layouts well where the backtick requires multiple keystrokes because it is used to apply accent grave to other letters (I use a Canadian French keyboard layout).
3. Multi-line code blocks do not appear to be properly supported (maybe because of the keyboard layout that I use?).

I think this is also the wrong approach because you're putting users who don't know markdown and want a rich text editor into the same bucket as users who know markdown really well and can be very effective with it, and really don't want a rich text editor. Look at GitHub if you want a better example for markdown folks. I'm typing this comment in markdown, and I know immediately what it will look like, yet if there is any doubt I can flip over to the preview tab. I can still use shortcuts for **bold** and _italics_, but I don't need to if I don't want to. The "rich" functionality of the editor is available to me but stays out of my way.

Anyway, I don't mean to sound like I don't appreciate the effort. I do. I just think the direction you chose isn't the right way to solve this problem. From my perspective, it feels like a wasted effort because it doesn't get me any closer to what I'm after. In fact, it does the opposite and adds more frustration to the editing experience by trying to do markdown, but doing it very, very poorly.

**Comment by JiuqingSong** [comment]
Thanks for your comment. It seems what you are looking for is a VSCode/github style markdown support: write in plain text, then view it in rich format, is that right?

Unfortunately, that beyonds the goal of roosterjs. RoosterJs focus on WYSIWYG HTML editing, it only handles the editing-time rich format support. For convert markdown to rich format during view-time, that should be down by some other library becuase that has nothing to do with editing. You may want to look for some perticular library for markdown converting, but not during editing. During editing ther can be some kind of mark down support such as when you press a "Bold" button we convert the highlighted text with "*", but that is not something a HTML editor should do. Otherwise, how can we know if user really want to type something with "*" around or user just want to bold it? 

An editor can be either plaintext+markdown, or WYSIWYG HTML rich format, but it should do them at the same time in the same editor. RoosterJs focus on latter.

**Comment by KirkMunro** [comment]
> Thanks for your comment. It seems what you are looking for is a VSCode/github style markdown support: write in plain text, then view it in rich format, is that right?

Maybe. I would happily work with that. I also really like the Typora.io markdown editing experience as well though, where you are always presented with the rich format that converts to markdown inline in the right location as you edit it. Either approach would do.

> Unfortunately, that beyonds the goal of roosterjs. RoosterJs focus on WYSIWYG HTML editing, it only handles the editing-time rich format support

Fair point. I came here after reading a blog post from 2018 advertising this editor being adopted in Azure DevOps, and suggesting we carry feedback into here, but since you are focused on WYSIWYG HTML it makes sense that I'll have to carry my request elsewhere to see if I can get a better markdown editing experience in Azure DevOps.

> For convert markdown to rich format during view-time, that should be down by some other library becuase that has nothing to do with editing. You may want to look for some perticular library for markdown converting, but not during editing. During editing ther can be some kind of mark down support such as when you press a "Bold" button we convert the highlighted text with `*`, but that is not something a HTML editor should do. Otherwise, how can we know if user really want to type something with `*` around or user just want to bold it?
> 
> An editor can be either plaintext+markdown, or WYSIWYG HTML rich format, but it should not do them at the same time in the same editor.

I understand your perspective but I don't entirely agree with you on this point. Look at Typora.io. It provides a markdown editor with inline rendering into rich text format. You want asterisks on your text without them being recognized as markdown bold enclosures? Escape them.

At any rate, that is not your mandate with RoosterJs, so I'll figure out where else I need to go to lobby for the functionality I feel should be there.

Thanks a bunch for taking the time to discuss this with me @JiuqingSong.

**Comment by Merlin2001** [comment]
@KirkMunro Any chance you found a better place to voice (y)our wish to improve AZD markdown support? I'd love to add my +1 there as I have exactly the same wish and can't understand why pull request descriptions and comments support markdown perfectly but backlog items don't :/

**Comment by KirkMunro** [comment]
@Merlin2001: Vote this up: https://developercommunity.visualstudio.com/t/Markdown-support-in-work-items/938805?space=21&q=Markdown.

**Comment by Merlin2001** [comment]
Thank you, perfect! I also just found another related suggestion that even has the status "Under Review":  
[Support markdown as an alternative to html for workitems](https://developercommunity.visualstudio.com/t/support-markdown-as-an-alternative-to-html-for-wor/365464)
