### ISSUE TITLE
Space key doesn't trigger the auto link feature in Android WebView

### ISSUE THREAD

**Issue by Foolment** [microsoft/roosterjs#513]
**Describe the bug**
In Android WebView, entering a space character doesn't trigger the auto link feature to make the text into link format.

**To Reproduce**
1. Type some text that match the link format, like: www.test.com
2. Type a space
3. The text doesn't turn into the link form.

**Expected behavior**
The text should turn into the link form.

**Screenshots**
![autolink](https://user-images.githubusercontent.com/3321518/105974795-380cfb80-60c9-11eb-9709-74795fefcfef.gif)

**Device Information**
 - Device: Pixel 3a emulator
 - OS: Android API 29
 - WebView: 74.0.3729.185

**Additional context**
![image](https://user-images.githubusercontent.com/3321518/105976220-dea5cc00-60ca-11eb-9726-d04a0fba1c34.png)
After we input a space, the keyCode for this `KeyboardEvent` is `229` not the `32`, so RoosterJs can't dispatch it to the [`autoLinkFeature`](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/autoLinkFeatures.ts).
From this documentation: [keyCode property of key events](https://lists.w3.org/Archives/Public/www-dom/2010JulSep/att-0182/keyCode-spec.html), `229` indicates an Input Method Editor is processing key input and the event is keydown.
Some discussions I found:
1. [Issue 118639: keydown and keyup events do not have proper keyCode (it's always 0)](https://bugs.chromium.org/p/chromium/issues/detail?id=118639)
2. [KeyDown event always returns KeyCode 229](https://social.msdn.microsoft.com/Forums/en-US/d9ac5d52-55f5-4e8f-b074-22323834a09c/keydown-event-always-returns-keycode-229?forum=vssmartdevicesvbcs)
3. [onKeyDown code not working on android mobile browsers](https://github.com/nosir/cleave.js/issues/147)

**Comment by JiuqingSong** [comment]
Thanks for reporting this issue.
If you have a local fix, you are always welcome to contribute your fix back into roosterjs.

**Comment by JiuqingSong** [comment]
Close old issues
