### ISSUE TITLE
Table cannot be centered 

### ISSUE THREAD

**Issue by danvln** [microsoft/roosterjs#516]
Table cannot be centered 

**To Reproduce**
1. Create a table using the table plugin
2. Try to center the table 
3. I am using the latest package: 8.1

**Expected behavior**
I was expecting for the table to be centered, however the table is not centered.

**Device Information**
 - OS: Windows 
 - Browser: chrome
 - Version:99+ (green)

**Additional context**
Even if the cursor is centered, when a new table is added then the table is inserted on the left.
This problem probably could be addressed with having another plugin that creates a div that's centered, and add the table into it, but is seems as a hack.

**Comment by JiuqingSong** [comment]
This is a planned feature.

**Comment by juliaroldi** [comment]
Feature added. See [PR 608](https://github.com/microsoft/roosterjs/pull/608)
