### ISSUE TITLE
AutoBullet: Extra leading space on Mobile Safari

### ISSUE THREAD

**Issue by imWildCat** [microsoft/roosterjs#532]
**Describe the bug**

**To Reproduce**
1. Type "-" and a space to trigger auto list behavior
2. Observe whether an extra space is added

**Expected behavior**

No extra space should be added before the leading of a list content

**Screenshots**

![IMG_7009ED481EFA-1](https://user-images.githubusercontent.com/2396817/114831149-a11a2a80-9dff-11eb-90c8-8b9f10aa9359.jpeg)

(video is also attached)

https://user-images.githubusercontent.com/2396817/114831365-e2aad580-9dff-11eb-858f-4bc7832ea6de.MP4

**Device Information**
 - OS: iOS 14.x
 - Browser: Mobile Safari
 - Version: 14.x

**Additional context**

**Comment by JiuqingSong** [comment]
It seems iOS safari has different implementation for async functions like setTimeout/requestAnimationFrame, that causes this result. Looks like we make need a different way to do async operation for iOS Safari, or avoid using async operation.

**Comment by JiuqingSong** [comment]
I have a PR to fix this issue #545

**Comment by imWildCat** [comment]
@JiuqingSong awesome, thank you!

**Comment by imWildCat** [comment]
Thanks a lot! I can confirm the fix!


https://user-images.githubusercontent.com/2396817/118211086-23991700-b49e-11eb-960e-d63922adc0b0.MP4
