### ISSUE TITLE
document.execCommand is deprecated

### ISSUE THREAD

**Issue by naveenakadaba** [microsoft/roosterjs#541]
Thanks for bringing out such a wonderful editor.

I was going through the source code and found that the package is using **document.execCommand**. But as per the current web standards it has been removed or in the process of being removed.

As per MDN Web Docs
**This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.**

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

Instead of execCommand, selection api should be used
https://developer.mozilla.org/en-US/docs/Web/API/Selection

**Comment by JiuqingSong** [comment]
Thanks, this is known and planned.

**Comment by naveenakadaba** [comment]
Hey! thanks for the reply. Is it planned anytime soon?

**Comment by JiuqingSong** [comment]
It's hard to say. This may not happen very soon.

**Comment by JiuqingSong** [comment]
need content state support
