### ISSUE TITLE
Demo project: Image is inserted inside of the anchor element

### ISSUE THREAD

**Issue by Yat3s** [microsoft/roosterjs#551]
**Describe the bug**
Images are inserted inside of the anchor element

**To Reproduce**
1. Insert link
2. Insert an image next to the link
3. Inspect element

**Expected behavior**
Should be on the outside of anchor

**Screenshots**
I can repro it on the local demo:
![2](https://user-images.githubusercontent.com/14801837/118465755-c7035980-b734-11eb-9c81-70f20bc974f3.png)

But I can't repro on the production demo:
![1](https://user-images.githubusercontent.com/14801837/118465777-ccf93a80-b734-11eb-90ad-9d1772a59936.png)

**Device Information**
 - OS: macOS
 - Browser Chrome
 - Version

**Comment by juliaroldi** [comment]
Bug fixed. See [PR 598](https://github.com/microsoft/roosterjs/pull/598)
