### ISSUE TITLE
document.queryCommandState('underline') always return true

### ISSUE THREAD

**Issue by Wanjing-Li** [microsoft/roosterjs#557]
**Describe the bug**
Open rooster sample website in Safari, tap `Underline` button and write some texts, then deselect the `Underline` button, the button still highlighted. After inputing some texts again, the highlight disappeared.

**To Reproduce**
1. Open rooster sample website in Safari
2. Click on `underline` button, the button highlighted
3. type some texts
4. Click on `underline` button, the button still highlighted
5. type some texts, `underline` button highlight disappeared

**Expected behavior**
In step4, the underline button should be canceled the highlight status.

**Device Information**
 - OS: macOS Big Sur v11.3.1, iOS 14.4
 - Browser :  Safari(reproduce 100%) Chrome(randomly reproduce)
 - Version : Safari 14.1, Chrome v90.0.4430.212

**Additional context**
Deep dive in Rooster.js, the `format state` for `underline` doesn't change. 
Then I tried to create a html and write these code in Console:
```
document.body.contentEditable = true;
document.body.innerHTML=" ";

document.execCommand("Underline", false, "");
document.execCommand("insertText", true, document.queryCommandState('underline'));

document.execCommand("Underline", false, "");
document.execCommand("insertText", true, document.queryCommandState('underline'));

```
The result is:
![image](https://user-images.githubusercontent.com/11981186/119468784-5afaa400-bd79-11eb-9bc4-326bcd4aa3e4.png)

I guess it's a Webkit bug, any ideas? @JiuqingSong

**Comment by Wanjing-Li** [comment]
BTW, I noticed [Document.execCommand()](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) and [Document.queryCommandState()](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandState) are deprecated, does Rooster.js have plan to refactor this?

**Comment by JiuqingSong** [comment]
This is a known Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1060276

**Comment by JiuqingSong** [comment]
There is plan to remove execCommand(), but no timeline yet.

**Comment by Wanjing-Li** [comment]
Seems it's won't be fixed as we expected, could Rooster.js maintain the status by self instead of checking `commandState` as workaround?

**Comment by Wanjing-Li** [comment]
BTW,  there is no hover behavior on mobile thus in sample page, the css `:hover` won't be canceled after clicked those ribbon buttons. https://github.com/microsoft/roosterjs/blob/cc88ee3110b6b4966f02ed0be6498a1956e8fe6a/demo/scripts/controls/ribbon/RibbonButton.scss#L10

**Comment by JiuqingSong** [comment]
Thanks for point this out. Would you like to make a fix?

For query commmand state, once we can implement our own editing command, it will be implemented together

**Comment by Wanjing-Li** [comment]
Do we have the requirement of lowest browser version? I think this is the solution for `:hover`:https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover

**Comment by juliaroldi** [comment]
Bug fixed. See [PR 607](https://github.com/microsoft/roosterjs/pull/607)
