### ISSUE TITLE
What browsers and devices does roosterjs support?​

### ISSUE THREAD

**Issue by HereSinceres** [Microsoft/roosterjs#56]
What browsers and devices does roosterjs support?​

**Comment by HereSinceres** [comment]
Can it be used in a production environment? What are the products that use roosterjs?

**Comment by JiuqingSong** [comment]
RoosterJs supports Edge 16+, IE 11, latest build of Chrome, Firefox and Safari. RoosterJs can also work on other browsers but it is not guaranteed. It is used by outlook.com, and some other projects.

**Comment by HereSinceres** [comment]
thx.
What made it does not support ie 9? I need to support ie 9 ^_^. The mobile support？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JiuqingSong** [comment]
This project is not well tested on IE 9. You can still use it on IE 9 with risk. And if you find any bug there, you are still welcome to report it, and we will fix them accordingly, at least avoid crashing your app.

Safari and Chrome on mobile is also supported, and I know we have customer working on integrating this project into their mobile app.

**Comment by HereSinceres** [comment]
thx，^ _ ^。  ^ - ^

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
