### ISSUE TITLE
Cannot deselect image with ImageResize plugin

### ISSUE THREAD

**Issue by braidenstiller** [microsoft/roosterjs#576]
**Describe the bug**
When pasting in an image, if you select it and try and unselect it the Resize plugin throws the following error:
![image](https://user-images.githubusercontent.com/8955294/124379285-6f777800-dcf9-11eb-9704-ec454911804b.png)

ImageResize plugin configured with defaults:
![image](https://user-images.githubusercontent.com/8955294/124379346-ce3cf180-dcf9-11eb-946a-5d56a48fdca4.png)

Resize handles render correctly:
![image](https://user-images.githubusercontent.com/8955294/124379396-14925080-dcfa-11eb-882b-0c9a803b9dc5.png)

Additionally, after the error appears, the left-most top and bottom handles no longer resize the image.

**To Reproduce**
1. Paste image from clipboard
2. Select image
3. Try and deselect image

**Expected behavior**
For the image to deselect and resize correctly.

**Device Information**
 - OS: Windows 10
 - Browser Chrome - 91.0.4472.124
 - Version v8.4.0

**Comment by braidenstiller** [comment]
Digging further the reason for this is because of the improper use of .length in the ImageResizeHandler.prototype.hideResizeHandles.

.Length is returning a count of 3 but the array may only have 2 due to the way Step is computed in ImageResizeHandler.prototype.createWrapper. The iterator for the hide function should probably implement the step function similar to how it's generated.

![image](https://user-images.githubusercontent.com/8955294/124403854-b27a2f80-dd7b-11eb-8046-30f0fbc5c150.png)

**Comment by braidenstiller** [comment]
Yep.
Further testing revealed this is #575

**Comment by JiuqingSong** [comment]
The change is merged.
