### ISSUE TITLE
New line after heading does not restore default style

### ISSUE THREAD

**Issue by braidenstiller** [microsoft/roosterjs#580]
**Describe the bug**
When creating a new line after heading, a new div is created but the default style is not applied.

**To Reproduce**
1. Create default style options with fontSize: '11pt' and fontFamily: 'Lato'
2. Write text one one line, style it with a header level (any will do)
3. Create a new line and write text. Newly created text will not have default style applied.

**Expected behavior**
For the default style to applied to new text after headers, just like on other new line text.

**Screenshots**
![image](https://user-images.githubusercontent.com/8955294/125235500-e75f2700-e325-11eb-99a7-1b06443ad3e5.png)

![image](https://user-images.githubusercontent.com/8955294/125235543-fb0a8d80-e325-11eb-956f-e7e0c4b8facd.png)

**Comment by juliaroldi** [comment]
Bug fixed. See [PR 591](https://github.com/microsoft/roosterjs/pull/591).
