### ISSUE TITLE
Support Trusted Types

### ISSUE THREAD

**Issue by shhnjk** [microsoft/roosterjs#581]
**Describe the bug**
RoosterJS is not usable in a webpage which has [Trusted Types](https://web.dev/trusted-types/) enforcement.
For example, there are many [_innerHTML_](https://github.com/microsoft/roosterjs/search?q=innerHTML+-filename%3Atest+-path%3Ademo) usage. Those `innerHTML` usage needs migration to safer practices (e.g. `textContent`, sanitization before assignment to `innerHTML`).

**To Reproduce**
1. Enforce Trusted Types on a page (i.e. `<meta http-equive="Content-Security-Policy" content="require-trusted-types-for 'script';">`).
2. Load RoosterJS on the page and observe that RoosterJS won't work.

**Expected behavior**
RoosterJS should be compatible with Trusted Types.

**Device Information**
 - OS: Windows 10
 - Browser: Chrome/Edge
 - Version: 91

**Comment by JiuqingSong** [comment]
Thanks for open this bug.
We need to plan for this one.

**Comment by shhnjk** [comment]
As [commented](https://github.com/microsoft/roosterjs/pull/602/files#r684402448) you don't have to create `sanitizeHtml` policy. DOMPurify already [creates a policy](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L54) within the library to return _TrustedHTML_ after sanitization.

**Comment by JiuqingSong** [comment]
> As [commented](https://github.com/microsoft/roosterjs/pull/602/files#r684402448), you don't have to create `sanitizeHtml` policy. DOMPurify already [creates a policy](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L54) within the library to return _TrustedHTML_ after sanitization.

Thanks for the comment. The related code is used by demo site only, but not in production. You will not get it from any npm package.
