### ISSUE TITLE
getFormateState API changes?

### ISSUE THREAD

**Issue by Yat3s** [microsoft/roosterjs#631]
**Describe the bug**
getFormateState()  return the format state of the whole dom instead of content.

**To Reproduce**
```
<div id="text1">
   <strong>Content</strong>
</div>

...
const element = document.querySelector('#text1');
const range = document.createRange();
range.selectNodeContents(element);
document.getSelection().removeAllRanges();
document.getSelection().addRange(range);

...
const format = getFormateState();
```

<=8.7.0:  
`format.isBold => true`

8.8.0:  
`format.isBold => false`

I didn't saw any change log for this API, is it regression or by design?

**Comment by JiuqingSong** [comment]
Thanks for reporting this issue. It sounds like a regression. @juliaroldi  please take a look.

BTW, suggest use editor.select() instead of getSelection().addRange() so that editor can know that the selection is changed.

**Comment by juliaroldi** [comment]
Bug fixed. See [PR 639](https://github.com/microsoft/roosterjs/pull/639)
