### ISSUE TITLE
Use `export enum` instead of `export const enum`

### ISSUE THREAD

**Issue by mjrjoh** [microsoft/roosterjs#641]
Hi, I have run into a problem about `roosterjs-editor-types` package. It seems not to be able to import and use some enums which exported with `export const` if the project typescript complier has an `isolatedModules` option.

Here is the reference about the conflict of `isolatedModules` option and `const enum`. https://ncjamieson.com/dont-export-const-enums/

I wonder if it makes sense to refactor `export const enum` to `export enum`. Thanks a lot!

**Comment by JiuqingSong** [comment]
Using of enum without const will cause bundle size increasing, and it will impact all customers. So for now we will not consider using enum without const.

**Comment by sverrejoh** [comment]
This prevents the package to be consumed by some tools, such as Babel, esbuild and swc. FluentUI and many other project are moving away from const enums.

If you're concerned about bundle size you can move towards using string literal unions instead of const enums.

**Comment by sverrejoh** [comment]
Also note that the TypeScript team does not recommend using const enums in your external interface. The const enum pitfalls is described here: https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls
