### ISSUE TITLE
getContent includes color and css attributes from ancestors for the RoosterJs editor 

### ISSUE THREAD

**Issue by Samigirma1** [microsoft/roosterjs#671]
**Describe the bug**

`html` returned by `getContent` (with default arguments) contains tags with class names from ancestor components of the Editor.

**To Reproduce**
1. Navigate to component containing a rooster editor. Take note of the class names of ancestor tags (divs, sections, etc...)
2. Modify content of the editor
3. call `Editor::getContent` for the editor and log its return value.
4. Look for `html` tags containing class names used by at least one of the editors ancestors and not assigned by the editor and its plugins.

**Expected behavior**
All attributes in tags returned by `getContent` should only contain attributes/props defined by the editor and its plug-ins
```html
<meta ...></div><div></div><div></div><div role="textbox"><b>Donda</b> is better than CLB</div>
```
**Actual behavior**
Additional attributes, like class names are included from parents

```html
<meta ...></div><div></div><div></div><div class="root-221" role="textbox"><b>Donda</b> is better than CLB</div>
```
**Device Information**
 - OS: Win 11
 - Browser: Microsoft Edge
 - Version 94.0.992.50

**Additional context**
This issue is particularly problematic for projects (like ones using `@fluentui/react` to manage their styles) using css class names generated at runtime.

**Comment by JiuqingSong** [comment]
would you please also get the full HTML inside the editor when you call getContent(), you can do this using a debugger, see if those classes are already in the editor.

If they are already there, getContent() will take whatever inside editor into the HTML result. It is possibly added by other component such as FluentUI, especially if you have code to add them into the editor. In that case, you need a plugin to handle ExtractContentWithDOM event to remove them.

If you can create a minimum review (using code pen or similar tool) then we can debug see how it happens. With current repro step I can only guess the reason, but not a specific fix.
