### ISSUE TITLE
roosterjsUnsafeConvertHTML Trusted Types policy is required even for users who don't use HtmlSanitizer

### ISSUE THREAD

**Issue by shhnjk** [microsoft/roosterjs#676]
**Describe the bug**
When using RoosterJS editor with following Trusted Types policy, the initialization fails.

```
Content-Security-Policy: require-trusted-types-for 'script'; trusted-types dompurify;
```

Following is the error I get.
```
Refused to create a TrustedTypePolicy named 'roosterjsUnsafeConvertHTML' because it violates the following Content Security Policy directive: "trusted-types dompurify".
```

**Expected behavior**
If RoosterJS editor is used without HtmlSanitizer, it should not require `roosterjsUnsafeConvertHTML` Trusted Types policy.

**Device Information**
 - OS: Windows 10
 - Browser: Edge
 - Version: 94

**Additional context**
I think there are still places where HtmlSanitizer is still being used in RoosterJS editor such as following.
https://github.com/microsoft/roosterjs/blob/73c8d5540ac4721ed23a0365654ab5398d1f8fb6/packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts#L152-L155

Which creates `roosterjsUnsafeConvertHTML` Trusted Type Policy.

**Comment by JiuqingSong** [comment]
Fixed in #689
