### ISSUE TITLE
Request picker plugin dismiss trigger information to be returned

### ISSUE THREAD

**Issue by leong985664** [microsoft/roosterjs#684]
Can we add the dismiss trigger information (e.g. ESC, typing through, mouse click) as an optional parameter in the onIsSuggestingChanged method for the callers to perform additional tasks on certain dismiss triggers?

**Comment by JiuqingSong** [comment]
Please feel free to publish a PR to add the parameter.

**Comment by JiuqingSong** [comment]
Close this one since no PR yet. Feel free to reactivate if there is a PR target to this issue is made.
