### ISSUE TITLE
RoosterJS not working in Vue3 / Vite

### ISSUE THREAD

**Issue by AlphaGeek** [microsoft/roosterjs#694]
I am trying to use RoosterJS in a Vue3 project that uses Vite and getting the attached error.   Here is the initialization of the editor...same code works in another Vue2 app we have that just uses webpack:

methods: {
    initializeEditor() {
      this.roosterjs = require('roosterjs')
      let editorDiv = document.getElementById(this.id, {
        defaultFormat: { backgroundColor: 'white', textColor: 'black' }
      })

![error](https://user-images.githubusercontent.com/1265543/142646209-79d1b541-bce4-49fc-8e05-ec9b1f33bcd7.png)

We are not using TS.

Thanks,

**Comment by JiuqingSong** [comment]
Can you build a simple repro package so that we can try?

This most likely related to your project config or dependency.
