### ISSUE TITLE
Add an option for restoring selection after cut/copy

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#698]
**Describe the bug**
Currently roosterjs restores selection after handling cut or copy events. However, the default behavior of Android WebView is to clear the selection after cut or copy. Can we add an option for the selection restoration in `CopyPastePlugin`? so that we can disable it on Android app.

**To Reproduce**
1. Open roosterjs demo page on Android device.
2. Input some texts and long press to select them. 
3. Click the 'Copy' option in context menu.
4. See error.

**Expected behavior**
The selection should be cleared after copy on Android device.

**Screenshots**
Default behavior of Android WebView, the selection is cleared:

https://user-images.githubusercontent.com/67583056/145038474-c950a37e-ec0f-45da-948c-eab8a7470ce2.mp4

The behavior of roosterjs, the selection is restored:

https://user-images.githubusercontent.com/67583056/145038512-7df0415e-086c-41c5-bb6c-4c9e3034c390.mp4

**Comment by BryanValverdeU** [comment]
Thank you for reporting I will check it

**Comment by BryanValverdeU** [comment]
This has been solved, will release the version next Friday.
