### ISSUE TITLE
ImageEdit plugin modifies image src url

### ISSUE THREAD

**Issue by jvandersterren** [microsoft/roosterjs#704]
**Describe the bug**
When using the ImageEdit plugin, relative image src urls are changed to the fully qualified url after any interaction with the image has occurred in the editor. This is happening since the ImageEdit plugin was introduced (in v8.6). The previous ImageResize plugin did not have this behavior.

**To Reproduce**
1. Include the ImageEdit plugin in a RoosterJs project.
2. Insert an image into the editor through the `RoosterJs.insertImage(editor: IEditor, url: string)` API method. Set the url to a relative url (f.e. "files/some-image.jpg").
3. Interact with the image in the editor, f.e. resize the image.
4. Inspect the image src attribute; it has now been modified by the ImageEdit plugin to a fully qualified url (f.e. "https://www.my-hostname.com/files/some-image.jpg").

**Expected behavior**
The image src url should not be modified by the ImageEdit plugin.

**Device Information**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 96

**Additional context**
I'm using the editor in a content management system, where the hostname & root url of the cms is not necessarily the same as the that of the published website. I am relying on the image src to be relative, so I can update the src with the correct hostname & root myself during back-end rendering. Therefore the url should not be modified by the ImageEdit plugin.

**Comment by JiuqingSong** [comment]
Thanks for reporting the issue.

My suggestion is not to use relative url for image. The HTML content with relative url will not work correctly once it leaves current path, so absolute url is the expect behavior. If you'd like to make it always using relative url, you can add a plugin to modify the url when retrieve HTML content by handling ExtractContentWithDOM event.

**Comment by jvandersterren** [comment]
A relative url is a perfectly valid url and has its uses, one of which I explained in the additional context of this issue. If I wanted to use an absolute url, I would have inserted the image with an absolute url. HTML content with a relative url will work correctly for the cases that it is intended, so absolute url is not at all always the expected behaviour. 

In any case, an HTML editor should not force that decision on us. You can be sure that no developer that uses RoosterJs is expecting it to change image urls without their knowledge. Therefore this is still a bug, and this issue should not have been closed. I have tried to fix it in the source, but unfortunately I don’t have enough JS expertise to fix it myself.
