### ISSUE TITLE
Many errors when implementing web component with microsoft/fast-element

### ISSUE THREAD

**Issue by sayers24** [microsoft/roosterjs#706]
I'm trying to implement this editor in the https://www.fast.design/ framework and I'm getting console errors:
- Cannot read property 'getSubStringBefore' when typing spacebar
- Cannot read property 'collapsed' when backspacing
I also get undesired behavior when using the commands. Highlighting text and toggling bold will unselect my selection and regardless of whether text is selected, it seems to place the cursor at the start of the field. 

**To Reproduce**
1. Go to [Stackblitz with FAST implementation](https://stackblitz.com/edit/typescript-fxtnn4)
2. Type text in the field, highlight it, then click the "B" button to try to bold it
3. Type text, then click the "B" button, continue typing
4. Type spacebar
5. Type backspace

**Expected behavior**
- Highlighting text then clicking the "B" should bold selection and maintain selection
- Clicking the "B" without highlighted text should maintain position in editor

**Additional context**
I suspect these are just side effects of some compatibility issue between RoosterJS and FAST and not related to these specific actions.

**Comment by JiuqingSong** [comment]
Currently putting roosterjs under a custom tag with Shadow DOM is not a supported scenario. Because in that case the active element will be the custom tag instead of the real editor element, and it will fail the check if a given element is inside editor, then it causes a lot of other unpredictable errors, including the errors you have seen.

**Comment by JiuqingSong** [comment]
close this issue since this is an unsupported scenario.
