### ISSUE TITLE
Align center text doesn't align bullet and numbering marker

### ISSUE THREAD

**Issue by chriszyyy** [microsoft/roosterjs#707]
In demo page, why align center or align right doesn't align bullet and numbering?

![image](https://user-images.githubusercontent.com/28225163/146757956-6755b119-87bc-45c4-b7db-71fd4c859868.png)

**Comment by JiuqingSong** [comment]
Assign to @juliaroldi to take a look.

**Comment by juliaroldi** [comment]
It happens because the setAligment api sets text-align to the li element
