### ISSUE TITLE
Cursor jumps to the beginning unexpectedly

### ISSUE THREAD

**Issue by Foolment** [microsoft/roosterjs#709]
**Describe the bug**
After typing a space key or other symbol keys, the cursor will jump to the beginning unexpectedly.
Able to reproduce stably by using Sougou Pinyin in Mi 10 device.

**To Reproduce**
1. Open [RoosterJs Sample Site](https://microsoft.github.io/roosterjs/index.html) in the Chrome Android
2. Enter or paste some long content into editor
3. Move the cursor to somewhere and type something
4. Type a space key and the cursor will jump to the beginning of the content

**Expected behavior**
Cursor should stay where we were typing.

**Screenshots**
[Screen Recording](https://user-images.githubusercontent.com/3321518/147334680-af366aec-0ce7-46c1-bba0-859a5b9d5c3f.mp4)

**Device Information**
 - OS: [Mi 10, Android 11]
 - Browser [Chrome Android]
 - Version [96.0.4664.45]

**Additional context**
We are able to reproduce both in Sample Site and Outlook Android.
Bug tickets in Outlook Android: [BUG 4219847](https://office.visualstudio.com/Outlook%20Mobile/_workitems/edit/5621736/)

**Comment by Foolment** [comment]
Guess it's related to the composition input.

**Comment by JiuqingSong** [comment]
I don't have an Android device for now, but it sounds like UndoPlugin and selection path may be related. Can you try to disable undo plugin (e.g., clear all event handling code in UndoPlugin class) and see if it still happen? That can help us reduce the scope.

**Comment by Foolment** [comment]
I commented all the code inside `onPluginEvent()`, `onKeyDown()`, and `onKeyPress()` functions of `UndoPlugin.ts`, still reproduced.

**Comment by JiuqingSong** [comment]
ok, then maybe comment out more plugins. 

It sounds like something related to Android device, but I don't have any environment to test it. If you know how to fix, please go ahead to publish a PR.

**Comment by JiuqingSong** [comment]
According to https://github.com/microsoft/roosterjs/issues/710, this seems an issue of Android.
