### ISSUE TITLE
PickerPlugin fails to restore cursor position after replaceNode

### ISSUE THREAD

**Issue by yifax** [microsoft/roosterjs#710]
**Describe the bug**
PickerPlugin sometimes cannot restore cursor selection back to its original position after processing `insertNode`. `insertNode.ts/core.api.selectRange(core, rangeToRestore)` won't take effect. We found this issue when testing the mention feature in Outlook compose, which is drived by PickerPlugin in the JS level.

**To Reproduce**
1. Add some mentions in compose area of the latest Outlook DF/Dev build
2. At some point, cursor will be set to the front after a new mention is commited

**Expected behavior**
Cursor stays at the end of new mention

**Screenshots**
[insertNode.ts](https://user-images.githubusercontent.com/14918900/148710548-1dcd2620-7796-48aa-8baa-d41473ff4801.mp4)
[selectRange.ts](https://user-images.githubusercontent.com/14918900/148710588-b67b56cd-4cfe-4d7a-b25e-8698b28d7b5c.mp4)

**Device Information**
 - OS: Android 11
 - Browser: WebView
 - Version: 96.0.4664.92

**Additional context**
In the video record, we can see that the cursor was set to the front after processing node's replacement. However, the following restore range logic won't take effect. Although `rangeToRestore` seems to have the correct node value, `core.api.selectRange` did not set cursor back to this postion. Inside selectRange(), `core.domEvent.selectionRange = range;` was not triggered for some reasons.

**Comment by JiuqingSong** [comment]
I can't see both videos and get error like:

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-12-31T05:42:25Z</Expires>
<ServerTime>2022-01-05T21:00:19Z</ServerTime>
<RequestId>CP4Q5KS3J18Z9V5T</RequestId>
<HostId>PzaZWAx85UZHRHYnBYo2vHZv6ocuxKpLZQe2pokyKNcO67nNpl+VWdARSzHH6V73djmSl1CwPDA=</HostId>
</Error>

**Comment by yifax** [comment]
> I can't see both videos and get error like:
> 
> `AccessDenied` Request has expired 2021-12-31T05:42:25Z 2022-01-05T21:00:19Z CP4Q5KS3J18Z9V5T PzaZWAx85UZHRHYnBYo2vHZv6ocuxKpLZQe2pokyKNcO67nNpl+VWdARSzHH6V73djmSl1CwPDA=

Sorry my bad! Updated with internal video link in the original post.

**Comment by JiuqingSong** [comment]
Ok. I can see the video now. Unfortunately, I don't have any android device or develop environment to test it. If you have any idea how to fix it, please go ahead to make a PR.

**Comment by yifax** [comment]
Debug to lower level and it seems `DOM.Selection.addRange()` has a bug on version = 9x
Cannot repro on versionName=87.0.4280.141
Close this ticket for now since we may need Google to fix it.
