### ISSUE TITLE
Unexpceted background after turing some content into bullet in iPad/iPhone when Auto-Correction is enabled

### ISSUE THREAD

**Issue by huahuahu** [microsoft/roosterjs#712]
**Describe the bug**
Unexpceted background after turing some content into bullet in iPad/iPhone when Auto-Correction is enabled

**To Reproduce**
1. Open iPad or iPhone
1. Turn Auto-Correction on in System Settings -> General -> Keyboard
2. Open the [demo page](https://microsoft.github.io/roosterjs/index.html)
3. Type some character. The characters are in selected state. There is background color for the characters. 
4. Click Bullet button to turn the charaters into bullet.
5. The background color still remains.

**Expected behavior**
The background color should disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/5757671/148151153-31ac84bf-525f-4f58-9832-e9d9dd7c6556.png)

![Large GIF (706x934)](https://user-images.githubusercontent.com/5757671/148151396-72eb9488-7a9a-41aa-acba-72390d17b73c.gif)

**Device Information**
 - OS: iOS
 - Browser Safari
 - Version 8.11.5

**Additional context**
I don't know whether it is a Apple only bug.

**Comment by JiuqingSong** [comment]
Looks like a bug of iOS. We don't have the control to such background, it is added by iOS.

**Comment by huahuahu** [comment]
Can you tell me how can repro it without roosterjs? I want to file a bug for Apple.

**Comment by JiuqingSong** [comment]
I can repro with the code below. It is just a very simple html page, no roosterjs is involved at all.

```html
<!doctype html>
<html>
<body>
<div id=div1 style="border: solid 1px black; width: 400px; height: 100px" contenteditable></div>
<button id=b1>test</button>
<script>
document.getElementById("b1").addEventListener("click", () => {
  var div1 = document.getElementById("div1");
  div1.focus();
  document.execCommand("insertorderedlist");
});
</script>
</body>
</html>
```

**Comment by huahuahu** [comment]
bug in webkit: https://bugs.webkit.org/show_bug.cgi?id=235056
