### ISSUE TITLE
Simulating typing into editor within a test case

### ISSUE THREAD

**Issue by Zeddox** [microsoft/roosterjs#714]
Hi, I'm working on implementing testing of our usage of the roosterjs editor. I'm currently unable to see content changes in my test case when trying to simulate typing in the editor.

Here's a simple jest test case:
```typescript
test.only('sets editor content', () => {
    const roosterDiv = document.createElement('div');
    document.body.append(roosterDiv);
    const rooster: IEditor = new Editor(roosterDiv, {
        plugins: [new ContentEdit(), new Paste(), new HyperLink()],
        defaultFormat: {}
    });

    roosterDiv.focus();
    roosterDiv.dispatchEvent(new KeyboardEvent('keyup', { key: 'A', code: 'KeyA' }));

    const content = rooster.getContent();
    expect(content).toContain('<div>A</div>');
});
```

The test case fails because the content returned is: `<div><br></div>`

How can I go about simulating the editing of content? I'd like to not use the Editor interface directly if possible.

Thanks!

Additional context: I've written a React wrapper around the editor and would like to use the [@testing-library/user-event](https://testing-library.com/docs/ecosystem-user-event#typeelement-text-options) library to simulate typing using `userEvent.type` to test my implementation and custom plugins as an end user would use the component.

**Comment by JiuqingSong** [comment]
Your code is not testing roosterjs, but actually testing browser behavior. I tried to remove all roosterjs related code from your code and it is still not working:
```ts
            const roosterDiv = document.createElement('div');
            document.body.append(roosterDiv);
            roosterDiv.focus();
            roosterDiv.dispatchEvent(new KeyboardEvent('keyup', { key: 'A', code: 'KeyA' }));
            const content = roosterDiv.innerHTML;
            console.log(content);
```

So you need to try with a simple DIV first.

**Comment by Zeddox** [comment]
Thanks for looking at this. I think my attempt to narrow down the test case is not explaining my intent correctly.

Here's the test case I have written:
```typescript
test('can set text field content', () => {
        render(
            <Customizer settings={{ theme: { ...TestTheme } }}>
                <InlineEditableRichTextField ariaLabel={'Test Rich Text Field'} value={'<div>Initial Value</div>'} />
            </Customizer>
        );

        const input = screen.getByLabelText('Test Rich Text Field');

        userEvent.type(input, 'Foo');

        expect(within(input).getByText('Foo', {exact:false})).toBeInTheDocument();
    });
```

The `InlineEditableRichTextField` is a React component we've written to wrap the RoosterJs editor instance. `Customizer` is from the Microsoft Fluent UI package.

I can see that the `userEvent.type` call is raising `PluginEventType.KeyUp` events in a plugin I've written. However, within the plugin, the `this._editor.getContent()` call, within the plugin's `onPluginEvent` handler, doesn't return content with the changed value. In a browser, typing into the RoosterJs editor raises the event, but there the `this._editor.getContent()` call does return the entered content.

Here's the `onPluginEvent` handler for reference:
```typescript
onPluginEvent(event: PluginEvent) {
        if (
            this._editor?.hasFocus &&
            (event.eventType === 7 /*PluginEventType.ContentChanged*/ || event.eventType === 2) /*PluginEventType.KeyUp*/
        ) {
            const content = this._editor.getContent();
            this._contentChangedCallback(content);
        }
    }
```

Ultimately, I'm trying to test as if the user were typing into the text field.

Appreciate your help with this issue :)

**Comment by JiuqingSong** [comment]
Please check if userEvent.type(...) really added the text into editor, from the UI, but not from the code. If it doesn't appear in the UI, then it is the right behavior that code didn't get it.

Simulate a user input event is not a part of roosterjs, so you need to make sure it works without roosterjs first.

**Comment by Zeddox** [comment]
@JiuqingSong Thanks for your help with this. JSDOM does not support `contenteditable` ([JSDOM github issue](https://github.com/jsdom/jsdom/issues/1670)), so I've resolved to using the IEditor interface for setting content and ensuring our wrapper reacts correctly.

**Comment by JiuqingSong** [comment]
No. RoosterJs support multiple instances, you can put as many instances as you want in same page. So there is no way to tell which instance you want.

But since the editor is created from your code, you can always store it anywhere you need.
