### ISSUE TITLE
Format issues (Firefox only)

### ISSUE THREAD

**Issue by yxlee61** [microsoft/roosterjs#734]
**Describe the bug**
1. After entering some text, and wanting to apply formatting (Bold, Italic or Underline) to future text, clicking on any format button will cause the cursor to jump to the beginning of the editor.
2. Highlighting some text and applying a format also causes the cursor to jump to the beginning of the editor, with formatting not applied.

**To Reproduce**
Stackblitz: https://angular-7gujuu.stackblitz.io/
Demo editor (Angular): https://github.com/yxlee61/Angular-RoosterJS

**Expected behavior**
1. Cursor stays in place
2. Highlighted text remains highlighted, with format(s) applied.

**Additional context**
This issue seems to only occur in Firefox. Works fine in Chrome or Edge. Unsure about Safari.

**Comment by JiuqingSong** [comment]
It doesn't happen to me in the demo site: https://microsoft.github.io/roosterjs/index.html

Is there an existing demo page I can test instead of the github projection page?

**Comment by yxlee61** [comment]
I added a stackblitz link for our implementation: https://angular-7gujuu.stackblitz.io/

I noticed that the demo site is running on React. Our implementation is in Angular.

**Comment by JiuqingSong** [comment]
I saw error in console when click button, possibly related:

ERROR TypeError: component.onTouched is not a function
    createEditor rooster-js-editor.service.ts:24
    Angular 14
    createEditor rooster-js-editor.service.ts:24
    ngAfterViewInit app.component.ts:24
    Angular 33
    Qt webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    Oe webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    U webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    u webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    Angular 4
    Qt webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    Oe webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    U webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    R.prototype[m.resolveInstantiate]/</</< webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    R.prototype[m.resolveInstantiate]/</< webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    promise callback*R.prototype[m.resolveInstantiate]/< webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    promise callback*R.prototype[m.resolveInstantiate] webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    import webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    promise callback*m.prototype.import webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    import webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:15
    s webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:8
    promise callback*s/< webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:8
    s webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:8
    s webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:8
    bootDefaultApp webcontainer.ed0127d77976e01ff6c93dcdeb0ce95d6ebd8177.js:8
    promise callback*Ze preview-a214a06f7a20.js:2
    _preboot preview-a214a06f7a20.js:2
    Xe preview-a214a06f7a20.js:2
    _preboot preview-a214a06f7a20.js:2
    promise callback*18528/window._preboot preview-a214a06f7a20.js:2
    Angular 2
errors.ts:30:22


source code (from your project):

        container.addEventListener('blur', (_) => component.onTouched());

**Comment by JiuqingSong** [comment]
And fyi, roosterjs is framework-independent, it can run with pure javascript without any framework (react, angular, ...).

**Comment by yxlee61** [comment]
Removed the following line but the bugs are still occurring:

`container.addEventListener('blur', (_) => component.onTouched());`

**Comment by JiuqingSong** [comment]
This looks like an issue how Firefox handle focus. I tried to modify all "span" to "button" then it works well to me.

To prove this, I did a test below:
```html
<!doctype html>
<html>
<body>
<span id=span1>test span</span>
<button id=button1>test button</button>
<div contenteditable id="div1">select me</div>
<script>
 function onClick() {
   var selection = window.getSelection();
   var range = selection.getRangeAt(0);
   console.log(range.collapsed);   
 }
 document.getElementById("div1").addEventListener("blur", onClick);
</script>
</body>
</html>
```
Save and open with Chrome/Firefox, select the text "select me", then click span and button, see the out put in console.
Chrome will always output "false"
Firefox will output "true" for the span, but "false" for the button. That is why the selection is lost.

**Comment by yxlee61** [comment]
That resolves the issue. Thank you!
