### ISSUE TITLE
Do you have a detailed design document

### ISSUE THREAD

**Issue by HereSinceres** [Microsoft/roosterjs#76]
current wiki：
This page is under construction. Please come back later, thanks!

Expect：
doc about design compile pack

**Comment by JiuqingSong** [comment]
This is planned. We are making some refactoring to the code now. Once that is finished, we will add more documentation for the new code.

**Comment by JiuqingSong** [comment]
We just added API references here: https://microsoft.github.io/roosterjs/docs/index.html

We will continue improve this document and add more links from existing documents.
