### ISSUE TITLE
Copied Word numbering bullet is not displaying properly in rooster.

### ISSUE THREAD

**Issue by zepei-sun** [microsoft/roosterjs#795]
**Describe the bug**

**To Reproduce**
1. Go to Word and create a random file with the following bullet points: 
![image](https://user-images.githubusercontent.com/101152963/157139411-f334fcb2-9d29-4cc2-8ec4-e7384c307eb9.png)
2. Copy the content and paste it into the rooster editor
3. You will see there are two '1' in the bullet list 
![image](https://user-images.githubusercontent.com/101152963/157139523-50a9f5ec-6503-415e-938a-5b3977e937ff.png)

**Expected behavior**
It should honor the original numbering value.

**Comment by BryanValverdeU** [comment]
This should be fixed with: #1200.
Let us know if you are still able to repro.
