### ISSUE TITLE
Cut failed on Android since we collapse selection range before deleteSelectedContent

### ISSUE THREAD

**Issue by yifax** [microsoft/roosterjs#797]
**Describe the bug**
Cut operation is no longer working on Android. Its behavior becomes the same as copy. Selected range will not be deleted, even though it will still be coped to clipboard.

**To Reproduce**
1. Open RoosterJS in Chrome [Demo](https://microsoft.github.io/roosterjs/index.html)
2. Use F12 to turn on Dev Tool
3. Click on "Switch to Simulator/Phone" button to view demo in "Android" user agent
4. Type something and try cut

**Expected behavior**
Selected range is copied and then deleted

**Screenshots**
https://user-images.githubusercontent.com/14918900/157162351-ed64812c-5995-43ac-8457-336f394014e7.mp4

**Device Information**
 - OS: Android
 - Browser Chrome

**Additional context**
We found the root cause to be a regression introduced by this PR: https://github.com/microsoft/roosterjs/pull/702
To clear selection after copy/cut, now we call `range.collapse();` in `CopyPastePlugin.prototype.cleanUpAndRestoreSelection`
This works fine for copy operation. However, for cut, `cleanUpAndRestoreSelection` is called before `if (isCut) {...}`.
The suggested fix here is to move `cleanUpAndRestoreSelection` after `if (isCut) {...}`, or only restrict it to copy only.

Also, since `range.collapse();` is wrapped by Android environment check, this regression only repro on Android side.
That's why in the video, first 4 cut operations are okay. After we fresh browser, the user agent change to Android 6.0 on Chrome's simulator mode. And then, it repros.

![image](https://user-images.githubusercontent.com/14918900/157162331-40a7318e-7a6c-417e-8028-a802de8f9ad6.png)

**Comment by BryanValverdeU** [comment]
Thank you for reporting.

I will take a look.
