### ISSUE TITLE
Manually trigger Paste Event

### ISSUE THREAD

**Issue by rpashankar** [microsoft/roosterjs#809]
**Feature:**
Copy files/images(ctrl+c) from local and paste it into rooster editor manually using paste button outside the ribbon or  not using ctrl+v

**example**:Outlook top paste button

** working with Solution:**
1.document.executecommand("paste")-depreciated
2.navigator.read()-reading clipboard data

Problem:
copy image/files from local and tried to paste then getting error like "no valid clipboared data".i used metod navigator.read().
Also,window does not have property like window.clipboaredData.I am not using ctrl+c so event is not triggerring and i can not use.e.clipboardData

Any way in rooster to fetch clipboard data without triggering event? or any idea to implement it?

**Comment by JiuqingSong** [comment]
All these limitation are from browser. Roosterjs also run in browser so it has the same limitation. We don't have other solution to paste since it has security issue.

**Comment by JiuqingSong** [comment]
Consider user copies some sensitive information such as bank account or social security number, and our code can read clipboard without user's action, then our code get easily get those information, which is every unsecure.
