### ISSUE TITLE
Dragging image (with Resize Image plugin) from one location to another creates new image

### ISSUE THREAD

**Issue by adriantran** [microsoft/roosterjs#85]
Repro:

1. Type some text
2. Paste an image
3. Move image via drag to the beginning (before the text)

**Comment by adriantran** [comment]
see attempt here: https://github.com/Microsoft/roosterjs/tree/users/adtran/drag-image-fix-attempt

**Comment by JiuqingSong** [comment]
adding undo snapshot after Drop event is finished caused another issue, say you type something then do a drag and drop, then undo, the text you just typed will also be removed.

Hope we can find a way to better add undo snapshot which is not conflict with drop event.

**Comment by JiuqingSong** [comment]
Fixed in 6.14.1 for Chrome & Firefox. Still has the issue in Edge and IE.

**Comment by JiuqingSong** [comment]
close bug for Edge/IE only
