### ISSUE TITLE
TableCellSelection Plugin is not considering the Cell Spans

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/roosterjs#861]
**Describe the bug**
When selecting the tables we are not considering the Table Spans, which cause weird behaviors in tables with merged cells.

Eg
![image](https://user-images.githubusercontent.com/8291124/160442750-fa3b9153-b9a9-4fd9-944d-9924cece6d57.png)

Vs Word
![image](https://user-images.githubusercontent.com/8291124/160442798-d2f6f0f3-9d45-482f-b61e-f70faae94758.png)

**Comment by JiuqingSong** [comment]
@BryanValverdeU  is this still active?

**Comment by BryanValverdeU** [comment]
@JiuqingSong yes
