### ISSUE TITLE
Default Format changed after switching to dark mode and then switching back

### ISSUE THREAD

**Issue by haven2world** [microsoft/roosterjs#904]
**Describe the bug**
If we set the value of the `textColor(s)`/`backgroundColor(s)` of `defaultFormat` to `undefined` when we initialize the RoosterEditor, and everything works well in light mode. But if we switch to dark mode and `reCalculateDefaultFormat` in `LifecyclePlugin` will be triggered and the default format will be changed. And even if we switch back to light mode, the default format won't be restored.

**To Reproduce**
1. Open roosterJS Demo site
2. Clear all content and then enter some new lines
3. Take a look at the inline style of the added lines
4. The inline style is empty
5. Turn on Dark mode
6. Clear all content and then enter some new lines
7. Take a look at the inline style of the added lines
8. The inline style has a dark background and white font color
9. Turn off dark mode
10. Clear all content and then enter some new lines
11. Take a look at the inline style of the added lines
12. There are still some inline style

**Expected behavior**

**Screenshots**
Step 4:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/17299418/162714138-a90de422-ffe1-4afa-8a81-b1b692ca4d55.png">
Step 8:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/17299418/162714445-872cf0bd-5dc1-4ba2-8ae9-e1cb53fdcd32.png">
Step 12:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/17299418/162714880-c77fe92e-1004-4e64-ad91-7ec529ca5d9f.png">

**Device Information**
 - OS: Mac OS
 - Browser chrome
 - Version 100.0.4896.75 (Official Build) (x86_64)

**Additional context**

**Comment by JiuqingSong** [comment]
Fixed in #1683
