### ISSUE TITLE
Some style elements in table are removed after pasting

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#907]
**Describe the bug**
After pasting a table in rooster editor, the `border`, `cellspacing` and `cellpadding` style in `<table>` is removed, and the style of table is broken. The style elements seem to be removed by the sanitizer in the `createPasteFragment`. 

The original table: 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/29978667/163572212-2d4fe38e-1e03-4dc9-9da2-0216b0c79a0f.png">
```
<table width="100%" border="0" cellspacing="0" cellpadding="0" style="color: rgb(16, 110, 190) !important; font-size: 87.5%; background-color: rgb(233, 243, 251) !important; border-radius: 4px;">
<tbody><tr>
<td><table border="0" cellspacing="0" cellpadding="0">
<tbody><tr>
<td height="8" style="line-height:0;">&nbsp;</td></tr></tbody></table></td></tr>
<tr itemscope="" itemprop="option" itemtype="http://schema.org/Event">
<td align="center"><time itemprop="startDate" datetime="2022-04-15T12:30:00+08:00">12:30 PM </time>- <time itemprop="endDate" datetime="2022-04-15T13:00:00+08:00">1:00 PM </time>(GMT+8) </td></tr>
<tr>
<td><table border="0" cellspacing="0" cellpadding="0">
<tbody><tr>
<td height="8" style="line-height:0;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table>
```

The table after pasting: 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/29978667/163572160-a7a6357c-999b-4dfa-99d3-9962de83667b.png">

```
<table style="font-size:13.125px;color:rgb(16, 110, 190) !important;background-color:rgb(233, 243, 251) !important;border-radius:4px" width="100%">
<tbody><tr>
<td><table>
<tbody><tr>
<td style="line-height:0" height="8">&nbsp;</td></tr></tbody></table></td></tr>
<tr><td align="center">
<time datetime="2022-04-15T12:30:00+08:00">12:30 PM<span>&nbsp;</span></time>-<span>&nbsp;</span>
<time datetime="2022-04-15T13:00:00+08:00">1:00 PM<span>&nbsp;</span></time>(GMT+8)</td></tr><tr><td>
<table><tbody><tr>
<td style="line-height:0" height="8">&nbsp;</td></tr></tbody></table></td></tr></tbody></table>
```

**To Reproduce**
1. Paste the HTML table element in roosterjs demo
2. Check the result. 

**Expected behavior**
The style elements shouldn't be removed. 

**Device Information**
 - OS: Android
 - Browser: Chrome
 - Version: 100.0.4896.88

**Comment by JiuqingSong** [comment]
You can create a plugin and handle BeforePasteEvent to customize the sanitize behavior, then you can decide what to keep and what to remove. Please take https://github.com/microsoft/roosterjs/blob/08f4c56828e76b8cb0983422d11e275bac2a0346/packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/convertPastedContentFromWord.ts#L15 as example.

**Comment by Rain-Zheng** [comment]
@JiuqingSong Thank you for the instruction! I'll try this solution.
