### ISSUE TITLE
Creating link does not replace the whole selected text

### ISSUE THREAD

**Issue by mathildebm** [microsoft/roosterjs#917]
**Describe the bug**
Creating a link does not replace the whole selection range, when the selection includes several \<div\> or \<span\>

**To Reproduce**
It is reproducible on the [demo site](https://microsoft.github.io/roosterjs/index.html) 
1. Write some text on several lines, with some line breaks
2. Select lines of text with at least 2 line breaks
3. Click on button to create link
4. Write in the 'Web address (URL)' input 
5. Click on OK
6. See error: the whole selected text or part of the selected text is remaining. 
In the HTML we can see that 2 links with the same url have been created: one for the remaining text, one for the correct new text

**Expected behavior**
The link should replace the whole selected text, and create only one link

**Screenshots**
![Capture d’écran de 2022-04-15 12-10-04](https://user-images.githubusercontent.com/104149443/164473806-28060631-a0d5-4c0b-ae1d-70e6bc827d87.png)
![Capture d’écran de 2022-04-15 12-11-08](https://user-images.githubusercontent.com/104149443/164473816-a924f814-cbea-4086-85eb-ee1dc4a99876.png)
![Capture d’écran de 2022-04-15 12-11-27](https://user-images.githubusercontent.com/104149443/164473829-79f2cd07-e29e-420f-9c52-2eddc1043a37.png)

**Device Information**
 - Browser: Chrome, Firefox

**Additional context**
This is reproductible on the Demo site

**Comment by JiuqingSong** [comment]
@BryanValverdeU  please try to repro, thanks.
