### ISSUE TITLE
Pasting bullets doesn't preserve level styling

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#920]
1) Copy a bulleted list with multiple levels (I used OneNote)
![image](https://user-images.githubusercontent.com/23065085/164557956-6365717a-6e78-4203-9c3b-ad21f7b4b5a2.png)
2) Paste it in OWA
![image](https://user-images.githubusercontent.com/23065085/164557976-4a52f775-f02a-451a-a842-de7249ea63a6.png)
As you can see, the third level bullet doesn't use the correct bullet type. It's odd because the default third level bullet in OWA is the white square, so there's no reason to change it.
3) Making changes to the list, like creating a new level, fixes the third bullet point but also changes indentation

**Comment by BryanValverdeU** [comment]
The pasting part is fixed, however we may need to also add support on the Content Edit Feature so we do not remove the margins of the list item when writing back

**Comment by JiuqingSong** [comment]
Tested on lates build, everything is working well now.
