### ISSUE TITLE
Double tabbing creates weird ordered list exprience

### ISSUE THREAD

**Issue by jesomekh** [Microsoft/roosterjs#98]
![image](https://user-images.githubusercontent.com/31226374/44690293-22cea700-aa0f-11e8-8a27-758dae47b699.png) 
One tab
![image](https://user-images.githubusercontent.com/31226374/44690303-2a8e4b80-aa0f-11e8-8870-15ff4160604c.png) 
tab again
 ![image](https://user-images.githubusercontent.com/31226374/44690310-2feb9600-aa0f-11e8-8621-e8007de8d3d5.png)

**Comment by JiuqingSong** [comment]
Thanks for reporting this bug. We'll make a fix soon.

**Comment by JiuqingSong** [comment]
Fixed in 6.15.0
