### ISSUE TITLE
Inconsistent style of bullet and number

### ISSUE THREAD

**Issue by Rain-Zheng** [microsoft/roosterjs#980]
**Describe the bug**
The style (font size, bold or italic) of bullet and number is inconsistent with the text. 

**To Reproduce**
1. Open roosterjs demo
2. Create a bulleted or numbered list
3. Select the list and change its style
4. The style of bullet or number is not changed

**Expected behavior**
The style of bullet or number should be changed. 

**Screenshots**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/67583056/168511634-e658fd9a-cba2-477a-ba31-38bb59a28e55.png">

**Device Information**
 - Browser: Chrome
 - Version: 100

**Comment by JiuqingSong** [comment]
This is now solved by Content Model.
