### ISSUE TITLE
Clear formatting should remove all formatting styles

### ISSUE THREAD

**Issue by jesomekh** [Microsoft/roosterjs#99]
Today, clear formatting does not remove a few stylings (bullets, number list, etc)

**Comment by JiuqingSong** [comment]
Current remove format API only removes inline formats, which means format within the selection are removed. However, formats like bullets/numbering as block formats, it is possible that not all content of the block is selected, in that way it is unclear if we should remove those formats. I feel we can either add a parameter or add a new API to deal with those formats.

**Comment by jesomekh** [comment]
If you look at how OneNote approaches it, they understand when text is highlighted that has been formatted with block formats such as bullets, and if you clear format, they'll clear the bullets. I think this behavior makes more sense.

**Comment by jesomekh** [comment]
Repinging here. We're rolling out the text editor in Azure DevOps and the number one piece of feedback we hear is that "clear formatting doesn't work." We have people disabling the feature just for this reason. Is it possible to have clear formatting clear both styles and structures. People are running into weird line spacings that can be brought over from an external copy and paste into the editor. But there's no way to clear it.

**Comment by JiuqingSong** [comment]
Is there a list of styles that we should do specially? For now what I got is:
bullet/neumbering
line spacing

anything else?

The hard part here is these kind of styles can be outside of the selection. For example:
AAABBB
CCCDDD
If you select "BBB" and "CCC", some styles for the whole line are specified before "AAA" so it is not in current selection. One way to do is to clear everything in current block, but this will also clear font and color of "AAA" which is not expected.

**Comment by JiuqingSong** [comment]
For the copy/paste scenario, maybe a better approach is to have something like "paste option". In OWA when you paste with rich format we show a popup to allow user to choose weather you want to paste with format or just plain text. The plain text version will contain no format and only text is pasted.

We already have API to paste with either option in Paste plugin but you need to build your own UI to trigger it.

**Comment by jesomekh** [comment]
I thought about that. I think when people paste in tables for example that carry formatting, they want to maintain that formatting. And I'm assuming that if user A pastes in a table with formatting in light mode (they have no clue it would be illegible in dark mode), then the next day user B comes in and uses dark mode and the formatting is all wonky. There's nothing user A can do at that point.

**Comment by JiuqingSong** [comment]
About dark mode, if I explicitly set the text to black or very deep gray, will it be broken as well when read it from dark mode?

I known OWA did some calcuation about the colors so that even the text is dark in light mode, we convert into light color in dark mode.

Anyway, I agree that pasting with plain text can't fix all the issue, especially for table. So let's discuss on what we can do here.

**Comment by JiuqingSong** [comment]
Fixed in 6.19.0
